### ISSUE TITLE
BOINC should prepend extra arguments, not append

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1013]
**Reported by MattArsenault on 17 Aug 40917798 00:53 UTC**
The way BOINC handles added arguments do not follow POSIX conventions (http://www.lkn.ei.tum.de/arbeiten/faq/man/JAVA-tutorial/essential/attributes/_posix.html)

With POSIX compliant command line arguments, options can't follow arguments. For example, in BSD cp, you can't have options such as -r following the source and destination arguments.

BOINC appends the options to the end of the command line, making it difficult to handle an arbitrary number of trailing arguments.

For example with GPUs and multihreaded applications, BOINC appends "--device N" or "--nthreads N" to control which devices to use to the end of the command line. However this is disruptive and makes it more difficult to use standard argument parsing libraries, and to handle in general particularly when several of these kinds of features could be in use at once.

For example, the milkyway@home server sends out a varying number of parameters after the options depending on the parameters being fit in a workunit. The added arguments at the end make it more difficult to figure out what are the actual parameters.

example_program -x 2.3 --sample --args 1.0 2.0 3.0 4.0 5.0 --device 0 --nthreads 4

Here it would be easy to use proper argument parsing to read the --sample and --args flags, and the -x 2.3 option with its argument. Whatever is left after the options would ideally then just be parameters which can vary in number. Figuring out which they are, particularly in the presence of other numbers (such as the arguments to -x and --device) makes it more work to pick out which these should be than if the extra options were in the compliant place at the start of the command line in the first place.

This should be:

example_program--device 0 --nthreads 4-x 2.3 --sample --args 1.0 2.0 3.0 4.0 5.0

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1037

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by JuhaSointusalo** [comment]
Appending the extra options at the end of the command line allows users to override the options server set.

This was used on LHC/Atlas to override the number of threads used by multi-threaded app before the option was added on the projects website. It is still used there to override memory settings because the server sets too low RAM size for VMs using two threads. It also allows users to easily test different configurations without having to wait for the server to send new tasks and for those tasks to reach the top of the cache.

I would prefer if this feature was not taken away.

In the OP's example it's rather trivial to change the command line to be easier to parse:

`example_program -x 2.3 --sample --args --input 1.0;2.0;3.0;4.0;5.0 --device 0 --nthreads 4`

Change the blanks between parameters to semicolons and then split the big parameter inside the app.

**Comment by lfield** [comment]
We don't have a requirement to be POSIX compliant. As pointed out this may be an issue if we were to try to adopt a  standard argument parsing library but as of yet this is not the case.
