### ISSUE TITLE
Help -> BOINC website … Statusbar text is not specific enough.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1033]
**Reported by JacobKlein on 3 May 41244970 22:13 UTC**
Currently, when hovering over items in the Help dropdown, the Statusbar texts at the bottom are:

Help -> BOINC help ::: Show information about BOINC[Help -> BOINC Manager help ::: Show information about the BOINC Manager[[BR]([BR]])]Help -> BOINC website ::: Show information about BOINC and BOINC Manager[Help -> About BOINC Manager... ::: Licensing and copyright information.

That third one makes it sound like it is a link that includes all content from the first two links!

I propose changing the Help -> BOINC website ... Statusbar text to something like:[[BR]([BR]])]Go to main BOINC website

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1057

**Comment by ChristianBeer** [comment]
related to #770

**Comment by Ageless93** [comment]
@AenBleidd, another cosmetic change. 
This one's found in AdvancedFrame.cpp line 680, and should be called "Show the BOINC web page".

**Comment by AenBleidd** [comment]
@Ageless93, got it

**Comment by CharlieFenton** [comment]
I disagree with this request. Changing the status bar as suggested would simply repeat the information already shown in the menu. The purpose of the status bar text here is to provide a further explanation in addition to what is already in the menu title.

But I have two other problems with the current wording:

[1] As @DavidAnderson wrote on August 12, 2017:
   The goal is to conceal the fact that there are two programs.
   We use "BOINC Manager" to refer to both.
   Where we need to refer to the client, we call it "client".
So "Show information about BOINC and BOINC Manager" seems contrary to this standard. 

[2] Although the string "BOINC Manager" is modified for branding (pSkinAdvanced->GetApplicationName: "BOINC Manager", "World Community Grid - BOINC Manager". "GridRepublic Desktop", etc.) "BOINC is not modified for branding, although "BOINC" is branded in the status bar text for some Help menu items: pSkinAdvanced->GetApplicationShortName. And I question whether it is appropriate to say "Show information about BOINC and GridRepublic Desktop".

**Comment by Ageless93** [comment]
Charlie, right now when I mouse over "BOINC web site" in the BOINC 7.8.1 Help menu, the text in the bar at the bottom of the manager says "Show information about BOINC and BOINC Manager", which isn't correct as that doesn't show on the BOINC web site. It dos show in the Wiki, but that's not where we go to when clicking on the "BOINC web site" link. We do end up on https://boinc.berkeley.edu/

So all I asked for in this case was to change the text showing to "Show the BOINC web page" (or web site).

**Comment by CharlieFenton** [comment]
@Ageless93: sorry, I should have written that I disagree with the suggested new wording, not with this entire request. I do see your point and agree with your concern. But "Show the BOINC web page" or "... web site" just repeats the information already found in the menu title. The status bar text should provide a more detailed explanation of what the menu item does. 

And I wanted to point out what I feel are additional problems with the current wording.

I would suggest something like "See more information about <short application name> on the web", where <short application name> is "BOINC", "World Community Grid", "GridRepublic", etc., since clicking on this menu item should take you to the home page of boinc.berkeley.edu, worldcommunitygrid.org, gridrepublic.org, etc., depending on which "branded" (skinned) version of BOINC you downloaded and installed. Note that all the items in the Help menu replace "BOINC" with "World Community Grid", "GridRepublic", etc. when the manager is branded with those skins.

**Comment by Ageless93** [comment]
All right, that's a possibility. Should the other descriptions also be changed, because they also show double and don't hint that they go to an external website.

**Comment by davidanderson** [comment]
Hi folks - FYI - you've got the wrong person here.  I'm not involved with
this project :-)

**Comment by AenBleidd** [comment]
Fixed via #2088

**Comment by Ageless93** [comment]
Tested with new BOINC Manager built from Master. Checks out.
