### ISSUE TITLE
KB/sec preferences show different values between Web Preferences and Manager

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1076]
**Reported by JacobKlein on 1 Jun 41325960 10:40 UTC**
I've noticed that, when setting KB/sec values in the Web Preferences, the values that are shown in the Manager do not match.

For instance:[Web says 60 Kbytes/sec, Manager says 58.59 KBytes/sec.[[BR]([BR]]If)]If Web says 5 Kbytes/sec, Manager says 4.88 KBytes/sec.

An incorrect conversion is happening on the value, somewhere between setting the value on the Web and showing it in the Manager.

Another test: If Web says 15 Kbytes/sec, Manager says 14.65 KBytes/sec, and the Event Log says "max upload rate: 15000 bytes/sec".

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1100

**Comment by ChristianBeer** [comment]
I could confirm this is still the case. The web interface converts kB to bytes by multiplying 1000 and the Manager is converting bytes into kB by dividing with 1024. This should be made consistent. I tested with the Drupal interface which should in this regard be the same like the normal Web interface.

**Comment by davidpanderson** [comment]
The confusion between KB (1000) and KiB (1024), and same for MB and GB, is  common in BOINC.

We should pick one or the other and use it everywhere, including Mbps, MB, MFLOPS, etc.
I lean very slightly toward the 1000^n meaning; see
https://en.wikipedia.org/wiki/Kilobyte

**Comment by Ferroin** [comment]
I would argue that it should be consistent with the industry.  

For FLOPS, consistency is SI units.
For network speed, it's usually also SI (SI always for bit rates, most of the time for byte rates).
For RAM, it's IEC units (for both the hardware and the software).
For disk storage though, it depends on who you ask, and that's where things get complicated.  Most operating systems report in IEC units for disk storage, but most hardware lists SI units (because the difference saves disk manufacturers money).  Given this, I would argue IEC units for disk space because that will then match up with what the OS itself reports (for most OS'es).

BOINC itself should be consistent for any given unit, but making all the units consistent will result in discrepancies with other software (regardless of whether it uses SI or IEC units),

**Comment by davidpanderson** [comment]
I'm fine with SI for FLOPS and network rates,
IEC for both RAM and disk.
Should we use the MiB, GiB notation for the latter?

**Comment by davidpanderson** [comment]
fixed
