### ISSUE TITLE
launch another boinc mgr -> execv: Permission denied

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1177]
**Reported by toralf on 16 Jul 42651934 12:46 UTC**
Under a stable Gentoo Linux I got that error message in .xsession-errors when I tried to to that action.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1205

**Comment by ChristianBeer** [comment]
This is also happening with current master although I currently don't see the execv: Permission denied error.

Also reported for Ubuntu/Debian: https://bugs.launchpad.net/ubuntu/+source/boinc/+bug/1115607

Easy way to reproduce:
Open boincmgr, open Advanced menu and select "Launch another BOINC manager". Nothing happens.

This appears in the console (or in a logfile somewhere):
execv: Permission denied

Here are the relevant source files:
Gets launched when clicking on menu item: CAdvancedFrame::OnLaunchNewInstance at https://github.com/BOINC/boinc/blob/master/clientgui/AdvancedFrame.cpp#L1585
Should launch the new manager: https://github.com/BOINC/boinc/blob/master/lib/util.cpp#L466

**Comment by CharlieFenton** [comment]
It does work correctly on MS Windows and macintosh, though.

**Comment by LocutusOfBorg** [comment]
I see two issues here:
* the changedir is not working, because running ./boincmgr makes it spawn a new window
* the new window opens correctly, but the old one is killed

**Comment by ChristianBeer** [comment]
I don't see that behavior. The old window keeps open and is unresponsive for the 3 seconds of the `boinc_sleep(3)` further down. What is happening is that after the fork the new process does a chdir and an execv which is failing and then the new manager instance gets terminated by the `exit(errno)` which it normally would not reach.

The question is why is the `execv` failing? One has to check if the arguments of the call are correct. Probably by putting some `fprintf()` in there.

**Comment by LocutusOfBorg** [comment]
fprintfs are not printed :(
I did put a lot of debugging code, and I experience the same behaviour as you, the only difference is that it works correctly when the manager is launched in the same directory.
My guess is that the changedir code is not working
(I launched it locally, and doing a "ps" showed the new window with a different pid, and launched with "--multiple" flag

**Comment by ChristianBeer** [comment]
It turns out this was never implemented for Linux despite the commit 8a79417f1934bbc4cce58d2b76b987e82af74f2f saying that it was.
The problem is that the `execv` call is missing the executable name which only gets detected on Windows and Mac but not Linux. I put in a crude fix that detects the executable name of the manager like this:
```
diff --git a/clientgui/BOINCGUIApp.cpp b/clientgui/BOINCGUIApp.cpp
index 434769b5e4..ead41d7a8a 100644
--- a/clientgui/BOINCGUIApp.cpp
+++ b/clientgui/BOINCGUIApp.cpp
@@ -721,6 +721,17 @@ void CBOINCGUIApp::DetectExecutableName() {

     // Store the root directory for later use.
     m_strBOINCMGRExecutableName = pszProg;
+#else
+    char path[PATH_MAX];
+    memset(path,0,sizeof(path));
+    int ret = readlink("/proc/self/exe", path, PATH_MAX);
+    if ( ret >= 0) {
+        path[ret] = '\0'; // readlink does not null terminate
+        char* name = strrchr(path, '/') + 1;
+        m_strBOINCMGRExecutableName = name;
+    } else {
+        perror("readlink");
+    }
 #endif
 }
```
I didn't investigate side effects or compatibility of this. I didn't get wxWidgets Debug output working so I dumped `fprintf`s to a file to see the parameters actually used for the `execv` call.

**Comment by ChristianBeer** [comment]
I was just wondering why `wxGetApp().GetRootDirectory()` was returning a valid path on Linux when `CBOINCGUIApp::DetectRootDirectory()` is not implemented for Linux. It turns out this detection is happening in [clientgui/BOINCGUIApp.cpp#L631](https://github.com/BOINC/boinc/blob/554c1d41bcf9f3cc479df1c757fa7d5ae7038cbd/clientgui/BOINCGUIApp.cpp#L631).

Although `readlink()` is POSIX specified there is a portability issue with `/proc/self/exe`. See: http://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe
So it seems to be better to detect the executable name earlier using `argv[0]`.

**Comment by LocutusOfBorg** [comment]
it works, unfortunately only when launched with ./ in the same directory... still that chdir is not working.
this instead works for me (and I'll probably upload in Debian)
```diff
--- boinc-7.6.33+dfsg.orig/clientgui/AdvancedFrame.cpp
+++ boinc-7.6.33+dfsg/clientgui/AdvancedFrame.cpp
@@ -1586,7 +1586,7 @@ void CAdvancedFrame::OnLaunchNewInstance
 #endif
     int argc = 2;
     char* const argv[3] = {
-         const_cast<char *>("boincmgr"), 
+         const_cast<char *>("/usr/bin/boincmgr"),
          const_cast<char *>("--multiple"),
          NULL
     };
--- boinc-7.6.33+dfsg.orig/lib/util.cpp
+++ boinc-7.6.33+dfsg/lib/util.cpp
@@ -468,7 +468,7 @@ int run_program(
             retval = chdir(dir);
             if (retval) return retval;
         }
-        execv(file, argv);
+        execv(argv[0], argv);
 #ifdef _USING_FCGI_
         FCGI::perror("execv");
 #else
```

**Comment by LocutusOfBorg** [comment]
execv wants the full path as first parameter (/usr/bin/boincmgr in our case and also for the second parameter in the first position of the array)
e.g. argv[0] = "/usr/bin/boincmgr"
argv[1] = "--multiple"
argv[2] = NULL // needed

so, even if hardcoding is not the best solution, probably changing that argv[0] will fix the issue in a more general way

what do you think?

**Comment by CharlieFenton** [comment]
Unfortunately, a quick search for the various places that run_program is called leads me to conclude that will break several of them:
COPROCS::launch_child_process_to_detect_gpus() in gpu_detect.cpp
CMainDocument::KillGraphicsApp() in MainDocument.cpp (when g_use_sandbox is true)
CMainDocument::WorkShowGraphics() in MainDocument.cpp (when g_use_sandbox is true)
CMainDocument::WorkShowGraphics() in MainDocument.cpp (when g_use_sandbox is true, or on platforms other than a Mac.)
CScreensaver::launch_screensaver() in screensaver.cpp for any platform except MSW
CScreensaver::terminate_v6_screensaver() in screensaver.cpp
CScreensaver::launch_default_screensaver() in screensaver.cpp on Mac

Of course, these could all be corrected, but it will take a bit more extensive changes than those two small patches.
 
Cheers,
--Charlie

**Comment by ChristianBeer** [comment]
`argv[0]` should by convention contain the name (not the path) of the executable. It must not be the same as in the path given to `execv()`. This is used by programs to customize behavior based on the name it was called with. So I don't think we need to change that part.
I indeed didn't test to launch a client in a different directory. But you are correct I could reproduce it. I think this is a problem in [clientgui/AdvancedFrame.cpp#L1601](https://github.com/BOINC/boinc/blob/master/clientgui/AdvancedFrame.cpp#L1601) where the code assumes that the executable is in the current root directory. Which is wrong in the case of Debian where it is in `/usr/bin/` and gets found because that is in `PATH`. The original assumption of the code is that you start the Manager like `./boincmgr`.

What we need is something like `getPathToThisApp()` for Linux that can detect where the original Manager is located. In the Debian case this is not the current directory. This needs to be added to [clientgui/BOINCGUIApp.cpp#L731](https://github.com/BOINC/boinc/blob/master/clientgui/BOINCGUIApp.cpp#L731).

**Comment by ChristianBeer** [comment]
I played a little bit more with this and found a working solution (as in it sets the correct directories). The problem is that it is not portable because `/proc/self/exe` is not available on all Linux distributions. And even if it is available it is not clear that it can be read. I'm quit sure it still works on Windows but if the Windows Manager has a problem to be started in the data directory one has to just put an `#ifdef` around the run_program parameter.

Here is a gist that could help the next one to tackle this problem: https://gist.github.com/ChristianBeer/30723e12c413673e3bc942c55d5eceed

**Comment by LocutusOfBorg** [comment]
what about this one?
```diff
--- boinc-7.6.33+dfsg.orig/clientgui/BOINCGUIApp.cpp
+++ boinc-7.6.33+dfsg/clientgui/BOINCGUIApp.cpp
@@ -765,6 +765,8 @@ void CBOINCGUIApp::DetectExecutableName(

     // Store the root directory for later use.
     m_strBOINCMGRExecutableName = pszProg;
+#else
+    m_strBOINCMGRExecutableName = wxString::FromUTF8(argv[0]);
 #endif
 }

@@ -786,6 +788,8 @@ void CBOINCGUIApp::DetectRootDirectory()

     // Store the root directory for later use.
     m_strBOINCMGRRootDirectory = szPath;
+#else
+    m_strBOINCMGRRootDirectory = ::wxGetCwd();
 #endif
 }
```

**Comment by LocutusOfBorg** [comment]
my solution is not working, I was testing an old version lol

**Comment by LocutusOfBorg** [comment]
@ChristianBeer why this change?
```diff
--- a/clientgui/AdvancedFrame.cpp
+++ b/clientgui/AdvancedFrame.cpp
@@ -1601,7 +1601,7 @@ void CAdvancedFrame::OnLaunchNewInstance(wxCommandEvent& WXUNUSED(event)) {
     wxString strExecutable = wxGetApp().GetRootDirectory() + wxGetApp().GetExecutableName();
 
     run_program(
-        wxGetApp().GetRootDirectory().mb_str(),
+        wxGetApp().GetDataDirectory().mb_str(),
         strExecutable.mb_str(),
         argc,
argv, 
```

this works for me:
```diff
diff --git a/clientgui/BOINCGUIApp.cpp b/clientgui/BOINCGUIApp.cpp
index 434769b5e4..b5c0b8a45b 100644
--- a/clientgui/BOINCGUIApp.cpp
+++ b/clientgui/BOINCGUIApp.cpp
@@ -721,6 +721,17 @@ void CBOINCGUIApp::DetectExecutableName() {

     // Store the root directory for later use.
     m_strBOINCMGRExecutableName = pszProg;
+#else
+    char path[PATH_MAX];
+    memset(path,0,sizeof(path));
+    int ret = readlink("/proc/self/exe", path, PATH_MAX);
+    if ( ret >= 0) {
+        path[ret] = '\0'; // readlink does not null terminate
+        char* name = strrchr(path, '/') + 1;
+        m_strBOINCMGRExecutableName = name;
+    } else {
+        perror("readlink");
+    }
 #endif
 }

@@ -742,6 +753,18 @@ void CBOINCGUIApp::DetectRootDirectory() {

     // Store the root directory for later use.
     m_strBOINCMGRRootDirectory = szPath;
+#else
+    char path[PATH_MAX];
+    memset(path,0,sizeof(path));
+    int ret = readlink("/proc/self/exe", path, PATH_MAX);
+    if ( ret >= 0) {
+        path[ret] = '\0'; // readlink does not null terminate
+        char* name = strrchr(path, '/') + 1;
+        *name = '\0';
+        m_strBOINCMGRRootDirectory = path;
+    } else {
+        perror("readlink");
+    }
 #endif
 }
```

**Comment by ChristianBeer** [comment]
The first argument to `run_program` is the working directory where the new Manager window will be started. The Manager expects this to be the local data directory in order to lookup the content of gui_rpc_auth.cfg for example. Since on Debian RootDirectory is different from DataDirectory this is necessary in case the user wants to connect to `localhost` with the second Manager. Otherwise the new manager will be started in `/usr/bin/`. Take a look at the `.desktop` file in Debian where something similar is done to make sure the Manager is started in the data directory `/var/lib/boinc-client`. It might not be needed but for consistency I changed it.

**Comment by LocutusOfBorg** [comment]
well, I opened a new manager window, connected it to localhost, and it worked correctly... so I presume such hacks are not needed anymore? anyway, lets commit it :)

**Comment by ChristianBeer** [comment]
As I wrote above `/proc/self/exe` is not portable across Linux. The `#else` must be changed to some other string that excludes Mac too. I guess it would be nice to also move the Mac code into these functions in the future.

@Germano0 Can you shed some light on availability of `/proc/self/exe` on Fedora and maybe test my patch there too. I would feel more comfortable creating a PR if this was tested on something else than Debian.

**Comment by Germano0** [comment]
@ChristianBeer why exe is not portable? See table 1.1 at https://www.kernel.org/doc/Documentation/filesystems/proc.txt
Could you please provide the URL of the patch so that I can test it on Fedora?
Thank you

**Comment by ChristianBeer** [comment]
I read a comment in one of the linked SO questions that `/proc/self/exe` is not readable on Ubuntu 12.04. You only need the BOINCGUIApp.cpp portion of my [gist](https://gist.github.com/ChristianBeer/30723e12c413673e3bc942c55d5eceed).

**Comment by LocutusOfBorg** [comment]
well, if the problem is on linux older than 5 years... we can also stop caring :)
The patch works in Debian and the last Ubuntu LTS, and I presume in other linux flavours too.
12.04 will be EOL in some days, so I presume we can avoid the whole issue!

**Comment by Germano0** [comment]
CentOS 6 (still maintained) that is older than the EOL'ed Ubuntu 12.04 uses kernel 2.6.32 and has exportable `/proc/self/exe`. So if you cannot access /proc/self/exe con Ubuntu I think it's an Ubuntu specific problem, and Linus Torvalds is not happy when people introduce kernel bugs in userspace/breaks userspace interfaces.  https://lkml.org/lkml/2012/12/23/75     `/proc/self/exe`  is guaranteed to stay. The opposite would be a breakage in userspace interface `/proc`

**Comment by ChristianBeer** [comment]
That leaves the `GetRootDirectory()` to `GetDataDirectory()` change. I'm fine with not adding this to a PR if the other changes are sufficient for normal user use-cases (opening BOINC via a desktop link).
I'll provide a PR later today.

**Comment by ChristianBeer** [comment]
I added the `/proc/self/exe` stuff as a library function because I wanted to avoid code duplication. I also added some more error checks and meaningful return values. 
The new Manager is still opened in what the old Manager thinks is the root directory which is different from the data directory.
Looking again at [clientgui/BOINCGUIApp.cpp#L631](https://github.com/BOINC/boinc/blob/554c1d41bcf9f3cc479df1c757fa7d5ae7038cbd/clientgui/BOINCGUIApp.cpp#L631) the logic is:
If no commandline option is specified the Manager assumes that the current working directory is the root and data directory. Since we now correctly determine the root directory on Linux (`/usr/bin`) which is different from the data directory (`/var/lib/boinc-client`) we should start the new Manager in the data directory via:
```diff
--- a/clientgui/AdvancedFrame.cpp
+++ b/clientgui/AdvancedFrame.cpp
@@ -1601,7 +1601,7 @@ void CAdvancedFrame::OnLaunchNewInstance(wxCommandEvent& WXUNUSED(event)) {
     wxString strExecutable = wxGetApp().GetRootDirectory() + wxGetApp().GetExecutableName();
 
     run_program(
-        wxGetApp().GetRootDirectory().mb_str(),
+        wxGetApp().GetDataDirectory().mb_str(),
         strExecutable.mb_str(),
         argc,
argv, 
```
but I'm still not 100% sure this doesn't break things since the Manager is not my area of expertise. the point is with this change the newly started Manager will have the wrong information where the data directory is if it is different from the root directory (which is where the `boincmgr` executable is).
