### ISSUE TITLE
Add Project - Adding a project that is down results in error dialog

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1212]
**Reported by JacobKlein on 21 Oct 43272476 05:57 UTC**
Rom,

When I add a project with a made-up URL (like, for instance, http://www.madeupname.testin.com )...
The friendly dialog box says:
Project temporarily unavailable
The project is temporarily unavailable.
Please try again later.
... and the Event Log says:
4/9/2013 1:21:00 AM |  | Fetching configuration file from http://www.madeupname.testin.com/get_project_config.php
4/9/2013 1:21:02 AM |  | Project communication failed: attempting access to reference site
4/9/2013 1:21:04 AM |  | Internet access OK - project servers may be temporarily down.

BUT

When I add a project that is within the official list, which just happens to be down (like Superlink@Technion)...
The unfriendly dialog box says:
Failed to add project
An error has occurred;
check the Event Log for details.
Click Finish to close.
... and the Event Log says:
4/9/2013 1:23:20 AM |  | Fetching configuration file from http://cbl-boinc-server2.cs.technion.ac.il/superlinkattechnion/get_project_config.php
4/9/2013 1:23:27 AM |  | Project communication failed: attempting access to reference site
4/9/2013 1:23:28 AM |  | Internet access OK - project servers may be temporarily down.

Shouldn't both dialog boxes have been friendly here?
Especially since the Event Log entries are the same?

Because this happens in 7.0.28 also, I guess I'll create a ticket.

Thanks,
Jacob 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1240

**Comment by ChristianBeer** [comment]
Although the log messages look the same the logic behind that handles the error values differently. One just needs to find out what error cases are already handled and which need to be added. Switching the logic seems to be the best case. A made up or outdated URL usually means no DNS lookup which should prompt the error dialog. If the URL could be resolved but we get a 404 on `get_project_config.php` the error dialog should also be displayed since the URL does not seem to belong to a project. In any other case it seems to be a legit project URL but we can't connect so show the project temporarily down dialog.

**Comment by AenBleidd** [comment]
Closing this for now as 'wonfix' since I don't believe it worths time to fix it
