### ISSUE TITLE
configure error on build when removing html directory

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1310]
**Reported by saldsl on 22 Mar 44144583 08:25 UTC**
On Fedora we used to remove the /html directory from build sources, since we don't need it (we use --disable-server directive in ./configure parameters).
Since 7.2 branch the html directory seems to be required, because even using --disable-server the ./configure script fails if removing that directory.

Shouldn't /html directory only be needed when building server component of boinc? (documentation says that)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1339

**Comment by ChristianBeer** [comment]
The /html directory contains a makefile for building a boinc-server-maker package and is required even if `--disable-server` is specified because `configure.ac` is not intelligent enough to not create a makefile there. I don't see a reason to delete /html from build sources. If one wants to do that it's also easy to patch `configure.ac` and remove the `html/Makefile` line.
