### ISSUE TITLE
Should switch from md5sum to sha256sum

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1346]
**Reported by bryanquigley on 1 Oct 45020795 01:00 UTC**
md5sum isn't secure anymore (https://en.wikipedia.org/wiki/MD5#Collision_vulnerabilities)

The protocol should be extended to support sha256 at least.  

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1375

**Comment by romw** [comment]
**Commented by Nicolas on 6 Mar 45020815 16:18 UTC**
What is the attack scenario where a collision attack would break BOINC?

I think you need a preimage attack (which is still impractical even for MD5), not a collision attack.

**Comment by romw** [comment]
**Commented by bryanquigley on 10 Jul 45020848 06:37 UTC**
I don't believe there is a practical attack right now just if the md5sum is correct (over HTTPS let's say) and we're just attacking using the data downloaded file.  Just best practice and it wouldn't hurt to have clients already support it when m5sum is broken worse.

The worst you might be able to do is try to brute force an app to crash and hope it breaks confinement and causes random damage.  You couldn't inject meaningful code (my understanding anyway).

**Comment by grctest** [comment]
I posted this in the [boinc_dev mailing list](http://lists.ssl.berkeley.edu/pipermail/boinc_dev/2016-September/022249.html) (Worth reading the email chain) and in my [boinc_project mailing list thread](http://lists.ssl.berkeley.edu/mailman/private/boinc_projects/2016-September/011834.html) a couple days ago but felt that this GitHub issue is relevant & I feel that this is a massive security concern which warrants discussion.

----

**Topic of discussion: The current BOINC project user password hashing process!**

Upon creating an account, the user's password is hashed as an md5 & salted with their email address: 
https://github.com/BOINC/boinc/blob/master/html/user/create_account_action.php#L107

If a BOINC server was fully compromised, the attacker would have access to all user's email addresses in the SQL table (entirely negating the salt's effectiveness) leaving the password only protected by an md5 hash.

I looked up whether or not an md5 password hash is sufficient protection, and [the overwhelming response was a resounding **no**](https://security.stackexchange.com/questions/19906/is-md5-considered-insecure ).

Quote from the above thread:
> Using salted md5 for passwords is a bad idea. Not because of MD5's cryptographic weaknesses, but because it's fast. This means that an attacker can try billions <http://hashcat.net/oclhashcat-plus/>of candidate passwords per second on a single GPU.

If an attacker has a few graphics cards and a database dump of the password hash + email fields then they could potentially figure out the password behind the md5 via brute force. With the state of password reuse these days, that could have dire consequences (all other BOINC projects potentially compromised if they use boinstats or even worse their accounts elsewhere such as banking could be at risk).

In PHP v5.5 they introduced simple password hashing functionality ([password_hash()](https://secure.php.net/manual/en/function.password-hash.php), [password_verify()](https://secure.php.net/manual/en/function.password-verify.php), etc) which implements [bcrypt](https://en.wikipedia.org/wiki/Bcrypt) which is **significantly** more secure than an md5 hashing process & it wouldn't be adding crazy amounts of new code nor external libraries to the web server.

https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016 (see the PHP section, pretty simple!)

https://stackoverflow.com/questions/4795385/how-do-you-use-bcrypt-for-hashing-passwords-in-php

I realise that switching to a different password hashing mechanism for an existing BOINC account wouldn't be possible without resetting the entire user base's passwords via email (which would be a nightmare), but for a new BOINC project would it not be advisable to switch to using a more secure password hashing process such as Bcrypt or PBKDF2 for password hashing?

I've been informed (in the boinc_dev mailing list) that the BOINC desktop client hashes the password before attempting to authenticate with the web server - that would mean that if I was to upgrade to bcrypt from md5 then I would break login/register compatability?

I also realise that switching to a different password hashing mechanism for an existing BOINC project would be quite difficult - the worst case scenario would be resetting the entire user base's password to force an upgrade to the latest version. Instead of resetting passwords en masse, perhaps we could have a migration phase? User logs into the website -> compares to old password hash, calculates new bcrypt password hash from password provided on login, flip a boolean field stating the user has upgraded to the new password hash mechanism and perhaps empty the old password hash (fully migrated to the new password hash mechanism at this point). 

If we were to [migrate from PHP v5.6 to v7.0+](ttps://secure.php.net/manual/en/migration70.php) in the future (would it pose a significant challenge to migrate?), we could potentially switch to [Argon2i](https://password-hashing.net/) instead of bcrypt for an even stronger hashing algorithm.

Best regards,
CM :)

**Comment by lfield** [comment]
Is this really an issue?

**Comment by marius311** [comment]
If this this refers to password hashing, it was fixed by https://github.com/BOINC/boinc/pull/2401. If not, lets close unless someone gives further information, although we can certainly reopen.
