### ISSUE TITLE
BOINC Android out of date?

### ISSUE THREAD

**Issue by jdheeter** [BOINC/boinc#1439]
When I compile the BOINC android code it will crash on every device I have tested. The app in the play store seems to work great, does anyone know why this open source code is out of date. Who should I contact to get the latest code?

**Comment by funkydude** [comment]
Bump. Of greater concern to me is the outdated OpenSSL (1.0.1j, 8 versions out of date, 1¼ years) and libcurl (7.39, 10 versions out of date, 1½ years)

cc: @romw @davidpanderson

**Comment by SETIguy** [comment]
Bleeding edge isn't always better.  Redhat Enterprise Linux 6 is still at
openssl 1.0.1e (although with a heartbleed patch).  It's as likely that one
of the 8 new versions introduced a security hole as it is to have fixed one.

CURL, on the other hand is much more holey than openssl.  In fact, by
number of reported vulnerabilities, we should all be using CURL 6.0.  CURL
7.39 has 9 known vulnerabilities and about 11 vulnerabilities that haven't
been found yet, going by the statistics of prior versions.  By the same
measure, the most recent version of CURL has no known vulnerabilities and
20 that haven't been found yet.

But definitely, if you can find (or are) an android developer, feel free to
submit a build that works on the full range of android operating systems.
Having built SETI@home, I can assure you its not as easy as it sounds.

**Comment by funkydude** [comment]
@SETIguy sorry but you seem to have a fundamental misunderstanding of how security works.

>Bleeding edge isn't always better.

I'm not asking for bleeding edge, I'm asking for the latest stable versions. In the case of OpenSSL, bleeding edge would be 1.0.2, not 1.0.1 which has a newer stable version available. cURL doesn't follow this form of versioning, all their releases are stable.

>Redhat Enterprise Linux 6 is still at openssl 1.0.1e (although with a heartbleed patch).  It's as likely that one of the 8 new versions introduced a security hole as it is to have fixed one.

I'll try explain how patching on most LTS Linux distros works. The latest version of software (or in this case a library) is always used at the time of the distros release. However, for stability, any security updates after the release of said distro version are patched in manually, like you've correctly noted with heartbleed. The version number is not changed, but all security updates have been merged in. In the case of OpenSSL, this means RHEL is actually using the latest 1.0.1, excluding some extremely minor changes. This is done purely for LTS stability which is the most important thing in an **enterprise environment**, not a home user environment.

If you wish, you can keep track of this [here](https://access.redhat.com/security/security-updates/#/). You are mistaken if you think Red Hat leaves its libraries with known security holes "just in case" a new version introduces another flaw.

>CURL, on the other hand is much more holey than openssl

It really isn't, the complexity difference is astonishing.

>In fact, by number of reported vulnerabilities, we should all be using CURL 6.0.

Number of vulnerabilities isn't an indicator of anything. You need to analyze what these vulnerabilities are. How critical are they, what do they affect, and what do they result in. The Linux kernel has vulnerabilities reported all the time, the count is massive. However, that doesn't make it less secure than Windows.

Also, there's a reason we're not all running Windows XP. Security through obscurity is not security. You seem to be under the impression that older is better/safer. Let me remind you that a lot of the OpenSSL vulnerabilities are being found in old parts of code (see heartbleed).

Thankfully today we have far better tools for recognizing flaws in our code, meaning newer is practically **always** better since these tools are constantly evolving to help us find more problems. A great example of this is Chrome.

>But definitely, if you can find (or are) an android developer, feel free to submit a build that works on the full range of android operating systems. Having built SETI@home, I can assure you its not as easy as it sounds.

Actually, it's really simple to build the exact same version with newer libraries and publish.

**Comment by SETIguy** [comment]
Then do it.

**Comment by romw** [comment]
I’ll see if I can give it a go this week.

In order for it to be published in the playstore, the apk has to be codesigned with a specific code signing key.  I’ve only ever code-signed the apk as prat of the Android app build process.

At this point I’m just hoping the Eclipse environment doesn’t choke on startup.  It has all been deprecated in favor of whatever Google is building these days.

----- Rom

**Comment by funkydude** [comment]
@romw good to hear!

If you're talking about Android Studio, what's wrong with it? It's available on all OS's.

https://developer.android.com/sdk/index.html
https://developer.android.com/tools/studio/index.html

**Comment by romw** [comment]
All the infrastructure for building BOINC on Android is currently geared around Eclipse.

If it stops working, then doing updates stops until somebody can pick-up the flag and convert the project into something Android Studio can use.

----- Rom

**Comment by brevilo** [comment]
Looking into it via #1846.

**Comment by AenBleidd** [comment]
As soon as we have reports from @Ageless93 about successful run of 7.14.1 on Android (with another issues but anyway) I think this issue can be closed.

**Comment by davidpanderson** [comment]
7.14.1 is working on my Android 7.1.1 phone.

**Comment by AenBleidd** [comment]
Closing this as not an issue anymore
