### ISSUE TITLE
XML team exports contain mangled non-ASCII characters

### ISSUE THREAD

**Issue by vorot93** [BOINC/boinc#1503]
Current XML parsing, namely XML exports, uses iso-8859-1. Since UTF-8 is used for team information in BOINC projects, any non-ASCII characters become mojibake.

On a side note: switching to libxml2 would remove any XML problems once and for all including this one.

**Comment by ChristianBeer** [comment]
Did you try to set the charset of the mysql server connection to UTF8? It's also possible that the content in the DB is UTF-8 but MySQL thinks it is iso-8859-1.
I remember struggling with this some time ago and fixing some bugs in the BOINC wide team mechanism. It's possible that what you see in your team export is a remnant of this problem. You should check the import_teams script if it uses the correct charset.

**Comment by ChristianBeer** [comment]
Rereading this after a year begs the question which team exports you mean. The stats export or the BOINC wide team exports that you import at the project level. Can you provide an example?

**Comment by Ageless93** [comment]
Is this still an issue?

**Comment by AenBleidd** [comment]
Up

**Comment by tomasbrod** [comment]
The issue is caused by this line: [db_dump.cpp#L366](https://github.com/BOINC/boinc/blob/3d9538ca78a77c1866ed12b7698e179cb62a166b/sched/db_dump.cpp#L366). The encoding is set to iso-8859-1 without actually writing that file in that encoding. Quick fix is to change it to utf-8, as most servers in 2019 operate in utf-8. More permanent solution is to detect the encoding from mysql or  system locale.
