### ISSUE TITLE
BOINC Manager interferes with Mac network printing

### ISSUE THREAD

**Issue by jonkreisler** [BOINC/boinc#1533]
BOINC Manager Mac v7.6.22, SETI@Home Mac v8 8.03, MAC OS X 10.11.5
Printing to EPSON ET-2550 via WI-FI
When tasks are running under BOINC Manager, anything attempting to print is stuck in "searching for printer". Suspending running projects in BOINC Manager allows printing immediately. Not suspending prevents printing completely.

**Comment by ChristianBeer** [comment]
If suspending projects fixes the Printer issue than the issue is with the project not with the BOINC Manager. Did you test this with another project running and Seti@home suspended? The only connection I can think of is RAM usage. Maybe the printer driver waits to get some RAM but Seti@home has all reserved which gets freed up by the suspend (if you have "Leave application in memory" disabled).

**Comment by Ageless93** [comment]
Calculations done on a GPU (AMD, Nvidia or Intel) will also affect the use
of the computer, because it can slow everything down.
The default setting for use of the GPU is 'use when the computer is NOT in
use'. Many people override this and then later find it does slow down their
system, but have forgotten they allowed BOINC to do this.


-- Jord van der Elst.

**Comment by ChristianBeer** [comment]
If this is still an issue please reopen. I still can't think of a connection between printing and BOINC.
