### ISSUE TITLE
Stops computing

### ISSUE THREAD

**Issue by Neutron167** [BOINC/boinc#1540]
For some reason, I'll be running a project and then it'll get to a certain point and just stop computing. It says that the tasks are running, but when I check the task manager, the CPU is 0% for the tasks. This sometimes happens after my computer goes into sleep mode. But even after restarting the computer and then restarting BOINC, the problem isn't solved. It just sits there saying it's running when it's clearly not. Just an FYI: the project I'm running is Rosetta@home and I'm using Windows 10 on an HP Laptop with a 4th generation Intel Core i7. I attached a screen shot that might be helpful:
![capture](https://cloud.githubusercontent.com/assets/19202379/15038920/3de93de4-125d-11e6-94c7-77d4c08af4dc.PNG)

**Comment by ChristianBeer** [comment]
Does this also happen with other projects? What's your workaround? Canceling the tasks?

From the perspective of the Client the app is running. If the app is not using any CPU time that is not a problem with BOINC but with the application.

**Comment by mackncheesiest** [comment]
I have a similar issue that only happens with Rosetta@Home projects (specifically those involving Rosetta Mini 3.73). My other projects (ATLAS@home & World Community Grid) have never had this issue.

**Comment by mackncheesiest** [comment]
More evidence to this being a bug on the Rosetta side (finally captured a similar screenshot):
![image](https://cloud.githubusercontent.com/assets/8922497/16710928/69886308-45f7-11e6-99d3-456aff56b893.png)

As it shows, the Rosetta project has been running for 6+ hours and isn't getting anywhere and the process is basically idling in task manager. It's certainly not due to difference in workload (this WCG project is an estimated 40,000 GFLOPs while the Rosetta one is about 80,000 -- not significant enough for this much of a slowdown). In addition, the "show graphics" GUI is completely nonresponsive whenever I try to load it for Rosetta but not for WCG.

Just to give an overall idea, here's a list of how all my recent Rosetta tasks have gone:
![image](https://cloud.githubusercontent.com/assets/8922497/16710956/af1247d0-45f8-11e6-90a7-c452b6715a1c.png)

At this point, I've removed and readded the Rosetta project in an attempt to see if "cleaning up" the files associated with it helped at all, and it pretty much didn't help at all. All in all, I suspect that this is probably a Rosetta issue and not a BOINC issue, although I don't know enough about the workings of BOINC to make that judgement.

**Comment by ChristianBeer** [comment]
Seems to be project specific. Please reopen if there is new evidence that it is not.
