### ISSUE TITLE
Split repository into separate parts

### ISSUE THREAD

**Issue by vorot93** [BOINC/boinc#1551]
Right now BOINC repository contains all components used by BOINC projects: desktop daemon, project server, Android client and even PHP CMS! This causes headaches for any outsider tinkering with  BOINC because a lot of code is not related to each other.

Therefore it would be extremely sound to move at least PHP and Java parts into their own Git repositories. This will result in both de-spaghettisation of files and extremely concise Git history for each code base.

**Comment by ChristianBeer** [comment]
That is a good idea but difficult to implement. I looked into separating the BOINC high-level components some time ago but couldn't find a tool or a workflow that was simple to use and also error proof. If you have an idea on how to split the repository but still maintain dependencies across those separate repositories I'm all ears.

Just an example what would need to be tracked when we "just" split of the android and HTML part.
The Android toolchain actually builds the client from /client and also uses the libraries and API, so in order to build the android app you need the Android repo and the normal BOINC repo with the correct versions side by side. How should we track this dependency and make sure the Android App is build against the correct Client?
The HTML code depends on the database schema which would not be in the new repository but rather in the BOINC one because it is also used by the server components. You would need to track the version of the HTML files against the version of the Server where the schema is. How would we know which version of the HTML repository is compatible with what version of the server repository?

Splitting the repository into e.g. Lib, Client, Manager, Server, Android, (HTML) has the same problem. You need to keep track of which version of which component is compatible to which version of the other components.

**Comment by davidpanderson** [comment]
Currently the code is divided into directories and subdirectories.  Putting it in different repos wouldn't improve anything, and would be a nuisance.

**Comment by skybon** [comment]
@ChristianBeer The last option is preferable with addition of Git submodules and tying them to specific revisions.

@davidpanderson It is true for someone that has been developing BOINC code for years. However, if you are an outsider then trying to navigate all the dark corners of this repository (and there are plenty of them) is nightmarish.

De-spaghettization is the way unless you would like to keep BOINC project to three active developers.

**Comment by ChristianBeer** [comment]
I looked into git submodules and learned that in order to get the full potential you have to adjust the development workflow to the tool or else you can break things very easily. Here are just three articles that show the problems when using git submodules:
[Why your company shouldn’t use Git submodules](https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/)
[Git: why submodules are evil](http://slopjong.de/2013/06/04/git-why-submodules-are-evil/)
[Git submodules are probably not the answer](http://somethingsinistral.net/blog/git-submodules-are-probably-not-the-answer/)
In general I don't like what can go wrong when making changes in submodules and not committing those changes or that an innocent `git submodule update` can throw away committed changes in a submodule that where not pushed. You always have to remember what command to run before another just to make sure nothing breaks. This is really a nuisance so I throw that idea away.

Another point is that in order to create such submodules one has to untangle all the code in the first place. This can also happen within the current repository and does not necessarily mean to create separate repos for each component. We just need to make sure that each component is bound to it's subdirectory and there is a common directory structure. I didn't look into this in detail yet but I like something like this: [A Simple C++ Project Structure](http://hiltmon.com/blog/2013/07/03/a-simple-c-plus-plus-project-structure/) or [Introduction to CMake by Example](http://derekmolloy.ie/hello-world-introductions-to-cmake/)
I would like to have a structure that makes it clear:

- Here are all the binaries that this component uses/produced that you can use
- Here are all the libraries that this component uses/produced that you can link against
- Here are all the header files that you may need when linking against a library
- Here are all the files needed to test the functionality of the component
- Here are all the files that produce a decent documentation from the code of this component (or contains a version specific documentation already)
- Here is all the sourcecode for this component to create the binaries, libraries and header files in the other directories

This structure should be the same for each component (with exceptions where applicable) so a new developer can more easily navigate around the code and find the relevant pieces of information. Is that also what you want to achieve @skybon?

IMHO: A transition from the current development workflow to something I just described rather than a completely different one with lots of new pitfalls is less of a nuisance.

**Comment by skybon** [comment]
@ChristianBeer Moving each component into its own folder is a good start. But it is a stopgap nevertheless. What about git logs? For example, plying through endless translation and PHP CMS updates brings no joy and obscrures the daemon updates.

**Comment by ChristianBeer** [comment]
To keep the git logs clean is a responsibility of the developer. Atomic commits with module names in the commit message (like we currently do) would make it easier to find commits that belong to a specific component. For the problem with the translations see the discussion in #1571

**Comment by adamradocz** [comment]
The folder structure is hardly understandable to me as well and don't know where to start if I want to contribute. There're a lot of file in the root folder which are don't seem to me relevant any more, like the checkin_notes.

I tried to find a how to guide but I only found the [](https://boinc.berkeley.edu/trac/wiki/SoftwareDevelopment) page.
A simple folder structure like the following, would be very helpful, at least to me:
- Client
     - Base
     - Linux
     - Mac
     - Win
- Manager
     - Base
     - Linux
     - Mac
     - Win
Etc.

**Comment by AenBleidd** [comment]
@adamradocz There is no split by OSs in BOINC. All OS-dependent code is stored inside the source files itself with define guards. Also 'client' sources are located in 'client' folder. 'Manager' sources are located in 'clientgui' folder. And this structure is pretty clear as for me (I am also a contributor not an owner of this project). And it took a couple of hours to understand the structure of the project and start contributing. If you have any further questions (do not know where to task) feel free to contact me directly. I'll try to answer all your questions.

**Comment by adamradocz** [comment]
Thanks very much.

**Comment by vorot93** [comment]
@adamradocz Currently the repository is a heap of junk compacted over 20 years of project's existence. It took me several days and tens of commits just to gracefully extract client code (for Volunode fork).
- Trust me, you will run into abandoned and forgotten code here. IIRC there is even an old student project (!) in this repo.
- You cannot easily split the repository without screwing up release process on proprietary platforms. I did some pkg-config work to interconnect libraries across repos. And succeeded but only because I did not concern myself with Windows or macOS support.

Since current code is unrefactorable anyway (`CLIENT_STATE` ball of mud, anyone?) I doubt that there is much sense in reorganizing the repo. BOINC client should be rewritten from scratch, clean and simple.

**Comment by AenBleidd** [comment]
@vorot93 I propose to close this thread because this conversation is about nothing. You've made a 'modern' fork of non-portable code. It's your choice. Code in this repo just works. Yes, it has issues but rewriting it from scratch will give nothing except of wasted time and a dozen of new issues. Sometimes small changes to legacy code are more effective than the big but unneeded job.
@davidpanderson, @ChristianBeer Please close this thread.

**Comment by vorot93** [comment]
@AenBleidd Whoa, jumping straight to NO U. For the record, you did troll me before, for the reasons that escape me (pathological contempt for Russians among 'progressive' Ukrainians?).

Ahem, back to the topic at hand: I agree that this issue has run its course. There is nothing we can do at this point.

**Comment by AenBleidd** [comment]
@vorot93 It's a pity that you decide to include politics here. Science need to be separated from the politics (take a look at the ISS as an example). I've never mixed work and politics/nations/religion. And I do not care what you think about me. But you're wrong in your judgment. If you want we can continue our discussion privately. Good luck.
