### ISSUE TITLE
Android request: suspend when bluetooth active

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1567]
I was wondering whether you would consider adding a feature to a future version of BOINC for Android where it stops processing when paired to a particular Bluetooth device?

I have my phone paired to my car stereo on my journeys and usually am using Google Maps as the same time. Unfortunately, if BOINC also is processing, my phone stops getting GPS locations and the only way to recover is to stop one of these CPU intensive applications from processing.

**Comment by AenBleidd** [comment]
Hello David,

I think in this case it is better to use option "Stop processing when screen is on" (I do not remember it's correct name but it's called smth like this).
Also from my POV pf view it will be a good enhancement to stop calculation when some exclusive apps are running.

Best regards,
Vitalii

**Comment by GITNE** [comment]
> I was wondering whether you would consider adding a feature to a future version of BOINC for Android where it stops processing when paired to a particular Bluetooth device?

Yeah, you could do that, and even more. You could even think of an even more complex system of triggers and scheduling conditions when to start or stop BOINC jobs. You could even develop a scripting language or XML Schema to configure this. However, I think this would be the wrong way to go. Running CPU intensive BOINC jobs on mass market mobile devices should be as simple as possible to setup; preferably fully automated. People expect their mobile devices to work **instantly** when on the go. Hence, the default should actually be to stop processing whenever the device is used. And, AFAICT this is also the current default setup.

If you have your device paired to your car stereo and you are simultaneously using Google Maps to navigate then you are de facto **using** your device. As @AenBleidd mentioned, the best setup for you would probably be to stop BOINC processing when your screen is on.

> I have my phone paired to my car stereo on my journeys and usually am using Google Maps as the same time. Unfortunately, if BOINC also is processing, my phone stops getting GPS locations and the only way to recover is to stop one of these CPU intensive applications from processing.

Regardless of the above, this behavior seems strange since BOINC jobs *should* run at the lowest priority. The location service is running at some lower than normal priority but certainly not the lowest priority which could potentially make it "starve". This makes me assume that perhaps in plugged-in or stationary device mode BOINC jobs are actually running at normal instead of lowest priority. This can indeed lead to temporary "starvation" of some background services. But, this is only a guess as to what may be happening.

**Comment by AenBleidd** [comment]
I believe that such use case is very rare and better options are provided above.
I consider not to add such functionality.
If this functionality still required please reopen this ticket,
