### ISSUE TITLE
Use XML objects for MSG_CHANNEL interop

### ISSUE THREAD

**Issue by vorot93** [BOINC/boinc#1617]
XML is extremely verbose in itself, especially for IPC purposes. More than that, the current code uses messages with [multiple XML root nodes](https://github.com/BOINC/boinc/blob/8604e8e0bdda499694e1040d5f0b86fe5f5fe4e1/api/boinc_api.cpp#L886) which is invalid XML and hence unportable.

JSON would make a much better fit for this purpose. MSG_CHANNEL seems relatively isolated within BOINC's codebase and a JSON port would relatively bug-free. A move to jsoncpp's [Json::Value](https://github.com/BOINC/boinc/blob/8604e8e0bdda499694e1040d5f0b86fe5f5fe4e1/api/boinc_api.cpp) as backing buffer storage would trim down the codebase and remove the encoding/parsing middleman.

I am ready to provide patches should the maintainers agree with the transition.

**Comment by davidpanderson** [comment]
Using JSON for GUI RPCs would add complexity (we need to keep the XML write/parse routines for scheduler RPCs) and wouldn't accomplish much; decreasing message size slightly wouldn't change performance significantly.
However, we should definitely have single XML root nodes.  Which messages have multiple root nodes?

**Comment by skybon** [comment]
@davidpanderson Just off the top of my head: [here](https://github.com/BOINC/boinc/blob/8604e8e0bdda499694e1040d5f0b86fe5f5fe4e1/api/boinc_api.cpp#L886).

**Comment by skybon** [comment]
I am currently working on [libxml++](https://developer.gnome.org/libxml++/2.40/) port of BOINC's XML routines. It will feature a revamped MSG_CHANNEL as well.

**Comment by ChristianBeer** [comment]
@skybon I just want to give you a friendly reminder to not mix format changes with functional changes. I just had a quick peak at your libxml++ branch in your personal fork. There is one big commit in there that is labeled "libxml++ port" but the majority of changes seem to be formating related. This is very hard if not impossible to review. In order to make it easier for other developers to understand and review your changes it would be better to differentiate between formating changes and functional changes and do the first before the second and not mix both.

In general I like both ideas very much and would like to help you with both. Can you write up a simple proposal for both with pros and cons of your proposed implementation? Here are some questions that spring to my mind about both projects.

- Like what particular coding conventions should be used and how do they differ from what we [currently have](http://boinc.berkeley.edu/trac/wiki/CodingStyle). How can we change/enforce/test the coding convention and is it possible to override them in special cases where we want a special formating of the source code.
- What kind of XML parser are you proposing to use (DOM or SAX). How to implement this into BOINC (probably with a simple example how to transition from current parser to libxml++). Is it possible to integrate libxml++ gradually or do we have to change all parsing in one go (what are pros and cons of those)

**Comment by skybon** [comment]
@ChristianBeer I am not a big fan of such format/semantics mix either but I never bothered to tinker w/ `.clang-format` for an extended period of time. Since current convention *may be* unenforceable by current beautifiers, the former should be reviewed. It must common enough anyway, maybe even a specific style.

An extended proposal w/ regards to XML is coming up.

**Comment by skybon** [comment]
@ChristianBeer Take a look at #1633. This bug has it as a prerequisite now.
