### ISSUE TITLE
Introduce .clang-format

### ISSUE THREAD

**Issue by vorot93** [BOINC/boinc#1622]
This will keep code style consistent and shift the burden from programmer to `clang-format`.

**Comment by ChristianBeer** [comment]
A prerequisite would be to compile a list of options to be used in such a file. This requires a consensus among the main BOINC developers on how to format code since the current spec is not detailed enough to do so.
For future reference: I found a nice interactive explanation of most of the options here: https://clangformat.com/

**Comment by davidpanderson** [comment]
The code style doc is here: http://boinc.berkeley.edu/trac/wiki/CodingStyle
Notes:
- this doc describes more than just code formatting
- this doc describes the current code; it's not a proposal for future changes
- The Manager code doesn't conform to the style; that's OK for now.
