### ISSUE TITLE
Boinc client use /home/boinc as BOINCDIR on CentOS 7

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1687]
I have just installed BOINC (compiled from GIT source) on CentOS 7. After checking /var/log/boinc_client.log I found that boinc-client service was using /home/boinc/ instead of /var/lib/boinc/ as a data dir. I had to explicitly execute `cd $BOINCDIR;` when starting boinc binary to make it work as expected.

This is my change to /etc/rc.d/init.d/boinc-client script:
```bash
${RUNUSER} - $BOINCUSER -c "$NOCORE ; cd $BOINCDIR ; $BOINCEXE $BOINCOPTS >>$LOGFILE 2>>$ERRORLOG" 2>/dev/null > /dev/null &
```

**Comment by ChristianBeer** [comment]
This sounds more like an issue with creating the `boinc` user. This user should get `/var/lib/boinc/` as home directory. On Debian where this user is created during package installation the passwd entry is something like this:
`boinc:x:117:124:BOINC core client,,,:/var/lib/boinc-client:/bin/false`
If you compile from source the user is not created. You either created it on your own or a previous package installation did that for you. If it is the later you should contact the package maintainer to fix it.

**Comment by sirzooro** [comment]
I created it manually, so it got default home dir /home/boinc/.

**Comment by ChristianBeer** [comment]
The preferred way to install BOINC on Linux is through the packages provided by the distribution which takes care of creating the user account and directories. They usually have their own init scripts and systemd files too. I hesitate to change anything in the script without a better specification. It would be better to improve the install process on Linux to create the `boinc` user and make `BOINCDIR` configurable. I don't think that's worth the effort since it's much easier to install from a software repo (and the version is usually more recent).

**Comment by sirzooro** [comment]
Unfortunately there is no BOINC package for CentOS, so I had to compile it myself. If there would be one ready, I would use it instead.

**Comment by ChristianBeer** [comment]
There are BOINC packages for CentOS. They are in the [EPEL repository](http://fedoraproject.org/wiki/EPEL). For CentOS 7 there is 7.6.22-6 and for CentOS 6 there is 7.2.33-3.

**Comment by sirzooro** [comment]
Thanks, I will use them in the future. I googled for "centos boinc rpm" but pages on top did not mention this, instead I saw compilation guide.
