### ISSUE TITLE
Mac OS System Panic Crash with BOINC 7.6.22 setiahome_8.03_x86_64-apple-darwin

### ISSUE THREAD

**Issue by jdw13** [BOINC/boinc#1727]
Latest Sierra
I have CUDA Driver Version 8.0.53 on iMac and current thread reported last setiahome_8.11.
This has happened three times in last few weeks, and have been running for two years without crash.
Attach is report seen when return to computer and login.
[SETIAHOME CRASH.txt](https://github.com/BOINC/boinc/files/630119/SETIAHOME.CRASH.txt)

**Comment by CharlieFenton** [comment]
Kernel panics like this are usually caused by overheating of the GPU and / or the CPU. According to <https://setiathome.berkeley.edu/apps.php>, version 8.11 is fairly recent (16 November 2016), so it may work some GPUs more intensely than they can tolerate. 

I had a similar problem on my Mac several years ago with a version of S@h. I resolved it at that time by disabling use of the NVIDIA GPU in my "SETI@home preferences for this project." (I also have an AMD GPU which continues to process SETI@home work.) I have not tried re-enabling it since then, though I allow other projects to use the NVIDIA GPU.

I am bringing this to the attention of the project personnel so they can check to see if others have reported this and possibly scale back the GPU usage if it turns out that the issue is widespread.

Cheers,
--Charlie
