### ISSUE TITLE
Android BOINC Client should tell server if host needs PIE or non-PIE apps

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1794]
BOINC server can't easily tell if particular device needs PIE or non-PIE app. [This post at Universe@Home forum](http://universeathome.pl/universe/forum_thread.php?id=203&postid=1940#1940) mentions that server has to learn this by sending out millions of WUs. It would be good if BOINC Client could tell server if it needs PIE or non-PIE apps. I propose to add some new tag (e.g. `<pie>`) with allowed values 0 and 1. When it will be sent from client to server, situation would be clear. When not (for older client versions), server would revert to current way of operation.

**Comment by ChristianBeer** [comment]
You can already target application versions using plan classes to specific operating systems. The [documentation](http://boinc.berkeley.edu/trac/wiki/AppPlanSpec) says there is a min and max android version tag which can be used. I don't know if that works since older Androids only report a kernel version. Einstein@Home uses the os_version field reported by the client to send PIE apps only to capable devices. The current regex is: 

`Android [567N]|Android4\.[1-9]|3\.4\.[0-9]`

**Comment by sirzooro** [comment]
Thanks. It should be enough to define special plan class for PIE app using regex provided by you, and another generic one for Android with non-PIE app. It should be also possible to create negated regex which will match devices with older Android versions and ones without provided version.
