### ISSUE TITLE
BOINC_GAHP should report running jobs. 

### ISSUE THREAD

**Issue by lfield** [BOINC/boinc#1818]
When the remote submission interface reports a job as "In Progress", this information is not being passed back to HTCondor and hence the job is reported to be in the  "idle" state. It should be reported as "running".

**Comment by bema-ligo** [comment]
The problem I see with that description is that a Condor "job" corresponds to a BOINC "workunit", which by itself doesn't have an "in progress" state. Instead it may have many (typically 2) tasks which can have states like "unsent", "in progress" or various types of errors. Which combination of task states should result in a "in progress" state of a workunit?

I would propose that a Condor job should be reported as "idle" when there is at least one "unsent" task for this workunit, else it should be reported as "running" (or, of course, "failed" in case the "workunit" errored out, i.e. has an error mask >0).

**Comment by lfield** [comment]
Hi Bernd,

Ignoring the semantics for now, the remote querying of the job status 
already returns "in progress" and this is what we would like to pass on 
to HTCondor. What this means is a different issue and the change is in a 
different place.

Cheers,

Laurence

**Comment by davidpanderson** [comment]
The BOINC GAHP returns "IN_PROGRESS", "DONE", or "ERROR" for each job.  Perhaps HTCondor isn't interpreting these correctly; e.g. I'm not sure what "idle" means.  Seems like a Condor issue.

**Comment by bema-ligo** [comment]
Then I agree that the GAHP state "IN_PROGRESS" should generally be translated to the Condor state "running", which is a change to the BOINC-GAHP interface module in Condor. For my suggestion, the protocol would need to be extended (e.g. with a fourth state "WAITING" if there are unsent tasks) which then should translate to Condor "idle" (meaning "waiting to run"). But this would require even more changes on both ends.

**Comment by bema-ligo** [comment]
The funny thing is that apparently the Condor end understands "IN_PROGRESS", "DONE", "ERROR" *and* a fourth state "NOT_STARTED": https://github.com/htcondor/htcondor/blob/master/src/condor_gridmanager/boincjob.cpp#L77. The code that refers to that status, however, is commented out and would need to be activated: https://github.com/htcondor/htcondor/blob/master/src/condor_gridmanager/boincjob.cpp#L842

**Comment by bema-ligo** [comment]
It looks like Condor is more or less prepared to handle things better than currently, but does it's best with the information it gets from the BOINC end. So in order to change that, we first need to fix the BOINC side, in particular:

- BOINC GAHP should return "NOT_STARTED" when there are unsent tasks for a job, then activate the code in Condor (as far as I understand it, also the initial Job state should be "NOT_STARTED" in stead of the current "IN_PROGRESS").

- The ugly behavior that (Condor) jobs are put on "hold" in case of *any* error on the BOINC side (which then requires a lot of manual lookup and cleanup) is basically because there is no specified and implemented error handling / cleanup procedure. We should specify (in the protocol #1817?) and implement this. Then we could modify Condor to let the jobs "fail" automatically.

**Comment by lfield** [comment]
This is now working. The issue can be closed.
