### ISSUE TITLE
automatic Release Notes generation

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#1831]
Hi,

I would be grateful if you could make some release notes for the development version as well, not just the stable. It would be easier to identify the potential bugs if we knew what did you changed and what are the new features.

**Comment by ChristianBeer** [comment]
It would be nice if someone could provide a script that extracts the commit messages between two sha1 commits (or tags). The output format should be adjustable to be plain text, bbcode (for posting in forums) or markdown (for posting on github).

**Comment by computersalat** [comment]
Where can I find release notes for 7.8 branch ?
I can only find this:
```
http://boinc.berkeley.edu/wiki/Release_Notes
```
which covers `7.6.33`

**Comment by AenBleidd** [comment]
Is this information not enough https://github.com/BOINC/boinc/milestone/19 ?
It looks more pretty than just copy-pasted commit message.

**Comment by RichardHaselgrove** [comment]
Users expect to be able to see both

* Release Notes - summary of major changes/fixes only
* Change log - detailed, hopefully comprehensive, list of all changes made, ideally including changes made during testing.

I don't think Github is an appropriate tool for non-developers: Milestones are also more often forward-looking planning tools, rather than retrospective archive records.

@computersalat - try https://boinc.berkeley.edu/forum_thread.php?id=11539
