### ISSUE TITLE
Windows 10 Creators Update broke BOINC screen saver

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#1859]
Windows 10 Pro x64 Creators Update v1703 Build 15063.13
BOINC 7.6.33
Videocard drivers up-to-date, or as provided via the Windows update. 

-The BOINC screen saver starts to load, the screen correctly goes black, and "BOINC screensaver loading" is correctly shown in the center.
-A "BOINC" minimized window is then shown.
-If graphics apps are running: a graphics minimized window is also shown (see screenshot, showing World Community Grid Mapping Cancer Markers minimized).
-If graphics apps are not running: a "BOINC screensaver" minimized window is also shown (see screenshot).
-After about 1 second, the black screen and minimized windows disappear, and the user is returned to their desktop.

Screen saver preview doesn't work either. 

-If you have set Boinc processing to start with the screensaver it does not start.
-If you set Boinc processing to start when computer is not in use but do not set the screen saver, it starts OK.
-If say you set Boinc to start after one minute and the screensaver to start after two minutes, when the screensaver fails it stops Boinc, with "user active".

**Comment by ChristianBeer** [comment]
I assigned this the highest priority because it stops BOINC from working.

**Comment by Ageless93** [comment]
I don't agree, because BOINC still works if the user sets the screen saver to None, or uses a different non-BOINC screen saver. In my opinion, the blocker would be if it didn't work under any circumstances.

**Comment by ChristianBeer** [comment]
The blocker is that it stops working without the user noticing and it needs user intervention to work again. Either way, feel free to lower it as I don't think it has an impact on how fast it will be resolved.

**Comment by Ageless93** [comment]
Without anyone knowing what broke and where, I don't think it'll be fixed
quickly either. And I wonder if it's up to BOINC to fix it, because it
worked prior to the Windows update and not afterwards, so why don't we let
Microsoft fix everything they broke? (In a perfect world...)

I'll leave it at blocker, then.


-- Jord van der Elst.

**Comment by Ageless93** [comment]
People reporting similar actions happening to their other applications (see
https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-winapps/apps-close-when-i-open-them/fb96b101-d641-41eb-a17f-9a21746a27a9?tab=question&status=AllReplies)
get advised to go back to the previous installation of Windows!


-- Jord van der Elst.

**Comment by Ferroin** [comment]
That's Microsoft's standard response when an update breaks something that wasn't both written by them and implies support for systems with that update.  In essence, they're telling people to get their software vendors to fix the broken software without actually coming out and saying it.

**Comment by Ageless93** [comment]
Sure it's their standard answer to fix things they don't have an answer to,
however for the vendors to fix a problem that Microsoft brought on? On a
similar tack, when you now install the CU, and you use DTS/Digital Dolby
Live via Realtek HD Audio devices, Creative Soudblasters or Yamaha sound
devices, you can say goodbye to those sounds as this doesn't work. MS had
this problem before in a previous beta build of Windows 10 and it then took
them over 6 months to come with a solution. Now it's broken again, and the
newest drivers from the hardware vendors don't fix it.

One answer I have seen from Microsoft on things like this is: if it doesn't
work, consider upgrading your system (aka buy new). (facepalm)



-- Jord van der Elst.

**Comment by amtronic** [comment]
As the canary that first reported this problem on April 7, I am surprised and disappointed that it has not gotten any traction and been elevated to the level that I believe it should be.

If it does not get corrected soon, BOINC, Seti, and many other projects that use BOINC will begin to rapidly loose supporters. To me, and to many others, BOINC equals Boinc screensaver equals SETI. 
I understand that they are different, but to laypeople they are effectively the same thing. And when the screensaver does not run, people will rapidly stop using it. Millions of cycles will be lost to the BOINC processing collective of projects.

Yes, Microsoft broke it. But expecting Microsoft to fix the problem and issue a new update is not rational or realistic. Microsoft's advice is, if an application no longer works after the Creators Update is installed, to back the update out. Applying the update takes a couple of hours - backing it out and restoring the previous version is fraught with risk and more time consumed. The real world effect is that instead of doing that, people will simply stop using BOINC and go back to some included screensaver that works. It will take a very long time for BOINC and the associated projects to recover those lost users.  I strongly suggest that this problem is resolved ASAP.

Link to initial problem report:
https://setiathome.berkeley.edu/forum_thread.php?id=81274

Respectfully, Amtronic

**Comment by amtronic** [comment]
Microsoft has issued an update to the Creator's Build
https://support.microsoft.com/en-us/help/4016240
(OS Build 15063.250)

The original problem with the BOINC screensaver remains,
the symptoms are the same.  The latest Microsoft Win 10
patch DOES NOT fix the problem.

**Comment by amtronic** [comment]
Microsoft has issued **yet another** update to the Creator's Build
https://support.microsoft.com/en-us/help/4016871/windows-10-update-kb4016871
(OS Build 1703.15063.296)

The original problem with the BOINC screensaver still remains,
the symptoms are the same. The newest Microsoft Win 10
patch DOES NOT fix the problem.

**Comment by hpetite** [comment]
I think the latest Windows 10 Creators fix **KB4020102** resolves this.

Since the Creators upgrade (1703) was installed I was having the same problem as everyone else up until today when I installed this latest fix and now the BOINC screen saver is working again. This fix may have been in the pipeline for a few days but I noticed that it kept failing to install on my system so I did a clean shutdown and reboot which allowed the install to proceed. My apologies for imprecise information but I neglected to write down the fix failure details and error code but it had something to do with some process already in progress, hence my decision to reboot.

With this fix installed, my build level is now 15063.332

**Comment by connylindquist** [comment]
I tested it and it sure starts now but in the screensaver, when I test, it say unspecified error occurred, in the gui.  I´ll check later if its only when I test it from the screensaver menu.

**Comment by amtronic** [comment]
The newest win10 update, 1703.15063.332 **appears to have resolved** the BOINC/SETI screensaver problem.

The newest releases, one for x86(32bit) and one for x64(64bit) are located at
http://www.catalog.update.microsoft.com/Search.aspx?q=KB4020102
Please insure you choose the correct version for your system.

As per the usual SOP a couple of reboots are required to get all the pieces in place.  I would also suggest 
that you insure you have the latest video drivers from your respective brand vendors as that seems to
be a common problem cause for other issues.

**Comment by amtronic** [comment]
Thanks for the update, I gave it a try and it does appear to have fixed the problem!  Thank you!!

Test Mode works fine for me, hope you get it resolved.


amtronic1@verizon.net








-----Original Message-----

**Comment by amtronic** [comment]
Thanks for the update, I gave it a try and it does appear to have fixed the problem!  Thank you!!







Atronic1@verizon.net






-----Original Message-----

**Comment by Ageless93** [comment]
Three people tested it, with many more via forums. Closing this as it seems to have been fixed. If a future Windows update breaks it again, we can open it again.

**Comment by amtronic** [comment]
Thanks for all your help and guidance in handling this problem.


W Tice
amtronic1@verizon.net




-----Original Message-----

**Comment by TruboXL** [comment]
Screen saver feature to be deprecated in Fall Creators Update, just to let you guys know...

>Screen saver functionality in Themes
>
>To be disabled in Themes (classified as "Removed" in this table). Screen saver functionality in Group Policies, Control Panel, and Sysprep is now deprecated but continues to be functional. Lockscreen features and policies are preferred.
