### ISSUE TITLE
Cannot select text in task property window

### ISSUE THREAD

**Issue by Germano0** [BOINC/boinc#1935]
In BOINC Manager 7.6.22 Linux, it is not possible to select text in working unit property/details window

**Comment by ChristianBeer** [comment]
I'm not sure what you mean. I guess you want to copy the information shown in the task properties window to somewhere else and because you can't select the textboxes this is only possible via a screenprint at the moment. If this is th correct interpretation I'm going to file this as a feature request, if not please elaborate.

**Comment by Germano0** [comment]
zomg I don't know what I had in my mind that day. I meant teXt not teSt. I am going to edit the first message

**Comment by AenBleidd** [comment]
I looked into this and can tell that this is not trivial task.
Maybe we can make 'Copy' button that will copy all text in this window as a workaround?
Will this be acceptable?

**Comment by Germano0** [comment]
Speaking about my needs, I can say that it is acceptable to have a copy button that copy all text in the window

**Comment by ChristianBeer** [comment]
I renamed the title to the actual name. A workunit is a name for something on the server. A Client/Manager will only get tasks which are slightly different things conceptually.

**Comment by AenBleidd** [comment]
@ChristianBeer So, is my solution is ok? If yes - I can implement this in two days. If no - I'll try to find another way to make text selectable.

**Comment by ChristianBeer** [comment]
This is not an urgent issue as we are not able to ship it (no new release in sight). Better to find a solution that makes the textfields selectable by the user. If this is not possible we could still go with the copy button which to me does not seem to be trivial as you need to anticipate additions to this dialog in the future. So ideally it should automatically gather the data displayed and "export" as simple text into the clipboard.

**Comment by AenBleidd** [comment]
All text fields are added to the container so the faster way with button solution is go through all text fields and copy them as simple text into the clipboard.
To make static text fields selectable is hard because:
1 - static text control does not accept user interaction (select/copy...)
2 - It is not easy to use another control and keep current alignment (actually wxtextctrl doesn't have 'autosize' command). I'll try to play with this on weekend, maybe I'll find some solution.

**Comment by AenBleidd** [comment]
Results:
1 - static text control does not accept user interaction (select/copy...)
2 - wxTextCtrl cannot be used to display all information in one control because there is no possibility to use different text styles (e.g. bold and normal). wxTE_RICH & wxTE_RICH2 flags are supported in Win32 only.
3 - wxRichTextCtrl looks better but I found no possibilities to enable horizontal scrolling (without this text will be wrapped to the next line that is not good because of 2 shown text columns: wrapped text from second column is shown on the next line in the first column).
4 - using wxRichTextTable in wxRichTextCtrl makes the window totally slow: it takes up to 30 seconds to open a window with data and has very bad performance during redraw. I found no possibilities to speed it up.

So as for now I see only one way: to add 'Copy' button which will copy all data from this window (this can be not suitable when user will want to copy only one field).

Any suggestions?

**Comment by Overtonesinger** [comment]
I agree with the Copy button, for now.

(Soon, the whole GUI will need a complete re-write to other lib/api, which will solve this forever and for good 😉 )


Odesláno z aplikace Pošta pro Windows 10

Od: Vitalii Koshura
Odesláno:pondělí 19. června 2017 4:01
Komu: BOINC/boinc
Kopie: Subscribed
Předmět: Re: [BOINC/boinc] Cannot select text in task property window (#1935)

Results:
1 - static text control does not accept user interaction (select/copy...)
2 - wxTextCtrl cannot be used to display all information in one control because there is no possibility to use different text styles (e.g. bold and normal). wxTE_RICH & wxTE_RICH2 flags are supported in Win32 only.
3 - wxRichTextCtrl looks better but I found no possibilities to enable horizontal scrolling (without this text will be wrapped to the next line that is not good because of 2 shown text columns: wrapped text from second column is shown on the next line in the first column).
4 - using wxRichTextTable in wxRichTextCtrl makes the window totally slow: it takes up to 30 seconds to open a window with data and has very bad performance during redraw. I found no possibilities to speed it up.
So as for now I see only one way: to add 'Copy' button which will copy all data from this window (this can be not suitable when user will want to copy only one field).
Any suggestions?

**Comment by AenBleidd** [comment]
I got a fresh idea to use wxHtmlWindow. Will try on this week.

**Comment by AenBleidd** [comment]
Fixed in #1950

**Comment by JuhaSointusalo** [comment]
Not quite sure where to discuss a PR that's already merged.

I'd like it better if the properties dialog looked more like a normal dialog, font and colours at least. And I dislike center-aligned cells, they always look bad to me, top-align please.

I think I'd like it better if word wrapping was prevented for labels, if that's possible. Maybe the dialog should be a bit larger too? It almost always has scroll bars.

master, 20d07be2:

![image](https://user-images.githubusercontent.com/15806192/28942621-b8a77d6c-78a4-11e7-8f19-13762cba4c22.png)

7.8.0:

![image](https://user-images.githubusercontent.com/15806192/28942663-e3d35088-78a4-11e7-802c-e4b23c68ab8c.png)

**Comment by AenBleidd** [comment]
Ok. I'll fix this in a couple of days.

Best regards,
Vitalii Koshura

2017-08-03 23:59 GMT+03:00 Juha Sointusalo <notifications@github.com>:

**Comment by AenBleidd** [comment]
@JuhaSointusalo Fixes are made in #2013. Could you please test it?

**Comment by RichardHaselgrove** [comment]
Working in v7.9.0 - test in v7.10

**Comment by JuhaSointusalo** [comment]
Closing. Implemented in PR #1950, PR #2013, PR #2030, commit 07e55b93 and PR #2190.
