### ISSUE TITLE
add Linux libc version info to host.os_version field

### ISSUE THREAD

**Issue by ChristianBeer** [BOINC/boinc#2064]
It's very helpful to know the libc version of hosts attached to a project so scientists can create compatible applications or target applications to older operating systems. Currently only the kernel version is stored in `host.os_version` e.g. `2.6.32-573.18.1.el6.x86_64` and starting with 7.8 the OS name and version too e.g.: `Debian GNU/Linux 9.1 (stretch) [4.9.0-3-amd64]`. From this you can not easily extract the libc version available on the host.

I propose to add code to the client (in [hostinfo_unix.cpp:HOST_INFO::get_os_info()](https://github.com/BOINC/boinc/blob/master/client/hostinfo_unix.cpp#L1589)) that detects the version of libc, reports it to the project server and stored it in the DB as part of `host.os_version`.

Detecting libc version on Linux based systems (mainly glibc based ones) can be done in several ways as shown on this StackExchange [question](https://unix.stackexchange.com/questions/120380/what-c-library-version-does-my-system-use). It all comes down to parsing version information either directly from `libc.so` or `ldd --version`. Unfortunately this does not work for BSD distributions (ldd doesn't support --version and libc.so is not executable). I found it easier to use `ldd --version` on Debian and RedHat based systems as the examples I gathered where simple and stable enough for this purpose. 
Example output from `PATH=/usr/bin:/bin:/usr/local/bin /usr/bin/ldd --version 2>&1` is:
Debian Stretch: `ldd (Debian GLIBC 2.24-11+deb9u1) 2.24`
Ubuntu 12.04LTS: `ldd (Ubuntu EGLIBC 2.15-0ubuntu10.18) 2.15`
Fedora 25: `ldd (GNU libc) 2.24`

I already have code that extracts the two information. The question to me now is what to do with it. Or rather how to add it to the existing `host.os_version` string so it is useful. With useful I mean that this information can be used for example in plan_classes so that certain app_versions can be targeted for specific libc versions or exclude specific libc versions. Another usage scenario is a census of available libc versions in a project to see what the minimum libc version is to use for a science app.

Here are the possibilities I see to add this new information to the existing `host.os_version` information:

1. `Debian GNU/Linux 9.1 (stretch) [4.9.0-3-amd64|libc 2.24]`
2. `Debian GNU/Linux 9.1 (stretch) [4.9.0-3-amd64|libc 2.24 (Debian GLIBC 2.24-11+deb9u1)]`
3. `Debian GNU/Linux 9.1 (stretch) [4.9.0-3-amd64|libc 2.24 (2.24-11+deb9u1)]`

The plan_class `os_version` filter uses a regular expression which just needs to start with `libc ` in order to restrict to certain versions. Using the information directly from DB and piping it through awk/sed is also easily possible to further extract the desired information although the square bracket format is not ideal.

I would like to get comments and thoughts from @BOINC/team-boinc and @BOINC/contributors  as well as a vote from @BOINC/committer on how to proceed.

**Comment by brevilo** [comment]
This is obviously a good idea. Of the proposed three versions I do prefer the second as it provides the most details.

**Comment by JuhaSointusalo** [comment]
Considering that there are other libc implementations besides just glibc and these others may at some point have version numbers that overlap glibc's version numbers I think it would be better to have the libc's name included with its version number.

Could you check with the oldest distro that is still supported (RHEL?) that the output of ldd has not changed? Or if you can find a non-glibc distro what its ldd outputs?

BSDs not supporting `ldd --version` is probably not a big issue. With only three or so BSDs it's easy to know what they can run vs. Linux and a couple hundred distros.

**Comment by ChristianBeer** [comment]
I just checked with CentOS 6.9 which has the same output as Fedora 25 (although an older version). I only checked freeBSD and openBSD as non-glibc distributions. Other major distributions all use glibc. From what I read it seems that distributions used on embedded systems sometimes use a smaller libc but I didn't look for a distribution for which a BOINC package is also available. The only embedded system BOINC currently supports is the Raspberry Pi and others which all run glibc based Linux distributions.

I agree with Juha and Oliver and I also prefer option 2 because it provides the most details (including the name).

**Comment by TheAspens** [comment]
Is there anything correspondingly that we would want to do for Mac, Windows and Android?

**Comment by JuhaSointusalo** [comment]
If you use Visual Studio and link your programs dynamically the programs
will depend msvcr<version>.dll and msvcp<version>.dll, or starting with
VS2015, ucrtbase.dll, vcruntime<version>.dll and msvcp<version>.dll. UCRT
is part of Windows 10 and available for older Windows' as redist package.
I'm not sure if the other DLLs are part of Windows 10.

A clean install of Windows might have some of the DLLs installed but I
don't think Microsoft guarantees that.

So instead of listing one version number you'd have to enumerate the
available versions.

MinGW links to msvcrt.dll which is from VC++6 era. Microsoft can't remove
that DLL from Windows without breaking backward compatibility.

**Comment by RichardHaselgrove** [comment]
At the moment, we get round that by distributing msvc?100.dll with the boinc executables, and telling the Windows installer to place them in the BOINC program directory - so they are independently available, and accessible via the default Windows directory search paths. (That's for VS2010 builds, as currently used: for VS2013 builds the distributed files would need to be msvc?120.dll, and upwards as Juha says.)

Other software packages don't redistribute the DLLs individually (although this is perfectly legal): instead they package the required version of the MS VC++ redistributable installer, and invoke it as a secondary process if needed. This would add the DLL suite to the common shared library search path, and (I would like to think - unverified) allow automatic installation of runtime DLL service pack updates via Windows Update - to the common benefit of all.

Instead, by placing static files in our private directory, we probably bypass Microsoft's security update process.

**Comment by ChristianBeer** [comment]
For Windows we already get a lot of details about the OS version (`Microsoft Windows 7 Professional x64 Edition, Service Pack 1, (06.01.7601.00)`) which includes the build number and service pack level. In the past that was enough to identify faulty versions. Using Visual Studio one can set the compatibility level to major versions like "Vista and newer" or "10 and newer". So the compatibility level that Microsoft is using is always the major version and projects can already exclude XP via plan_class if they have an app that is compiled for Vista and newer.

For Android we already get the Android version as well as the kernel version which is also enough to identify problematic versions. The most prominent change here was forcing apps to use PIE-executables since Android 5 for which plan_class solutions already exist. Older Android versions only report a kernel version but that changed with Android 4 I think so that is not a problem either.

For Mac we get a simple version number `Darwin 15.6.0` which is enough since Apple only releases one version and we know the capabilities and limitations.

This only leaves Linux where there is a more heterogeneous environment and we need to know the low level stuff like libc version.

**Comment by AenBleidd** [comment]
Hello @all,

This is some kind of off-topic but from my POV very important thing is
identifying problematic GPUs too.
I'll try to explain what I mean.
In my case I have notebook with GPU AMD Radeon HD 5470. The problem is that
this GPU can't work with double-precision floats so no one application from
the list of interesting projects could be run on my GPU. But the real
problem is that from BOINC POV this GPU is normal and it can download and
run AMD specific applications. Of course, they will fail with error and I
know that I can manually switch off GPU usage for BOINC projects but I want
to say that it can be very helpful option to identify such problematic GPUs.

I don't know whether it is possible to identify this automatically using
some OpenCL checks. It is just my thoughts about this.

What do you think, guys?

Thanks

Best regards,
Vitalii Koshura

2017-08-25 13:28 GMT+03:00 Christian Beer <notifications@github.com>:

**Comment by RichardHaselgrove** [comment]
The double-precision problem (and similar differences between GPUs of different generations) can also become important when multiple, disparate, GPUs are fitted in the same host. A user might wish to allow their DP GPU to help a particular project. They can achieve that by manually excluding the SP GPU from the project using an entry in cc_config.xml, but it's non-trivial for the average user.

They would need to add <use_all_gpus> to cc_config to use the SP GPU in a different, compatible, project, of course, but in my experience the advice to add <use_all_gpus> on project message boards is rarely accompanied by "(but remember to exclude the SP card from your other DP project)".

In the long term, it would be good to identify the properties of each GPU individually, and pass that information to the servers so that projects can take advantage of it, but that would be a much bigger project than the '1 day' envisaged for this issue. Perhaps BOINC v8?

**Comment by AenBleidd** [comment]
@RichardHaselgrove,

I agree, this is a big task so v8 looks nice.

Thanks

Best regards,
Vitalii Koshura

2017-08-25 14:05 GMT+03:00 RichardHaselgrove <notifications@github.com>:

**Comment by bema-ligo** [comment]
As the title says, this is only meant for Linux. For all other OS we get useful information in the "os_version" that allows to determine whether a given application will run on that machine. For Linux this depends mainly on the libc version that the application has been compiled with vs. the version on the machine. The latter is what so far we don't get any information about, although it would be the most important one.
