### ISSUE TITLE
Fields To Show Task Estimated Completion & Relative To Deadline

### ISSUE THREAD

**Issue by PaulWalkerUK** [BOINC/boinc#2115]
It would be really useful if two extra columns were available on the Advanced View --> Tasks pane (I'm using the Windows BOINC Manager 7.8.2). These would help visualising if a task was likely to be completed before it's deadline and help users micro-manage priorities to ensure they are, if and as required. It would be especially useful for the larger, longer-running tasks.

# New Field 1: Estimated Completion

This would show the estimated date/time that a task will complete. It would be calculated as `current_datetime + remaining_estimated`

# New Field 2: Relative To Deadline

I'm not sure what the best name for this would be, but basically it would show the difference (in `days hours:minutes:seconds`) between the deadline and the "estimated completion" (as described above). This would be shown as negative if the task is expected to complete early or positive if the task is expected to overrun. This column should be sortable so you can see the tasks most likely to overrun at the top of the list and the tasks with most time in hand at the bottom - or vice-versa.

## Example

If Task1 is expected to complete on 15th September at 13:00 and the deadline is 17th September at 14:30, then this field would show something like `-2d 01:30:00` (i.e. it is expected to complete 2 days 1 hour and 30 minutes before the deadline - plenty of time to spare, no problem).

If Task2 was expected to complete at on 19th September at 14:00 but the deadline was the same day at 10:00, then it would show something like `+ 04:00:00` (i.e. it's expected to overrun by 4 hours - might want to take action to try to get this to complete before the deadline).

These new fields could look something like this (based on current time being 12/09/2017 23:00 and ignoring most existing fields for the sake of the example):

Task | Deadline | Remaining | Estimated Completion | Relative To Deadline
-----|----------|------------|------------------------|----------------------
Task1 | 17/09/2017 14:30:00 | 2d 14:00:00 | 15/09/2017 13:00:00 | -2d 01:30:00
Task2 | 19/09/2017 10:00:00 | 6d 15:00:00 | 19/09/2017 14:00:00 | +0d 04:00:00

**Comment by ethanteng** [comment]
Just double checking this is something we want? I'm new to the project and would like to pick this up as my first contribution. And it's a feature request I've personally wanted :)

**Comment by AenBleidd** [comment]
@ethanteng, yes, it looks like an interesting feature. Feel free to go ahead and implement it.
Thank you for your interest

**Comment by ethanteng** [comment]
I've made good progress on this. I've implemented the first part and added the "Estimated Completion" column. (See the screenshot below.)

![Screen Shot 2019-12-12 at 3 24 29 PM](https://user-images.githubusercontent.com/2678675/70757232-a63f0500-1cf3-11ea-8a83-154885f64def.png)

But, as I'm thinking through the rest of this feature request, I wonder if the second part -- i.e. adding another column for "relative to deadline" -- is maybe over-engineering the solution? In my opinion, seeing the "Estimated Completion" next to "Deadline" is enough for a user to visually assess which task(s) likely won't complete by the deadline. I think adding another column for "Relative to Deadline" isn't really necessary.

Thoughts? @PaulWalkerUK @AenBleidd

**Comment by PaulWalkerUK** [comment]
I don’t mind either way. It was just a suggestion, I’m happy with whatever anyone decides

**Comment by AenBleidd** [comment]
@Vulpine05, assuming your current experience, maybe this is a next good ticket for you? It has a PR open, but it's not correct (you can read my comments) and I believe you're the best candidate to make this implementation in a proper way.

**Comment by Vulpine05** [comment]
@AenBleidd sure, I can take a look.  I have read through the comments and PR, and it appears there still is some debate about what this is supposed to do or not do.  Specifically, the estimated completion column.  I'll report back after I've had time to do some testing and thinking.

**Comment by Vulpine05** [comment]
I think @davidpanderson is right in his argument [here](https://github.com/BOINC/boinc/pull/3403#issuecomment-570831940), I don't know if this is a good feature to implement, at least as a new column in the task tab.  There are a few things that concern me:

1. With this extra column, each active task is going to have its estimated completion (EC) updated once a second.  This information is going to be a constantly updating, either an increase or decrease in time.  Plus, the information in this column (at least for active tasks) will appear/disappear as computation is suspended and resumed.  I'm concerned this may be information overload.  Too much information changing, or disappearing, or reappearing, without much significance from second to second.  Currently, the only information actively changing on this tab are the time computed, remaining time, % complete, and the status of the task.  All of those items are helpful for most users.  I think this new column would be helpful for only a handful of users and confusing or annoying to the rest.
2. Although probably small, this is taking computing time that could be used for other purposes.
3. Some projects have an remaining time that varies. For example, Einstein's remaining computing time has (or still does) vary a bit if you are running different applications on the project.  Additionally, GPUGrid's Python app has computing times close to a year.  I've canceled tasks before thinking I was not going to complete them, but in fact I do get them done by the deadline.  If a user is not well aware of how the tasks work on their computer, they may see the estimated completion time and prematurely cancel a task.

Perhaps we need to think about what we are asking for here, and is there a better way to serve it.  To @RichardHaselgrove 's point in a related issue [here](https://github.com/BOINC/boinc/issues/2957#issuecomment-566016337), this is going to be used by the active, involved participants that may micromanage.  My guess is that these users also are familiar with the projects that they are signed up to, and know which ones have unique subtleties such as Einstein@home.

What if instead we provide a tool to check for tasks that may run past their deadline?  I would suggest this is placed under the Tools menu.  That way it is not in direct view of every user, but the active/involved user would know where to run and use it.  This could also be ran from boinccmd.  It could create a new window, check all tasks (maybe just active, but probably all tasks) to see how it compares to their deadline.  That window could be a list of the tasks that won't make the deadline.  What the user decides to do with that information is up to them.  I'm not sure how I feel about adding additional functionality to allow the user to abort/suspend these potentially overdue tasks, but we could include that as well.

Thoughts?

**Comment by CharlieFenton** [comment]
While I added code several years ago to allow a user to hide or show columns, and on MS Windows to rearrange them, there are already too many columns to display on most monitors.

> I think this new column would be helpful for only a handful of users and confusing or annoying to the rest.

I think this is an extremely important point that gets overlooked far too often. The BOINC power users represent a tiny percentage of the BOINC community, or perhaps more accurately, the size of the BOINC community we wish to have. The main goal of BOINC is to attract ordinary, everyday "mom and pop" users, who are most likely to use a simple "set and forget" app that takes minimal effort to understand. 

I have long been concerned that all the attention we have expended catering to the handful of power users has made BOINC so complex that it frustrates and scares off too many potential users. While the Simple View is an attempt to address that, for many potential users it is either not powerful enough or still too complicated. For most to whom Simple View is inadequate, the leap to Advanced View is far too great.

BOINC desperately needs to attract more users. Repeatedly adding this sort of fine tuning counteracts that and so is, IMO, counterproductive. We should be simplifying BOINC by reducing options (or at least removing them from the GUI) rather than adding to the GUI. 

By _removing them from the GUI_ I mean require editing a configuration file to enable more advanced options.

**Comment by AenBleidd** [comment]
@CharlieFenton, this is not related to this particular PR but I need to mention this.

> We should be simplifying BOINC by reducing options (or at least removing them from the GUI) rather than adding to the GUI.

I don't agree. In general yes, we should make UI as simple as possible but sometimes some setting should be changed and when it's not available on UI - it's extremely hard to explain to "mom and pop" users how to edit properly configuration file (that has an XML format and is not easy to use).
I'd think about another solution: add all options to UI but make them visible when user enabled some 'Advanced' or 'Expert' mode.
Not sure we have resources for this now, but I believe it would be nice to discuss this one day in a separate ticket.

**Comment by CharlieFenton** [comment]
@AenBleidd I think your suggestion about having an "advanced" or "expert" mode is fine, though we already call the detailed GUI "Advanced View." I have also long thought that we need some view between Simple and Advanced, but as you say we don't have the resources to do that. 

> it's extremely hard to explain to "mom and pop" users how to edit properly configuration file (that has an XML format and is not easy to use).

I'm sorry I was not clear. I was referring to only those very advanced and rarely used settings which are of  interest only to BOINC power users. BOINC power users will know how to add or change options in XML files; they already must do that in _cc_config.xml_ for some options. "Mom and pop" users don't care about estimated completion time relative to deadline, or about many features which have been requested by other power users.

I was also thinking about adding an "advanced" or "expert" item to the  help menu in Advanced View, which would open a web page explaining the expert options that could be enabled by editing a configuration file. This would be a new configuration file specifically for the Manager, since cc_config.xml affects only the client. (We originally referred to the client as the "core client", which is where the "cc" in _cc-config,xml_ came from.)

**Comment by davidpanderson** [comment]
I think the GUI (both views) should have 3 options,
Low power / Standard / Maximum computing
(like the Science United web interface)
with an Advanced button showing the complete set
(with tooltips explaining each one)

**Comment by Vulpine05** [comment]
Sorry, I didn't mean to get this off topic for this issue!  Considering what has been said, I could add this feature as @AenBleidd has suggested (keeping the column un-selected).  It wouldn't take much to tidy up #3403.  A separate window as I suggested yesterday would take a bit more effort on my part, and to @CharlieFenton 's point, there are other fixes that I can focus on that affect more users.

**Comment by AenBleidd** [comment]
One more comment about this. If show this column, then update it for running tasks only, otherwise it will anyway show not relevant information

**Comment by Vulpine05** [comment]
The PR does that already, but the field doesn't refresh.  If you move the mouse over the task it will update, and in your example turn to '---'.  To your point, I can fix it to display properly.
