### ISSUE TITLE
Misleading "Another instance of BOINC is running" with wrong ownership of boinc dir

### ISSUE THREAD

**Issue by eMPee584** [BOINC/boinc#2156]
Just resolved this by ~~picking the boinc pid from `watch -d -n 0.2 systemctl status boinc-client.service`,~~ tracing the process within the `        retval = wait_client_mutex(".", 10);` 10 second timeout with `strace -fe trace=file -p $(pidof boinc)` and that gave me the real issue:

```
command: "strace -fe trace=file -p 19601" (strace is /usr/bin/strace)
@dir: /home/empee584 @time: Thu  5 Oct 09:27:53 CEST 2017

strace: Process 19601 attached
open("./lockfile", O_WRONLY|O_CREAT, 0664) = -1 EACCES (Permission denied)
open("./lockfile", O_WRONLY|O_CREAT, 0664) = -1 EACCES (Permission denied)
open("./lockfile", O_WRONLY|O_CREAT, 0664) = -1 EACCES (Permission denied)
open("./lockfile", O_WRONLY|O_CREAT, 0664) = -1 EACCES (Permission denied)
open("./lockfile", O_WRONLY|O_CREAT, 0664) = -1 EACCES (Permission denied)
open("./lockfile", O_WRONLY|O_CREAT, 0664) = -1 EACCES (Permission denied)
open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 3
+++ exited with 108 +++

"strace -fe trace=file -p 19601" exited after 6 seconds
exit status 0 at Thu  5 Oct 09:27:59 CEST 2017

```
which was caused by the fact that my older version of ranger doesn't transfer file permissions when copying a dir (ranger/ranger#734).
So the presented error message is wrong and totally misleading. Obviously, this is a corner case, but still.  :smile:

**Comment by makeasnek** [comment]
A bounty has been started by the [SCI](https://thesciencecommons.org) to fix this issue on [BountySource](https://app.bountysource.com/issues/119785136-bounty-fix-confusing-warning-to-users-when-directory-permissions-are-incorrect-linux). It is currently at $25 USD and will continue to increase until the issue has been fixed. You can contribute to this bounty directly if this issue is important to you.
