### ISSUE TITLE
"--allow_remote_gui_rpc" doesn't seem to work

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2282]
Hi,

If I start the boinc with the --allow_remote_gui_rpc parameter, than I can connect to it remotely, but if I put it in the remote_hosts.cfg file, I can't.

**Comment by AenBleidd** [comment]
It works for me both on linux and raspberry pi. I can double check it in
two weeks cause. I'm on vacation now.

What OS are you use and what version of boinc client?

Best regards,
Vitalii

Sent via Android

31 дек. 2017 г. 10:46 PM пользователь "Adam Radocz" <
notifications@github.com> написал:

Hi,

If I start the boinc with the "--allow_remote_gui_rpc" parameter, than I
can connect to it remotely, but if I put it in the remote_hosts.cfg file, I
can't.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BOINC/boinc/issues/2282>, or mute the thread

**Comment by adamradocz** [comment]
OS: Docker Ubuntu 17.10 image
Version: 7.8.3

**Comment by adamradocz** [comment]
I tried on Windows 10 as well and got the same result. Even if I add specific IP address.
Version: 7.8.3

**Comment by adamradocz** [comment]
Works with specific IP address. But if I put the  "--allow_remote_gui_rpc" in the remote_hosts.cfg file, than the client gives this error message:
`02-Jan-2018 18:42:50 [---] Can't resolve hostname in remote_hosts.cfg: --allow_remote_gui_rpc`

**Comment by CharlieFenton** [comment]
I believe you are misunderstanding the use of this flag; _--allow_remote_gui_rpc_ should not be placed in the _remote_hosts.cfg_ file.. According to [http://boinc.berkeley.edu/wiki/Controlling_BOINC_remotely] _--allow_remote_gui_rpc_ is a command line argument to be passed in a call to the BOINC Client to indicate that connections should be accepted from all hosts. Alternately, ta list of specific IP addresses from which to accept connections may be placed in a _remote_hosts.cfg_ file.  
There is also a third way. According to [http://boinc.berkeley.edu/wiki/Client_configuration], you can put `allow_remote_gui_rpc>1</allow_remote_gui_rpc` in the _cc_config.xml_ file to allow GUI RPCs from any remote host.

It is important to read the documentation to ensure you are using an option  correctly before assuming that the option is broken.

**Comment by adamradocz** [comment]
Oh, my bad! I read once more the instruction and you're right. :)
