### ISSUE TITLE
Official Docker BOINC Client image

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2361]
I think an official Docker BOINC Client image would be nice. There are a lot of people with headless NAS servers and Home Media Servers, with Docker installed on.

I created a Docker image with a nice description a couple of months ago, and I would happily transfer the ownership of it.

The repo: [https://github.com/adamradocz/docker-boinc](https://github.com/adamradocz/docker-boinc)

The docker image in the hub: [https://hub.docker.com/r/adamradocz/boinc/](https://hub.docker.com/r/adamradocz/boinc/)

**Comment by marius311** [comment]
Hey @adamradocz that looks really great. One thing you can do now is transfer it to the "boinc" organization on the Docker Hub https://hub.docker.com/r/boinc/ along side the server images. I would rename the image so that we have the three `boinc/server_*` images and `boinc/client`. I just added you to the organization so you should be able to set up the automated build. 

For that matter, it'd be great if I could add another one of the developers too, @TheAspens @davidpanderson want to volunteer to be on there just in case ?

**Comment by adamradocz** [comment]
Shouldn't I transfer the giuthub repo first?

**Comment by marius311** [comment]
Yea, it could save a step I suppose if people agree to move it into the Github BOINC organization (I have no control over that fyi).

**Comment by adamradocz** [comment]
@davidpanderson What do you think?

**Comment by davidpanderson** [comment]
Shouldn't be too hard, worth doing.

**Comment by adamradocz** [comment]
I tried to transfer the ownership but I don't have permission to create a repository in the boinc organization.

**Comment by davidpanderson** [comment]
Should I create one?  What should I call it?

**Comment by adamradocz** [comment]
I suggest docker-boinc or docker-boinc-client.
@marius311 do you have any other suggestion or do you agree with the names?

**Comment by marius311** [comment]
How about `boinc-client-docker` for no good reason except to be consistent with https://github.com/marius311/boinc-server-docker ?

**Comment by davidpanderson** [comment]
I created the repo, and gave both of you write access.

**Comment by adamradocz** [comment]
I uploaded the code and connected the github with the docker hub. I tested the image with my server, and it seems working, so I close this issue.

One more thing. I think the [https://boinc.berkeley.edu/download_all.php](https://boinc.berkeley.edu/download_all.php) page should show the docker version too.
