### ISSUE TITLE
Create a setting to automatically remove expired tasks.

### ISSUE THREAD

**Issue by hintofbasil** [BOINC/boinc#2366]
I started up Boinc for the first time in over a month and was surprised to see that instead of removing my overdue tasks, it started computing them instead.  I believe at lease one of these tasks had not been started but I have no way to prove that.

The tasks are identified as overdue in the logs.

    20-Feb-2018 18:17:47 [Citizen Science Grid] Task exact_genome_1515759602_61_12650_1 is 17.16 days overdue; you may not get credit for it.  Consider aborting it.
    20-Feb-2018 18:17:47 [Citizen Science Grid] Task exact_genome_1515759602_58_12641_1 is 10.69 days overdue; you may not get credit for it.  Consider aborting it.
    20-Feb-2018 18:17:47 [Citizen Science Grid] Task exact_genome_1511526933_31_18545_3 is 9.17 days overdue; you may not get credit for it.  Consider aborting it.
    20-Feb-2018 18:17:47 [Citizen Science Grid] Task exact_genome_1515759602_60_12665_1 is 9.93 days overdue; you may not get credit for it.  Consider aborting it.
    20-Feb-2018 18:17:47 [Collatz Conjecture] Task collatz_sieve_3949741896312092098560_52776558133248_0 is 19.06 days overdue; you may not get credit for it.  Consider aborting it.
    20-Feb-2018 18:17:47 [Einstein@Home] Task LATeah0021F_504.0_173800_0.0_0 is 19.06 days overdue; you may not get credit for it.  Consider aborting it.
    20-Feb-2018 18:17:47 [Collatz Conjecture] Task collatz_sieve_3949741949088650231808_52776558133248_0 is 19.06 days overdue; you may not get credit for it.  Consider aborting it.

It would be good to have a preference which allowed these to automatically be removed.  I would have expected this to be the default behaviour however just the option would be good.  The ability to remove once expired by a set time would be even better.

Examples:

    <max_overdue_hours>1</max_overdue_hours> # -1 for disabled

or

    <remove_expired />

**Comment by chungboom** [comment]
ฉัน ทำอย่างไร







Create your own email signature<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

________________________________
จาก: hintofbasil <notifications@github.com>
ส่ง: 21 กุมภาพันธ์ 2561 1:37
ถึง: BOINC/boinc
สำเนาถึง: Subscribed
ชื่อเรื่อง: [BOINC/boinc] Create a setting to automatically remove expired tasks. (#2366)


I started up Boinc for the first time in over a month and was surprised to see that instead of removing my overdue tasks, it started computing them instead. I believe at lease one of these tasks had not been started but I have no way to prove that.

The tasks are identified as overdue in the logs.

20-Feb-2018 18:17:47 [Citizen Science Grid] Task exact_genome_1515759602_61_12650_1 is 17.16 days overdue; you may not get credit for it.  Consider aborting it.
20-Feb-2018 18:17:47 [Citizen Science Grid] Task exact_genome_1515759602_58_12641_1 is 10.69 days overdue; you may not get credit for it.  Consider aborting it.
20-Feb-2018 18:17:47 [Citizen Science Grid] Task exact_genome_1511526933_31_18545_3 is 9.17 days overdue; you may not get credit for it.  Consider aborting it.
20-Feb-2018 18:17:47 [Citizen Science Grid] Task exact_genome_1515759602_60_12665_1 is 9.93 days overdue; you may not get credit for it.  Consider aborting it.
20-Feb-2018 18:17:47 [Collatz Conjecture] Task collatz_sieve_3949741896312092098560_52776558133248_0 is 19.06 days overdue; you may not get credit for it.  Consider aborting it.
20-Feb-2018 18:17:47 [Einstein@Home] Task LATeah0021F_504.0_173800_0.0_0 is 19.06 days overdue; you may not get credit for it.  Consider aborting it.
20-Feb-2018 18:17:47 [Collatz Conjecture] Task collatz_sieve_3949741949088650231808_52776558133248_0 is 19.06 days overdue; you may not get credit for it.  Consider aborting it.


It would be good to have a preference which allowed these to automatically be removed. I would have expected this to be the default behaviour however just the option would be good. The ability to remove once expired by a set time would be even better.

Examples:

<max_overdue_hours>1</max_overdue_hours> # -1 for disabled


or

<remove_expired />
