### ISSUE TITLE
[Manager] Update the projects' url to https 

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2438]
On the project chooser window some project have http link, but the project has https access, like World Community Grid.

<img width="444" alt="project chooser" src="https://user-images.githubusercontent.com/16503773/38143661-d48dd3e2-3441-11e8-92af-e236b56619f0.PNG">
<img width="258" alt="wcg" src="https://user-images.githubusercontent.com/16503773/38143662-d4abff84-3441-11e8-978a-3b366cb6cd17.PNG">

**Comment by RichardHaselgrove** [comment]
It's important that the 'Project URL' (which is the URL which volunteers use to attach to the project via the project scheduler - not necessarily the same URL as their primary website) is the address which each individual project asks their volunteers to use, for whatever reasoning they choose. But you're right: we should periodically check through the list and make sure we haven't missed an update. That's particularly important in the run-up to a new version release - which just happens to be the case right now. I'll have a look through over the holiday weekend.

Having said that, WCG are closely involved in the preparations for the new release, which I understand will also be released in WCG branding. If anything needs changing, I'm sure this issue will prompt them to change it.

**Comment by TheAspens** [comment]
Actually - I'm delinquent in testing this one.  It used to be that if you changed the master url from http to https you got a compliant.  I think that got fixed somewhere along the way but I need to verify.  If that got fixed, then we should https as well since having the first connection at http is a security hole.

**Comment by RichardHaselgrove** [comment]
I checked CPDN quite thoroughly this morning, both http and https on both variants of their url. No problems found. There might be a problem if we pushed this out to older clients on the 14-day update cycle, but it would be hard work to test that.

There's a single url in the structure of all_projects_list.xml, which is used both for attaching and for clicking through to the project website. As I said last night, of the 37 projects in the list, 9 (almost 25%) have websites which can't yet be accessed over https, so we'll need to leave those urls at http for this cycle.

**Comment by TheAspens** [comment]
I'm fine with waiting until 7.12 to update these, but when we do WCG should be updated to https.

**Comment by RichardHaselgrove** [comment]
We need to do an active reach-out to the non compliant projects before v7.12 - I'll email you the list tomorrow - but if you're certifying that WCG is compliant, I can update that before the next build. Then, we need to lock the agreed version of all_projects_list.xml as at the date of release into the version control system so that reversions don't creep in - I was investigating CPDN (and I'm still awaiting final confirmation from the project) because their url in the v7.10 release branch update was older than the Jan 18 BOINC-site 'authority'.

**Comment by davidpanderson** [comment]
boinc-site/projects.inc is authoritative; please let me know what edits to
make

**Comment by RichardHaselgrove** [comment]
We need to merge the changes you made in ae73f01eee8c1a92270a7cfc9f6c0b62fd92b65d and I made in 3e2b51dfee33dc35c967420246941200ba63c636

**Comment by adamradocz** [comment]
One more thing about the project chooser window. Under the Supported systems section, the Intel GPU never shown, even when the project has Intel GPU support.

**Comment by RichardHaselgrove** [comment]
Checked the code. There is no test for intel_gpu, and no icon resource to display the result if there was a test.

I found other problems when testing: I'll add them to #2579, so that we can deal with them all in a single pass.

**Comment by AenBleidd** [comment]
@adamradocz, is this still an issue? I believe it could be closed now

**Comment by adamradocz** [comment]
WCG still uses the `HTTP` protocol, not the `HTTPS`, but the Intel GPU support is shown now.

**Comment by RichardHaselgrove** [comment]
Any remaining http/https confusion would be better handled by #2696. I think this one can be closed.
