### ISSUE TITLE
Email Change Notification

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2451]
In issue #2447 we are discussing that there needs to be tighter controls on how to make it difficult to take over someone else's account.  This describes a change that will provide better security regarding email address changes.

Please see https://boinc.berkeley.edu/trac/wiki/EmailChangeNotification for a description of the design.

**Comment by Ageless93** [comment]
>If the user attempts to visit the change email address screen while user.email_addr_change_time is within 7 days, then they will be informed that they can only change their email address once every 7 days. 

* What if the authentic user looks in here, while their account was taken over? 
* What if the authentic user's old email address was no longer valid, so he didn't get the token, his account was taken over, the nefarious one has made the change of the email address and everything is waiting for the authentic user to click the token email (that he didn't get)? 

I know, in all these years we haven't had account take-overs (that we know of), but people's laptops have been stolen with a running BOINC on board. They have been using BOINC to figure out where their laptop was, due to changing IP addresses. Which is probably where the nefarious one will try to change these things, or delete the account so this info cannot be gotten. 
I also know that the above two things may happen once in a hundred years, if ever. Just asking if we need an option for that, or can they then send a PM to the admin? (If at least the account isn't deleted, with the PM still in there before admin read it. ;-))

**Comment by drshawnkwang** [comment]
Did PR #2500 resolve this issue? Is there a reason why it is still open?
