### ISSUE TITLE
broke boinc when moved from /var/lib/boinc to /home/boinc

### ISSUE THREAD

**Issue by mepreston** [BOINC/boinc#2506]
Hi,
I'm using fedora and opened a bug with that distribution and they quickly close it as not a bug as they say the code complaint with upstream so i guess i'll file an issue here.

So using Fedora 28 I installed 
boinc-manager-7.9.3-1.fc28.x86_64
boinc-client-7.9.3-1.fc28.x86_64

and after it was running a day or so noticed it was using /var/lib and i don't have a lot of left over space there and i have plenty in /home.   So i moved /var/lib/boinc to /home/boinc and change the home path in /etc/passwd and it would not start via systemctl.

i then tried 
semanage fcontext -a -e /var/lib/boinc /home/boinc
restorecon -R -v /home/boinc 
that didn't resolve the start issue

I've tried changing the /usr/lib/systemd/system/boinc-client.service and hardcode it to /home/boinc
and that didn't work.

So i feel strongly that the location of the boinc directory be chooseable at install time and if not possible at least allow and document how to move it after install.   So how do i get this to work when the home dir is not /var/lib/boinc.

and i did see the issue "Default working directory changd to /var/lib/boinc #2419" but that isn't suppose to be released till 7.10 and i'm using 7.9.

I did login as boinc user and can run the client but even then a lot of things don't work correct such as run preference, disk usage, suspending after hours, unsuspending at start time and so on.

cheers.

**Comment by lfield** [comment]
If starting the BOINC client with systemd, the Filesystem Hierarchy Standard (FHS) should be followed and hence persistent state data should reside in /var/lib. If there is not much space in /var/lib then there is potentially a system wide issue. Usually this is caused by log files in /var/log. The BOINC client can be run on the command line by a user and an option is available to define the location of the state directory. I would recommend not to mix /home and systemd.
