### ISSUE TITLE
Save versus Cancel in config and options type windows....

### ISSUE THREAD

**Issue by bigfootnlc** [BOINC/boinc#2546]
Greetings:

I recently updated to 7.10.2 on Windows 10x64, not sure from which version, but I try to stay up to date. There is one change that is really bugging me, a little thing really...

In Windows applications, generally, when you're working in a sub-window and are ready to leave that sub-window, you can either click on OK, or Save, or something like that. Or, you can hit the Enter key. I'm used to hitting the Enter key. However, in 7.10.2, at least, the Save button is not the default highlighted button. No, it's the Cancel button. This means that when you complete whatever changes you want to make and hit the Enter key, it bails out and dumps any changes because of the Cancel button being the highlighted selection.

WHY has this change been made? Please fix this!

btw, 'Ageless' on the BOINC Forum informed me that "We've changed from the OK button to the Save button to clarify that when pressing Save the changes will be made immediately. People would look into this window and click OK, and then later complain that their preferences had changed to the local ones without them 'knowing'. As far as I know, the only change we made was to the lettering of the button, not to the activity of it..."  I understand the change from OK to Save, but think the default highlighted button still needs to be the Save button.

Thanks!

**Comment by bigfootnlc** [comment]
Any update?  Thanks!

**Comment by JuhaSointusalo** [comment]
#2585 changes things so that if you are using web preferences Cancel is the default button and you'll get a confirmation dialog if you click Save. If you are already using local preferences then Save is the default button and there is no confirmation. For reason why changing default from OK/Save to Cancel was done in the first place see #601 and [CANCEL as default on options change](http://boinc.berkeley.edu/forum_thread.php?id=12515).

I believe the new implementation is a good balance between making it harder to accidentally change from web prefs to local prefs for people who pay no attention to what they are doing and making the Manager easier to use for power users like yourself. So I'm closing this issue.
