### ISSUE TITLE
Devise mechanism for updating all_projects_list.xml in github

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#2696]
all_projects_list.xml is dynamic data which is distributed to new users as a part of the installation process. Historically, it's held in this repository at master/win_build/installerv2/redist (and hence automatically incorporated in new release branches): although the location flags it as a Windows build file, the same resource is also used in Mac installer builds.

The file is also fetched periodically (every 14 days) by the BOINC client, unless disabled by corporate policies like <dont_contact_ref_site>.

At the moment, the file in master is 5 months old, and thus breaks the policy that master should be held in a state of readiness for the Release Manager when he or she decides to make a new client release branch.

This new issue is intended to act as a reminder that we have 'unfinished business' from the last few client releases, so that previous references like #2247 and #2579 can be closed or remain closed. This issue should be read in conjunction with @ChristianBeer comments in #2642, where the confusion between 'project config' and 'master' urls is discussed: this affects whether http or https is used in the primary url field in all_projects_list - see note on Einstein@Home in attached spreadsheet showing the current differences between versions of the file.

[Comparison of All_Projects_List versions 2018-09-19.zip](https://github.com/BOINC/boinc/files/2396794/Comparison.of.All_Projects_List.versions.2018-09-19.zip)

**Comment by KeithMyers** [comment]
Einstein has changed their URL to https now.  All the BOINC files will need to be changed also.

**Comment by RichardHaselgrove** [comment]
@KeithMyers - see the discussion on #4926. I think the Einstein change was in response to @AenBleidd's email to the projects list: one down, six to go.

But all should see the discussion in https://einsteinathome.org/content/master-url-changed-use-https: the change hasn't been welcomed in all quarters, especially by those users not yet running v7.16.20 or later.

**Comment by KeithMyers** [comment]
But of course you know the Catch-22 people are faced with when responding to the advisory messages about being connected twice to Einstein.  If you follow the instructions to remove and rejoin the project, you are going to use the Join Project mechanism which relies on the all_projects_list.xml file which still has Einstein listed with a http URL.

So you achieve nothing by taking action on the advisory.  Until that projects list file gets updated with the correct https URL for Einstein you are back to the original problem. Same thing applies to all the other projects still on http URL's.

I've been responding to posts in the forums complaining that the project managers aren't doing their job and I have to explain the project has nothing to do with the issue and the BOINC devs need to resolve it.

Most of Einstein's downloaded file URL's in the client_state file already are using https.  Only the master URL is still back at http.

I have several hosts still back on BOINC 7.9.3 because that is all that is available in the distro so they don't have the 7.16.20 mechanism to ignore the issue and I have been manually fixing the issue by editing the two files in the two places.  But I know what to do and the normal user does not and is not expected to resolve the issue by manually editing BOINC system files.

It looks like [#4926](https://github.com/BOINC/boinc/pull/4926) is the correct approach in my opinion.

**Comment by CharlieFenton** [comment]
Looking at the code, the BOINC client (including much older versions) downloads a new all_projects_list.xml from the [BOINC server](https://boinc.berkeley.edu/project_list.php) about every 2 weeks, or whenever the client is restarted. So I believe the issues with older clients should resolve themselves within 2 weeks after the URLs are updated on the BOINC server.

The all_projects_list.xml file on the server now has the updated URL for Einstein@home, so exiting and relaunching the client should fix the issue for that project, and it should resolve for that project within 2 weeks even without relaunching the client. (On my computer, the all_projects_list of 13 September 2022 did not yet have the updated URL for Einstein.)

Having said all that, I see a possible problem with the mechanism for downloading a new all_projects_list.xml every 2 weeks. The code that does this is called from `SCHEDULER_OP::init_op_project()` but only if communication with at least one project succeeded. I suspect it will never happen if all projects attached to the client are failing because of obsolete URLs (or if the client is attached to only the one project with an obsolete URL.) But this should not prevent downloading the all_projects_list.xml when the client exits and is relaunched.

**Comment by RichardHaselgrove** [comment]
Communications with a project usually succeed, even if the wrong flavour of http is used. The event log message/notice is a warning, not an error.

I've seen one exception to that rule recently:  if a project configures its server to reject all **non**-https connections. There's an acronym for that, but I've forgotten it again. Projects with allow redirect are OK.
