### ISSUE TITLE
Building on AlpineLinux outputs many more notes

### ISSUE THREAD

**Issue by tcely** [BOINC/boinc#2807]
The amount of warnings and notes output during compilation has increased significantly.

Log for 7.12.1 (4643 lines):
https://api.travis-ci.org/v3/job/415043084/log.txt

Log for 7.14.2 (52838 lines):
https://api.travis-ci.org/v3/job/452886252/log.txt

I haven't gone through all of the output yet, but it would be great if anyone could provide pointers for removing as many of these notes and warnings as possible. Thanks!

**Comment by ChristianBeer** [comment]
The gcc version between the two logs you posted jumped from 6.4.0-r8 to 8.2.0-r0. The later version of course creates more warnings because it does more checks. Thus it is not unusal and you can't strictly compare the number of warnings between the two.

This does not mean we should not address the warnings generated by newer gcc versions. But the reason for the increase in warnings is not AlpineLinux or the BOINC version build.

A lot seem to come from an outdated use of `memset`on structs. A lot are generated for code that is a dependency (zip, wxWidgets). One should focus on the `memset` warnings and the incompatible pointer type warnings (look for `CAccountManagerProcessingPageEvent` in the second log for an example).

**Comment by AenBleidd** [comment]
It's useless to track build warnings on the ticket.
Closing this as 'wontfix'
