### ISSUE TITLE
OpenCL sometimes doesn't detect Intel GPU

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2834]
On my laptop (Lenovo W530) the client sometimes detects the built-in Intel GPU (via OpenCL) and sometimes it doesn't. This leads to "stranded" jobs.  Happens with both 32 and 64 bit clients.

**Comment by JuhaSointusalo** [comment]
> Lenovo W530

According to Lenovo's website that is a 15.6 inch laptop with 23 inch display and weights 7.3 or 9.13 kg depending on which stand you select.

According to the rest of the Internet it's got i7-3720QM or thereabouts, HD Graphics 4000 and Quadro K2100M or thereabouts. It's an [Nvidia Optimus](https://en.wikipedia.org/wiki/Nvidia_Optimus) laptop.

On a hunch, do you sometimes use external monitor?

**Comment by davidpanderson** [comment]
Mystery solved!  Indeed, OpenCL reports the GPU if and only if the external monitor is disconnected.

As an experiment I allowed an Intel GPU job to start, then connected the monitor.  The job continued, but mouse tracking was sluggish and the left button stopped working.

Maybe in this situation (missing GPU that was previously detected by OpenCL) the client should print a message suggesting disconnecting an external monitor.

**Comment by JuhaSointusalo** [comment]
> Maybe in this situation (missing GPU that was previously detected by OpenCL) the client should print a message suggesting disconnecting an external monitor.

I think in the great majority of missing OpenCL GPU cases it's driver install gone wrong and OpenCL driver is missing.

FYI. Normally when you go to forums and ask help with Intel GPU you are told to forget about it. The reason is, CPU and GPU share the same thermal and power limits, RAM bandwidth and possibly caches. Intel makes fast CPUs but their GPUs are not so fast. Using the GPU tends to slow down CPU processing more than you gain from using the GPU. So far the only exception seems to be the lowest of the low end CPUs. In Atom family chips the CPU is so slow that the GPU manages to be competitive.

**Comment by davidpanderson** [comment]
Regardless of current performance, there are projects with Intel GPU apps and
BOINC needs to support them properly.
I doubt that problems due to driver changes outnumber problems due to
external monitors on laptops.

**Comment by JuhaSointusalo** [comment]
> I doubt that problems due to driver changes outnumber problems due to
> external monitors on laptops.

Lets put it this way. This is the first time I know of when the problem was diagnosed to be external monitor.

**Comment by RichardHaselgrove** [comment]
I think we know rather more about Intel GPUs than those exchanges imply. I've just - consciously and deliberately - triggered these log messages:

> 28-Nov-2018 08:08:52 [---] app version refers to missing GPU type intel_gpu
28-Nov-2018 08:08:52 [Einstein@Home] Application uses missing intel_gpu GPU
28-Nov-2018 08:08:52 [Einstein@Home] Missing coprocessor for task p2030.20170403.G43.05-02.29.S.b0s0g0.00000_1830_2

How? By removing the hardware dummy plug that normally tricks my Intel GPU into thinking that a monitor is connected. This is a desktop machine, and the real monitor is connected to an NVidia card. I think that's probably the commonest cause of iGPU failure, and it explains why devices like [these](https://www.amazon.co.uk/Headless-Display-Emulator-Headless-1920x1080-generation-HDMI-2K/dp/B072PV6K8J) are manufactured and sold.

David's external monitor problem is a new one on me, but it's clearly related. I'd guess that the real problem is disabling the internal screen, rather than using an external one. It's possible that changing a configuration - either in BIOS, or in the OS - to use both screens together might restore iGPU detection, But possibly not: I also have machines (Dell Optiplex desktop) where the iGPU is comprehensively disabled in BIOS when a discrete GPU is added.

The hardware and BIOS behaviour is manufacturer dependent: it would be hard to write a generic BOINC message that covers all three cases.

**Comment by RichardHaselgrove** [comment]
@JuhaSointusalo: I recognise those forum messages, but I think they come from writers with very specific preconceptions about how BOINC is going to be used.

It's true that if the CPU is going to be maxxed out with heavily optimised and overclocked floating point FFTW operations, there won't be any spare capacity in the power and thermal envelope to squeeze in the iGPU as well. But my experience is that if the CPU is gently pushing a few integers around, there's plenty of capacity to use the iGPU alongside: the machine I generated the log messages from has a RAC of 8,400 at Einstein using iGPU alone, which isn't too shabby. Tasks complete in just over 10 minutes.

**Comment by Ferroin** [comment]
My own experience mirrors that of @RichardHaselgrove,  I've got a system with an i7-8559 that I run one BOINC task per physical core (with HT on, so half as many tasks as logical CPU's) and a single NCI task, and I see no performance differences on that system whether I'm running a BOINC task that uses the iGPU or not.  That said, Intel's GPU's have gotten significantly better since the fifth generation Core chips, so I wouldn't be surprised if older chips really did have significant issues.

**Comment by JuhaSointusalo** [comment]
Ok ok, YMMV.

Back to the real topic. So there's driver problem, external monitor connected, no monitor connected, another GPU installed, and it just occurred to me, replacing a GPU with one from different brand. If there needs to be some kind of help message I think a link to an FAQ or manual would work best.

**Comment by RichardHaselgrove** [comment]
External linkage from the Event Log is problematic - you can only copy a complete line, and then you have to extract the url manually. A notice might be needed.

I think driver problems are rarer than they were. Windows 10 (in particular) caused endless headaches in the early days by removing all GP compute tools (both cuda and opencl) when installing the 6-monthly updates. But with my most recent test (I think with the Fall update last year), NVidia cards were given the CUDA driver, and Intel GPUs were given the OpenCL driver. And the Intel driver restored OpenCL support for the NVidia card, too.

**Comment by JuhaSointusalo** [comment]
I thought about notice but I'm not sure if it's the right thing here. It feels to me that a notice is something that demands user's attention. It won't be good if BOINC is nagging about something every time the computer is started. So the user should be able to do something to make the notice go away.

Some actions would be easy to do. If the GPU changed from AMD to Nvidia then the only action is to abort the old GPU tasks. But some actions need quite a bit more technical skills like inserting dummy plug or changing BIOS settings. Wasn't BOINC was a bit too technical already. And it wouldn't help with David's scenario of sometimes using an external monitor.

If the user can't figure out what to do or can't do anything we'd need a way to tell BOINC to not show some notice ever again.

I don't know. Feel free to sell me a good idea :)

**Comment by davidpanderson** [comment]
The logical place to link to is https://boinc.berkeley.edu/wiki/GPU_computing
That page is mostly outdated; we should get rid of most of it before adding anything.

Yes, parts of BOINC are too technical.  That doesn't mean we should deliberately
omit information about why jobs mysteriously stop in the middle.

**Comment by RichardHaselgrove** [comment]
Having said that driver problems had gone away: driver problems haven't (necessarily) gone away.

https://www.intel.com/content/www/us/en/support/articles/000031275/graphics-drivers.html

> Microsoft is moving to a new Universal Drivers architecture starting with Windows® 10 October 2018 Update. This represents a shift in our Intel® Graphics Drivers.

> Intel is targeting November, 28th 2018 for the release of our first graphics Modern Windows Drivers via DownloadCenter and Intel® Driver and Support Assistant (IDSA).

I'll run some tests.

**Comment by AenBleidd** [comment]
I'm closing this ticket now since it's already 6 years old, and during these years there were a lot of changes both on OS's and drivers' side.
I don't think we need to do anything additional here.
If there is still a problem - we can always reopen this ticket, and think about good solution of handling such a cases.
