### ISSUE TITLE
more advanced preferences

### ISSUE THREAD

**Issue by cristipurdel** [BOINC/boinc#2938]
**Describe the problem**
It would be better to have some bleeding edge features, requiring root or not, which should be not enabled by default
For example to enable the deprecated Android remote monitoring in
https://github.com/BOINC/boinc/issues/1699
Or supporting Arm GPU hardware, etc.

**Describe the solution you'd like**
Add an entry "Show extreme/dangerous preferences and controls" under the similar one in "Show advanced preferences and controls"

**Additional context**
Can be treated as some sort of alpha testing

**Comment by adamradocz** [comment]
ARM GPUs are supported, but there is no project that supports it.
The advanced features already for power users, we won't make "more advanced" section, because it would be confusing. If you have a specific feature request it will be added if legit enough, but putting back legacy code is really bad practice.
