### ISSUE TITLE
config.h is not installed

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#2964]
In #1624 @tomasbrod mentioned:

> I am affected by this issue. config.h is not installed. Almost all header files installed in /usr/include include that "config.h" file making them useless without the missing header.

**Comment by tomasbrod** [comment]
I think this issue was not reported earlier is because building out-of-tree apps is not supported and all apps that are built out-of-tree are using internal boinc tree copy (with config.h).

**Comment by AenBleidd** [comment]
Walking around I found this thread:
https://lists.gnu.org/archive/html/autoconf/2013-07/msg00043.html
Looks like fixing this is not so trivial

**Comment by tomasbrod** [comment]
I thought the `#include <boinc/config.h>` is unambiguous. Maybe the problem mentioned was caused by installing config.h to the root inclusion namespace.

**Comment by brevilo** [comment]
While it might not be trivial, it still seems [straight-forward](https://www.gnu.org/software/autoconf-archive/ax_prefix_config_h.html).

**Comment by brevilo** [comment]
What I don't understand is this: most people who build BOINC should be projects admins/developers. I presume that none of those effectively install BOINC (via `make install`) in the standard `prefix`, eg. `/usr/local`. Project admins rather compile BOINC (server) and copy the binaries to their production server. Project developers compile BOINC (api/libs etc.) in a dedicated build environment as a build dependency of their science apps and screensavers. In both cases BOINC should be rather isolated which would mean installing `config.h` in the configured `prefix` would mean no harm.

I also checked the depencies BOINC itself requires: they don't install `config.h` themselves so there won't be a conflict there either.

That said, not installing `config.h` seems trying to solve a non-existent problem, while causing issues for those having to compile/use BOINC as build dependency. Therefore I do see two ways forward: install `config.h` and see if it **really** causes problems (I doubt it) or use `AX_PREFIX_CONFIG_H` as mentioned in my previous comment.

**Comment by CharlieFenton** [comment]
The issue is ensuring that the client and manager built by Berkeley and World Community Grid for distribution to the public can be installed on a range of Macintosh computers. Project applications are also distributed to the public and must run on a range of computers. As I wrote in my comments to PR #3471:

If you use configure to create the config.h file, the generated code may not work on older versions of OS X, and may not work at all (as implied by PR #3471.) The Xcode build uses a fixed version of config.h at clientgui/mac/config.h, and so should the make file.

As I understand it, the config / make approach was developed on a model where each user would build most software themselves, on their target computer, from the source files. This starts with running configure on that target computer, since configure determines the build options by testing what resources are available on that peculiar machine and optimizes the build to run on that particular machine.

But those resources may not be available on versions of OS X older than the one on the build machine. This is one of the reasons I created a special config.h for Mac builds at clientgui/mac/config.h. All that is needed to use this is to put that path ahead of others in the search path, or to put a symbolic link to it where the make file expects to find config.h, and of course just don't run configure.

(FWIW, Apple bases their limited approach to backward compatibility on a very different model, using availability macros in its headers.)

**Comment by brevilo** [comment]
Charlie, this isn't just about macOS, but also Linux or even Windows when cross-compiled using MinGW. Also, regarding macOS, as I replied in [3471](https://github.com/BOINC/boinc/issues/3471#issuecomment-591333208) already, using configure/make isn't a problem at all if done right. We're using that for **all** the builds we distribute at E@H.

Official BOINC builds can and should be built as you see fit and thus use the fixed `config.h` you provide but that shouldn't preclude working `configure/make` setup. Furthermore, it had already been [agreed](https://github.com/BOINC/boinc/pull/3218#issuecomment-533322152) that api/lib builds should be supported via `configure/make`. What we're trying to do here is to get those parts fixed that are broken/incomplete right now.

**Comment by CharlieFenton** [comment]
I just re-read that reply and I agree. (I think I missed it before.) If you build using the oldest OS you are supporting, then `configure/make` is fine. As long as others who use it also understand that restriction.

> Another idea: could config.h be installed conditionally, e.g. when prefix doesn't point to /usr or /usr/local?

Sure, that sounds like it could work.
