### ISSUE TITLE
Images in Notices don't appear on macOS, but they do on Windows

### ISSUE THREAD

**Issue by numbermaniac** [BOINC/boinc#2996]
**Describe the bug**
If Notices contain embedded images, they just show up as a question mark on macOS - however they do work on Windows.

**Steps To Reproduce**
1. Include an image in a Notice. Then check how it displays on both platforms.

**Expected behavior**
The images should show on both platforms

**Screenshots**
Windows:
![windows](https://user-images.githubusercontent.com/5206120/52023414-28e22a00-2551-11e9-8f23-0c205881af8e.png)

macOS:
![screen shot 2019-01-31 at 11 54 06 am](https://user-images.githubusercontent.com/5206120/52023421-30093800-2551-11e9-904d-1d595e0596bb.png)

**System Information (please complete the following information):**
 - OS: macOS 10.14.2
 - BOINC Version: 7.14.2

**Comment by CharlieFenton** [comment]
The images display properly with BOINC 7.8.6 (January 14, 2018), but not with 7.9.1 (February 12, 2018) or later. Between those dates, changes were made to the relevant code and we also upgraded  the GUI library used by the Manager from wxWidgets 3.0.0 to wxWidgets 3.1.0. I took a look at the differences in this function on the Mac both in the BOINC code and the wxWidgets code, and have not identified any obvious cause.

**Comment by RichardHaselgrove** [comment]
Not necessarily between those dates. v7.8.6 (the final Mac patch for that branch) was based on code split from Master around Jun 18, 2017: v7.9.1 was built from a branch split around Feb 9, 2018. I seem to remember that there were quite a lot of commits after Jun 18 that weren't cherry-picked into the 7.8 branch.

**Comment by RichardHaselgrove** [comment]
My PR #2065 - closed without merging, because it has long since been overtaken by events - could perhaps help jog our memories about the commits made before Jan 14 but not exposed until v7.10

I don't immediately see anything related to notice display, though.

**Comment by CharlieFenton** [comment]
After many hours trying unsuccessfully to find the changes in BOINC or wxWidgets code responsible for this issue, I finally noticed this message in stderrgui.txt:
> BOINCManager[93247:533289] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

It turns out that this issue was not caused by any changes we made. Apple introduced tighter security restrictions in WebKit (used by wxWebView) and various network access APIs for applications built under OS 10.11 or later. Since I built BOINC 7.8.6 using OS 10.9, it continued to properly load these images even when run under later versions of OS X. However, when I made a new build of BOINC 7.8.6 using the same source files, but building with a newer version of Xcode under OS 10.11 or later, it failed to load the images and produced the same error message quoted above.

[This article](http://www.neglectedpotential.com/2015/06/working-with-apples-application-transport-security/)  says:
> With iOS 9 and OS X El Capitan, Apple has introduced App Transport Security. In a nutshell, App Transport Security enforces best practices for secure network connections — notably, TLS 1.2 and forward secrecy. In the future, Apple will also update these best practices to ensure they always reflect the latest security practices that will keep network data secure.

[This article](https://www.nowsecure.com/blog/2017/08/31/security-analysts-guide-nsapptransportsecurity-nsallowsarbitraryloads-app-transport-security-ats-exceptions/) describes some of the security vulnerabilities addressed by this change. 

[This article](http://www.neglectedpotential.com/2015/06/working-with-apples-application-transport-security/) summarizes what happened with BOINC:
> App Transport Security is enabled by default ... in iOS 9 or OS X El Capitan. Unfortunately for many developers this may mean that things break as soon as they build for iOS 9 or OS X 10.11. 

I can see 4 possible ways to fix this:
[1] The security restrictions can be completely disabled by adding the keys _NSAppTransportSecurity_ and _NSAllowsArbitraryLoads_ to the Manager's _info.plist_ file. This is strongly discouraged by Apple as it compromises security. Apple may in the future remove this option.

[2] The security restrictions can be disabled for all web content by adding the keys _NSAppTransportSecurity_ and _NSAllowsArbitraryLoadsInWebContent_ to the Manager's _info.plist_ file. Since we are only loading web content in Notices, this is probably equivalent to option 1. Apple may in the future remove this option.

[3] Tell all projects that they must use **https://** for all resource URLs in their notices. The projects must ensure that all the URLs can be accessed via  **https://**, with at least TLS 1.2 and forward secrecy. Note also that the certificates must be obtained server certificate from a known certificate authority (CA); self-signed certificates will be rejected.

[4] Add code to _NoticeListCtrl.cpp_ which replaces all instances of **http://** with **https://** in the notices. This would allow notices sent to the client with **http://** to continue to work, but the server requirements of option 3 remain. So this probably offers no advantage over option 3.

Hopefully we all agree that ensuring BOINC's security is a high priority, so I recommend option 3.

**Comment by davidpanderson** [comment]
I agree with Charlie; option 3.

**Comment by TheAspens** [comment]
Charlie notified the projects via the boinc_projects mailing list.  Since the reporter of the issue gave a 'thumbs' up to @CharlieFenton's recommended option #3 and since @davidpanderson agrees and there are no dissents, I am closing this issue as not a bug.
