### ISSUE TITLE
Suspend when non-boinc load exceeds X % not working in container environment

### ISSUE THREAD

**Issue by VedantMahabaleshwarkar** [BOINC/boinc#3100]
Deploying the linux app for boinc in a container environment, on an Openshift cluster. 
The aim is to suspend the boinc container when other pods on the cluster take up resources. However, this feature does not seem to be working. BOINC never suspends irrespective of the non-boinc load running in another container on the same node of the cluster. 
How do I get boinc to suspend in this scenario?

**Comment by Ferroin** [comment]
I suspect that this is due to BOINC not being able to see anything outside it's own container (which means it either can't see the high CPU usage, or can't figure out what's causing it).  Correctly handling this without compromising the security of any of the containers is likely to require handling from the container management stack, not BOINC.

**Comment by anshugoe** [comment]
@Ferroin So is it because BOINC calculates percentage usage of CPU based on processes running on the same container and not how much resource is actually free since those resource might also be getting used by some different containers 
Also, it would be great if you could help us point out in which file these calculations are being made.

**Comment by Ferroin** [comment]
I'm not exactly sure where it's doing the calculations, but on Linux systems I'm fairly certain it's looking at the same files in `/proc` that the `top` command uses to calculate total CPU usage, and does similar on MacOS and Windows (just using different API's to get the data).  Depending on how aggressive the container software is at isolating containers from the rest of the system, that may or may not include any CPU usage from processes in other containers or on the host system, and if it does include such usage, it may be accounting it as 'guest' time (just like would be done with a tightly integrated QEMU VM).  In the event that the usage info is included, BOINC will ignore it if it's accounted as 'guest' time (it just doesn't look for that, just like it doesn't pay attention to time the system spends in the kernel's IRQ handlers), and even if it did, it seems to get confused by usage that can't be traced back to processes it can see.

Pretty much, your best bet here is probably not going to be changing BOINC to work in this situation, but to add something on the container host (or the management system) to watch overall utilization of the non-BOINC containers, and suspend the BOINC container if that utilization is too high.

**Comment by AenBleidd** [comment]
BOINC is not designed to work in a container and monitor resources outside of the its container because of security issues. If you want to let BOINC work when there is no system high-load by other processes you should do this manually or install BOINC directly on your hardware without any containers

**Comment by adamradocz** [comment]
This issue can be closed.

**Comment by anshugoe** [comment]
@AenBleidd @Ferroin When you say security issue, is it security concern to BOINC or other non-BOINC process running in some different container.
The reason I am trying to run BOINC as a container so that it is able to utilize all the slack resource of my node/cluster without affecting any of the primary containers running. Tuning BOINC container is possible from outside but I believe that wouldn't be as efficient as BOINC could be since it would have to kill the container rather than pausing it. Do you have any better suggestions on this ?

**Comment by AenBleidd** [comment]
When I say "security issue" I mean BOINC must know nothing about the environment outside of the environment he run on (in this case, inside the container). And I believe it can't.
And no, I have no other suggestions except third-party software to control container or BOINC client inside it

**Comment by anshugoe** [comment]
I believe this is the part of code where BOINC is calculating CPU usage of non-BOINC process running in the same environment. There are cross-platform library like psutil in python which can get us the resource usage of all other containers running on the same node, without exposing much details

This looks like the final calculation:
https://github.com/BOINC/boinc/blob/master/client/app.cpp#L501

Which uses this helper method:
https://github.com/BOINC/boinc/blob/f14d96d2be2e5a290177f7b5391b0802fbd3756c/lib/procinfo.cpp#L111

**Comment by Ferroin** [comment]
@anshugoe As stupid as it sounds, external management of BOINC resource utilization is, in my experience at least, way more efficient than just letting BOINC do it.  You get much more fine-grained control of trigger conditions, as well as being able to potentially react faster than BOINC itself does, and even potentially scale it down preemptively.

I've not done it with container software, but I've done it both manually with Linux control groups, and with some special tuning with Xen back when I was using that actively for virtualization, and in both cases I got much better results than having BOINC handle things.

The whole point of having such functionality in BOINC itself is so people who don't understand this type of thing don't have to go way out of their comfort zone to get it to behave reasonable sanely (IOW, it's there for convenience).

**Comment by adamradocz** [comment]
Applications can't know anything outside of the container by design.
I use the [boinc-client-docker](https://github.com/BOINC/boinc-client-docker) and it works fine. The processes inside the container have low priority, so it uses the unused system resources.

**Comment by ChristianBeer** [comment]
The idea of a container is to contain what is inside and not let it know what is outside the container. Depending on how much control you have other the containers you might set up a system that communicates with the Client inside the container via RPC (boinccmd from the outside) or execute a script inside the container (calling boinccmd) and controlling the client this way.
What you should not do is destroy and create containers whenever the load changes. This only leads to problems on the projects side due to excessive host numbers in your account since every new container is considered a new host. You should monitor that.

**Comment by AenBleidd** [comment]
I believe question by @VedantMahabaleshwarkar  was answered well enough. Closing this ticket
