### ISSUE TITLE
[Web] Add android to project options

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3223]
**Describe the problem**
I run LHC and Einstein as backup projects and I want only GPU tasks for PC and any task for Android. The issue is if I check-out the `Use CPU` option to not get any CPU task for PC, then I don't get any task for Android as well. Even tho I'd like to run any kind of Android task.

**Describe the solution you'd like**
Get CPU task for Android, even when the `Use CPU` option is checked out. Separate options for the Android and PC would be the best and most straight forward.

**Comment by AenBleidd** [comment]
Try to use different settings, e.g. 'Home' settings for Android, 'Work' settings for other devices or vice versa.
I see no reason to add 'Android' option because there are currently 2 kind of tasks, the one that use CPU and the one that use GPU. Android tasks use CPU only (potentially GPU also but there is no project for Android that has application that could run on mobile GPU).
So personally I think that this option is unnecessary

**Comment by AenBleidd** [comment]
@adamradocz, please use this [link](https://boinc.berkeley.edu/wiki/Preferences#Location-specific_preferences)

**Comment by adamradocz** [comment]
Settings name can't be changed, so it's really deceiving. I don't like using it because I don't know which is which.

**Comment by Rytiss** [comment]
Venues can definitely solve this problem already, so closing this issue.

Allowing one to change venue names or create custom venues is a different issue, which has been determined to be a "won't fix" in #313. I do think allowing custom venue names is actually a good idea, so if that would work for @adamradocz I can look into implementing it (@adamradocz, please create a separate issue if so).
