### ISSUE TITLE
Allow the validator to flag compared results as `runtime_outlier`

### ISSUE THREAD

**Issue by amereghe** [BOINC/boinc#3256]
`runtime_outlier` is a flag that allows to disregard the use of a specific result to update the FPOPs estimate of a specific host. This mechanism can be important when the result is generated with a number of FPOPS way smaller than expected; otherwise, in presence of many of these results, the FPOPs of a host can be corrupted.

The aim of SixTrack simulations is to find the boundary between stable and chaotic motion in accelerator beams. Chaotic motion leads to beam losses and hence an early end of computation, in presence of a set of input files fully correct and a totally correct job processing. Since a single job covers a tiny bit of phase space to be studied, it can easily happen that a job ends way earlier than expected simply because the initial conditions falls in a region of chaotic motion.

Since SixTrack validates results, it is essential to spot validated results obtained with a number of FPOPS way smaller than expected. The validation file reports if losses took place or not; hence, the best place where to set `runtime_outlier=true` is in `files_match` in `compare_results`. At present, we can flag only the first result as runtime outlier, since the second one is passed via the interfaces as `const`.

**Comment by AenBleidd** [comment]
@lfield, this ticket was open 3 years ago, and the implementation of it was not agreed.
Is it still an issue and should be discussed further or it is not needed anymore and thus could be just closed?

**Comment by RichardHaselgrove** [comment]
As one of the people who identified the need for the outlier mechanism at SETI@Home (it wasn't included in the first version of [runtime estimation](https://boinc.berkeley.edu/trac/wiki/RuntimeEstimation)), I would say it is definitely still needed. The SETI and LHC applications are very similar in this respect, although the interpretation of the very short outlier results differs.

I can't comment on the specific technical detail of this particular issue, but the general purpose is needed: **every** result which passes validation after an abnormal runtime needs to be flagged, otherwise the host's APR record can be damaged to the extent that normal runtime tasks are errored for exceeding rsc_fpops_bound.

**Comment by davidpanderson** [comment]
This exists: https://boinc.berkeley.edu/trac/wiki/ValidationSimple#Runtimeoutliers

**Comment by RichardHaselgrove** [comment]
In general, a project validator will use custom code to suit the data and constraints intrinsic to the science being researched. Only in very simple cases will the sample validators maintained in the BOINC sources be sufficient.

I don't know what validator is used for the LHC sixtrack application. A source (and line) reference for the statement

> we can flag only the first result as runtime outlier, since the second one is passed via the interfaces as const.

would be most helpful.

If the problem lies in the BOINC sample code, it could - and should - be fixed here. If the problem lies in LHC custom code, it's up to LHC to fix it, and this issue can be closed.

**Comment by lfield** [comment]
I think this can be closed. We are working on a new application in this area so if it is still an issue, we will find it again.
