### ISSUE TITLE
Boinc won't take 100% CPU

### ISSUE THREAD

**Issue by Sekaiji** [BOINC/boinc#3318]
Greetings fellows,

I'm a daily user of Boinc since 14 years.
2 weeks ago I added some new sub projects of LHC@home called "Atlas".
Those tasks are running in virtualbox and use 8 cores and a lot of RAM.

My issue is when I crunch for those tasks my CPU is used around 80 to 85 %.
I would understand it's normal if I had "only" crunching this sub project, but I'm also participating on WCG and Rosetta so Boinc could use the other tasks to fill the gap. Actually it's using some rosetta tasks but not enough to reach 100%.

When using other projects, I'm always at 100%. CPU.

I didn't modify the default settings in Boinc.

Conf :
Windows 10
RAM usage is 41Gb of 64 Gb
Threadripper 3990WX
500Gb free on 1Tb

Any help will be appreciated.

**Comment by adamradocz** [comment]
Is there any free ram for boinc?
What's your memory setting for "When computer is in use, use at most X%?"

**Comment by Sekaiji** [comment]
Yes there's enough ram for boinc, I have 64Gb ram and only used 20 to 42 Gb depending of other softwares launched.
My settings in Boinc for Memory are 90% (while in used) 95% (while not in used) 90% (swap).

This behaviour is not always like that. Sometimes, like now, I have 100% used CPU with a mix of 2 LHC (Atlas) tasks and 48 WGC taks.

**Comment by AenBleidd** [comment]
In general, BOINC run 1 single-thread CPU task on 1 CPU core. In case of GPU situation is different, in common case 1 GPU task uses 1 GPU device and some amount of CPU.
Sometimes (mostly with Virtual box tasks) it is possible that 1 task will use less than 1 CPU core because of saving data to disk that takes time and doesn't use full CPU core for this.
So my question is:
How many cores to do have? How many tasks do you have running simultaneously (please also take in account how much CPU cores each task uses, it's always written in the description of the task.l)?
In a situation, when 1 task allocates 1 full core but uses it 100% - BOINC will not run additional task to reach 100% CPU usage.

**Comment by Sekaiji** [comment]
Ok some precisions :
I have 32 cores 64 threads
I run only CPU tasks, no GPU
I have always 64 tasks running when crunching for WCG, Rosetta and LHC (sixtrack). Those tasks doesn't require virtualbox. My CPU will be always used at 100%.

When working on LHC (Atlas) those tasks requires virtualbox and 8 CPU per tasks. Boinc will run a mix of those tasks plus WGC or Rosetta tasks but sometimes won't reach the 100% cpu usage because some cores will stay idle.

Now I'm reaching 100%, CPU usage so I'll post again when I'll have more information about how many cores are used when the problem occurs.

**Comment by Sekaiji** [comment]
Now have 5 LHC (Atlas) tasks that takes 8 cores each +24 tasks of WGC and LHC (sixtrack).
So I can see 64 tasks running and my CPU usage is average 80%
My ram is used at 40 Gb on 64Gb.
In the windows task manager I can see around 21 cores that are not fully used, from 1% to 65%.

**Comment by RichardHaselgrove** [comment]
Once a core is assigned to a VM by BOINC, BOINC regards it as unavailable for other projects - whether the VM needs that core at any particular moment or not.

The allocation of cores within the VM is the subject of a private conversation between the VM and Atlas, bypassing BOINC. If you wish to ensure that every core of every VM is utilised by Atlas, you will have to take that up with Atlas, not here.

**Comment by AenBleidd** [comment]
So I see no issues here.
Multithread tasks could not run 100% time on every CPU core because of
synchronization or any other reasons (e.g. checkpointing to disk).
It's up to every application to use CPU effectively.
BOINC can do nothing with this. And it's not correct to assign more tasks
to use cores that are not fully used with additional tasks.
-- 
Best regards,
Vitalii Koshura

Sent via iPhone

**Comment by Sekaiji** [comment]
OK so it's the way Atlas is using the assigned cores. I guess i'll just stop working for this project.
Thanks

**Comment by AenBleidd** [comment]
I assume that question is resolved so I close this ticket.
@Sekaiji, if it's necessary feel free to reopen it
