### ISSUE TITLE
[Android] 7.16.3, doesn't run, always suspended - on batteries

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#3333]
Putting my Huawei P20 lite (Android 9) phone on the charger, when BOINC 7.16.3 starts it stops at the end of the loading with Suspending computation - on batteries. It hasn't run any of the work it had in cache since I upgraded to 7.16.3, and the phone's been on the charger every night, and in between in the car (doubling as navigation). 

Returning to 7.4.53 immediately started work (although the previous tasks were lost of course).

**Comment by AenBleidd** [comment]
I believe the real issue is that boinc client crashed, And this is just an aftermath of it.

**Comment by Ageless93** [comment]
Here as well, I took the message from the event log. For the event log to
be visible the client must be running. So it wasn't crashed.

**Comment by Ageless93** [comment]
https://setiathome.berkeley.edu/show_host_detail.php?hostid=8691436 is the host. The last task finished was on 7.4.53, since 7.16.3 nothing has been returned. I updated over 7.4.53, and didn't check if it was running OK. Egg on my face. :(

**Comment by Ageless93** [comment]
Okay, I'll have to reinstall it on the phone to test something there. 
The problem with any new install is that it uses the default preferences from the website for things like communications. I have a separate Home location set up for my Android devices, but forgot to add this device to that location. So will have to test it again. Will wait for present work in cache to be done though. So that'll be tomorrow at the soonest.

**Comment by KenSharp** [comment]
This is also true on the Galaxy S7. If you look at the battery icon (in my case) it shows that charging has completed and hence it is technically not charging any more (though it isn't running from battery either).

I haven't looked into this further but I suspect that that is the issue.

To get around this on the Galaxy S5, I simply tell BOINC to run on batteries, but then this phone is plugged in all the time, whereas the S7 is not.

I need 7.16.3 so that I can add a customer account manager. No doubt I could use the old version and sideload an edited APK but that's for another day.

**Comment by talregev** [comment]
Can you check it again on 7.16.16?

**Comment by AenBleidd** [comment]
Should be fixed in the new release. Please reopen this ticket if this issue will be still there after testing a new release
