### ISSUE TITLE
per_app_list.php keeps old averages forever

### ISSUE THREAD

**Issue by computezrmle** [BOINC/boinc#3373]
BOINC projects like LHC@home use top_users.php and per_app_list.php to present user credit ranking pages.
Both pages allow to sort the lists by average but they behave different.

top_users.php
Inactive users slowly move down the ranking over the time.
This corresponds to the behavior at the user details page where the same average is also shown.

per_app_list.php
Averages (per subproject) shown here remain on the last calculated value even if a user doesn't run tasks for a distinct subproject any more.
This should be changed to the behavior shown at top_users.php.

**Comment by lfield** [comment]
This turned out to be a project configuration issue. The [instructions](https://boinc.berkeley.edu/trac/wiki/PerAppCredit) use decay_per_app_credit.php but the actual script is [decay_credit_by_app.php](https://github.com/BOINC/boinc/blob/master/html/ops/decay_credit_by_app.php). The php.ini was also limiting the memory available to use. The documentation has been [updated](https://boinc.berkeley.edu/trac/wiki/PerAppCredit?action=diff&version=7&old_version=6).
