### ISSUE TITLE
[Explained]systemd service not passing arguments to client

### ISSUE THREAD

**Issue by JStateson** [BOINC/boinc#3393]
Arguments to a service, such as the boinc client, need to be put into an environmental file.  That file exists, but is not identified in the service.

in /lib/systemd/system/boinc-client.service make the following change:

from
```
WorkingDirectory=/var/lib/boinc
ExecStart=/usr/bin/boinc
ExecStop=/usr/bin/boinccmd --quit
```

to 
```
WorkingDirectory=/var/lib/boinc
ExecStart=/usr/bin/boinc $BOINC_OPTS
EnvironmentFile=/etc/default/boinc-client
ExecStop=/usr/bin/boinccmd --quit
```

the script /etc/init.d/boinc-client attempts to pass $BOINC_OPTS but fails.  The spec
https://wiki.archlinux.org/index.php/Systemd
calls for arguments to be in an environmental file.
If that init.d file is depreciated (so I have heard) then the /etc/default/boinc-client should not be depreciated as it is useful for passing arguments and should be modified to only have something like the following
```
# Here you can specify additional options to pass to the BOINC core client.
# Type 'boinc --help' or 'man boinc' for a full summary of allowed options.
#BOINC_OPTS="--allow_remote_gui_rpc"
BOINC_OPTS=""
```

Right now it has a lot of stuff used by the init.d script but it worked fine when I ran
```
systemctl start boinc-client
```
and the client accepted the arguments I had put it.

**Comment by AenBleidd** [comment]
@JStateson, could you please make a PR with the changes you suggest? Thanks

**Comment by JStateson** [comment]
AFAICT this code is not under source control at GitHub (newbie could not find it) so there is nothing to push into.

**Comment by tristanolive** [comment]
It looks like [boinc-client.service.in](https://github.com/BOINC/boinc/blob/master/client/scripts/boinc-client.service.in) is the file you're looking for. If you're not too accustomed to working with git and could use a few pointers, we can help; otherwise, I'll look forward to seeing your PR merged!

**Comment by JStateson** [comment]
The change to the servicxe.in file needs to be
```
ExecStart=@exec_prefix@/bin/boinc $BOINC_OPTS
EnvironmentFile=/etc/default/boinc-client
```
However, I have not set up my branch (if that is the term for it) correctly as I seem to be pushing into the master.  I do not know how to configure so that each change is a different tag.  I think that is what Vitalii was telling me on the pull for #3342 when he said "lit is not ok to use the master".
My local repo has the above cjhange.  If I do the "git add ." followed by a "commit -m" and a push to "git push origin fix-non-allowed" that change goes into (or includes) the issue 3342.  Is that OK??

**Comment by tristanolive** [comment]
The idea is to use branches anytime your are working on a distinct problem or improvement. So if you aren't frustrated with the process, we should try to separate your change here from the ones in #3342. In general, what you would do when starting a new task is:

- Use `git branch` to see what branch you're currently on and `git checkout master`, if needed, in order to get back on the master branch
- Use `git pull` to be sure your local copy of master is sync'd with github
- Create a new branch for your changes, e.g. `git checkout -b jstateson_systemd-pass-arguments` (note that this branch is created based on the branch that was active/checked out, which is why the first thing to do was get on master and be sure it is up to date)
- Now you are on the new branch (and can confirm with `git branch`), so you can make your changes
- Once done, `git status` shows which files have changed and `git diff file1` can show you exactly what changed in a file. You can then use `git add file1 file2` to stage the relevant files into a commit and `git commit` to actually commit them to the branch (and typing a nice description of the changes helps others understand what is being done)
- Continue until all work is done, it's ok to have many commits in one pull request
- With all commits done in your local branch, push the branch as a pull request: `git push -u origin jstateson_systemd-pass-arguments` (this assumes "origin" is the name of the github remote, which is true by default)

If at any point you want to stop working on one task and switch to another, you can commit your changes to the branch you're on and then `git checkout jstateson_other-branch`. Be careful that you don't have a bunch of files open in text editors with the affected code, though, or you may end up with some surprises...

Now for this current issue, if you can, check out your master branch and then create a new branch for this specific change to the boinc-client.service file. You can then `git add boinc-client.service.in` and commit that, leaving any other changed files alone (`git add .` would add everything, so that should be avoided unless you really want to add everything in the current directory).

Hopefully this helps to get you going -- it really is a nice system once past the initial learning curve.

**Comment by JStateson** [comment]
Sorry, just got  back to this.  What you wrote was helpful but I should have done the branching first long ago.  I am back now on (my) master branch and did the pull.  However, it is up to date with my master at github/jstateson.  That one is a few of commits ahead and a lot more behind the upstream.  When I did the pull I expected to see it brought up-to-date with the Berkeley upstream.  I assume it is ok to continue with what I have and not try to update my master to the upsteam.  I am going reverse my change (the service.in), make a new branch, make the change, and then push that and avoid any "git add .".  This look ok?

**Comment by AenBleidd** [comment]
@JStateson, these two articles could help you:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by tristanolive** [comment]
> I assume it is ok to continue with what I have and not try to update my master to the upsteam

This should be fine. There may be one trick, though. Since your master has diverged from upstream, the new branch you'd make would be based on code (or more accurately, a commit hash) that doesn't exist upstream. You can avoid this by specifying which commit to use as the base for your new branch:

- On master, `git log` will show you the history of commits. The idea in this case is to find the latest one that is not yours
- Use the commit hash/ID of the most recent upstream commit that you have as the base of your new branch, e.g.: `git checkout -b jstateson_systemd-pass-arguments 83fc04e248f586720d454e09775eea4a5484db7b`

That should give you a branch that is ready to be merged upstream cleanly (once you apply your changes, of course).

**Comment by yuri-sevatz** [comment]
I setup a PR to avoid some issues with different .conf file paths for this.

We can get away with just specifying $BOINC_OPTS during ExecStart, in boinc-client.service.in

Then users can customize their own unit files like so:

# cat /etc/systemd/system/boinc-client.service.d/00gentoo.conf 
```
[Service]
Environment="BOINC_OPTS=--allow_remote_gui_rpc"
```

Yields:
```
● boinc-client.service - Berkeley Open Infrastructure Network Computing Client
     Loaded: loaded (/usr/lib/systemd/system/boinc-client.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/boinc-client.service.d
             └─00gentoo.conf
     Active: active (running) since Wed 2020-02-19 02:15:07 EST; 3s ago
       Docs: man:boinc(1)
   Main PID: 195328 (boinc)
      Tasks: 8 (limit: 38427)
     Memory: 144.1M
        CPU: 6.254s
     CGroup: /system.slice/boinc-client.service
             ├─195328 /usr/bin/boinc --allow_remote_gui_rpc
...
```

Seems to work  :+1:

**Comment by yuri-sevatz** [comment]
Quoting here what looks like the preferred way to solve this instead:

https://github.com/BOINC/boinc/pull/3466#issuecomment-659238750

I've closed the associated PR, but it looks like someone may have to solve this by adding a new key in cc_config.xml

**Comment by AenBleidd** [comment]
All the configuration should be passed using the cc_config.xml file.
This is the best and the most convenient way of working with the client settings.
Closing this as "won't fix".
