### ISSUE TITLE
Dynamically allocate cpu ressources to tasks

### ISSUE THREAD

**Issue by Uroc327** [BOINC/boinc#3462]
Some of the ATLAS simulations from LHC@home seem to have a lot of idling time. I have a bunch that were expected to run 1:30 h on 8 cpus, but instead are running over 7 or 8 h. During this additional time, they usually don't produce any cpu load. When this happens, boinc thinks that all of my 8 cpus are occupied, when instead they are pretty much idling. Apparently (after a quick skim through the lhc@home forums) this is also no bug but 'how the application works'.

I would like to be able to either automatically suspend tasks, which are occupying boinc resources without actually doing significant work to require those ressources or alternatively I would like the boinc client to monitor ressources dynamically and to assign new tasks to cpus when it realizes that currently the processor is below the expected load.

**Comment by AenBleidd** [comment]
This tasks requires a lot of changes to scheduler. And I'm not completely sure that this is necessary.
You told that these particular tasks during this additional time don't produce any CPU load. But what do they do all this time? Maybe it takes so long because of I/O requests that load hard drive to 100%? In this case running additional tasks (especially of the same project) can create a big bottleneck and long queue for hard-drive resources.
In any case, before implementation, this should be investigated very carefully because it's too easy to hit worse performance than it was before.

**Comment by RichardHaselgrove** [comment]
I think this issue goes back at least 10 years. I think the 'ATLAS simulations' referred to are running in a VM, where tasks are allocated (or not) by CERN's direct communication with the internals of the VM, bypassing BOINC's scheduler entirely. It is therefore entirely possible for BOINC to think the CPU is busy (VM task allocated and running), but no actual science being performed (CERN has nothing to send to the VM, or CERN <--> VM comms are down). The proposal, in general terms, is for BOINC to be able to recognise an idle condition within the VM, and super-allocate non-VM tasks to use the reource for as long as (but no longer than) the VM is idle.

**Comment by Rytiss** [comment]
CERN VM should use `boinc_temporary_exit()` to exit when it has no work. That would release the CPU to BOINC, but not immediately report and download another WU. The temporary exit duration is also configurable from the app, so if they know they'll only have work in 8 hours, they could exit for those 8 hours, and otherwise exit for like 10 minutes and retry later.

My verdict: this is not a BOINC problem, this is an application problem. BOINC provides mechanisms to deal with such situations.

**Comment by AenBleidd** [comment]
Assuming everything written above, I believe we should just close this ticket as 'Not an issue'.
@Uroc327, if you believe I'm wrong, feel free to reopen this to continue discussion.
Also it would be nice if someone could forward this issue to LHC@home developers.
