### ISSUE TITLE
config.h depends on project_specific_defines.h which is never installed

### ISSUE THREAD

**Issue by brevilo** [BOINC/boinc#3471]
**Describe the bug**
`config.h` [depends](https://github.com/BOINC/boinc/blob/cbcaa407db44627bb0ed8e8526a848d141a426b2/configure.ac#L657) on `project_specific_defines.h` which is never installed in the configured `--prefix` path.

**Steps To Reproduce**
1. `configure` and `make` BOINC using an install `PREFIX`
2.  Build software against BOINC, e.g. using the BOINC API

**Expected behavior**
A successful build

**System Information**
 - OS: macOS
 - BOINC Version: master

**Comment by CharlieFenton** [comment]
I haven't looked at the make files, but I want to point out that if you use configure to create the config.h file it may not work on older versions of OS X, and may not work at all (as implied by this PR.) The Xcode build uses a fixed version of config.h at _clientgui/mac/config.h_, and so should the make file.

**Comment by brevilo** [comment]
So far we have always used configure/make for all of our science app and screensaver builds, consistently across all platforms, incl. macOS. We need to retain that since it's part of our continuous integration and deployment infrastructure. The more workarounds a certain platform requires, the more effort we'll have maintaining releases for it. I suspect other projects have similar issues which is why I think we should try and solve this centrally in order to avoid multiplied efforts downstream. I presume that's more or less the reason [this](https://github.com/BOINC/boinc/pull/3218#issuecomment-533322152) agreement.

**Comment by CharlieFenton** [comment]
>  if you use configure to create the config.h file it may not work on older versions of OS X

@brevio, I certainly understand your need to keep the build methods as similar as possible across platforms. I am just trying to point out potential issues of which you want to be aware. IMO, Apple is terrible about supporting backward compatibility; they show no restraint in deprecating and eventually eliminating APIs.

Just to clarify, I meant that the _generated code_ may not work properly on older versions of OS X. As I understand it, the config / make approach was developed on a model where each user would build most software themselves, on their target computer, from the source files. This starts with running `configure` on that target computer, since `configure` determines the build options by testing what resources are available on that peculiar machine and optimizes the build to run on that particular machine. 

But those resources may not be available on versions of OS X older than the one on the build machine. This is one of the reasons I created a special config.h for Mac builds at _clientgui/mac/config.h_. All that is needed to use this is to put that path ahead of others in the search path, or to put a symbolic link to it where the make file expects to find  _config.h_, and of course just don't run `configure`.

(FWIW, Apple bases their limited approach to backward compatibility on a very different model, using _availability macros_ in its headers.)

**Comment by brevilo** [comment]
> Just to clarify, I meant that the generated code may not work properly on older versions of OS X. [...] But those resources may not be available on versions of OS X older than the one on the build machine. 

I understand that but so far that was never an issue for us. We always build our binaries using the oldest OS versions possible. For x68_64 that would have been 10.6 but the latest code changes in BOINC effectively require 10.8 (not 10.7. as partially stated in the readme) which is what I'm targeting now. As far as I can see this still works as expected - after I fixed the missing files in various places. At least for the screensaver...

**Comment by AenBleidd** [comment]
@brevilo, could be #2662 fixed with your fixes also? Could you please check? If you need help with Travis CI - just push me

**Comment by brevilo** [comment]
I think that's unrelated and Juha appears to already have found the culprit.
