### ISSUE TITLE
Move Mac build instructions to a plain text document

### ISSUE THREAD

**Issue by mcandre** [BOINC/boinc#3527]
**Describe the problem**

PDF's and RTF's are somewhat cumbersome to work with compared to plain text documents, such as Markdown.

**Describe the solution you'd like**

Move the build steps to a plain text document.

**Comment by CharlieFenton** [comment]
I disagree. I believe you are referring to the Mac build instructions. RTD files are very easy to edit with the TextEdit app on Macs, and trivial to then save a copy as a PDF.

The reason I added the PDF version of mac_build/HowToBuildBOINC_XCode.pdf is so that updates to the build instructions will automatically be available via a link from [here](https://boinc.berkeley.edu/trac/wiki/MacBuild). Changing the format will break this.

**Comment by CharlieFenton** [comment]
> PDF's and RTF's are somewhat cumbersome to work with compared to plain text documents, such as Markdown

RTF documents are the default output of the TextEdit app, which is supplied on every Mac in `/Applications/Utilities/`. TextEdit is a WYSIWYG text editing tool and is one of the easiest tools for creating RTF files. And it will automatically convert the file to PDF by selecting either  _File/Export as PDF_ or `Print` from its `File` menu.

**Comment by AenBleidd** [comment]
I don't think this is an important feature.
