### ISSUE TITLE
[Draft] [Android] Convert APK to Bundle

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#3566]
See https://developer.android.com/guide/app-bundle/ for reference.

Main bundle should include BOINC Manager for Android.
Platform dependent executables (BOINC client) should be located in a separate bundle for every architecture supported (ARM, AARCH64, x86, x86-64).

Also platform dependent project executables should be located in a separate bundles.

Add support of downloading necessary bundes on demand:
- client bundles should be downloaded on application start after device architecture was detected 
- project bundles should be downloaded when particular project is added.

Ref:
- https://developer.android.com/guide/app-bundle/play-feature-delivery
- https://developer.android.com/guide/app-bundle/conditional-delivery

**Comment by talregev** [comment]
> Platform dependent executables (BOINC client) should be located in a separate bundle for every architecture supported (ARM, AARCH64, x86, x86-64).

This is not how bundle concept work. from experience. 
You should have **one** bundle file with **all** platforms.
Then you upload to google play store. (You need to change and add new signature). 
Then It will download only the relevant platform to device.
Before you activate the release in the play developer console you can see the size of each platform.
If you put everything in one file, google can do optimization and also you will see that download size will be decrease slightly for each platform. Also more easy for developers to create all platforms and tests it as needed.

**Comment by AenBleidd** [comment]
Your experience will help us! Thank you

**Comment by talregev** [comment]
I compile boinc to bundle.
And I have some interesting and not explain stuff: 

First I remove this line:
`testCoverageEnabled true`
from here:
https://stackoverflow.com/a/56823288/550384

> This will make the APK / App Bundle debuggable, and Google Play Console will consider it's not signed. Removing this resolved the issue.

Then I upload to google play console:
![no_so1](https://user-images.githubusercontent.com/7043539/80850889-17417380-8c27-11ea-890e-f49b65ca29bb.PNG)
![no_so2](https://user-images.githubusercontent.com/7043539/80850898-1e688180-8c27-11ea-90e7-0127ea6ad05f.PNG)

Then I see it not split to the abi, so I did this things:
add this to the code:
```gradle
    sourceSets {
        main {
            jniLibs.srcDirs 'src/main/assets'
        }
    }
```

and change the binaries names to boinc.so and boinccmd.so that android studio will split with abi
Google console now split with abi but
it get a larger file to download and install:
![so1](https://user-images.githubusercontent.com/7043539/80850979-7c956480-8c27-11ea-86b9-1c79fbd9b9cf.PNG)
![s02](https://user-images.githubusercontent.com/7043539/80850982-83bc7280-8c27-11ea-9285-94fa0262367e.PNG)
![s03](https://user-images.githubusercontent.com/7043539/80850985-874ff980-8c27-11ea-912c-660c2dd0daa6.PNG)

Not sure what it the correct way.
Also, is it possible to run binaries with .so extension?

**Comment by AenBleidd** [comment]
.so - is a shared library, while 'boinc' and 'boinccmd' (last one actually is removed from apk in master) are executables.

**Comment by AenBleidd** [comment]
As it was mentioned in the #5338, there is no chance we get back to Play Store.
That means that this ticket is not relevant anymore, since we still should provide our users with APK and can't delegate this functionality to the Play Store.
