### ISSUE TITLE
Feature request: Change device name on windows client. 

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#3587]
**Describe the problem**
A clear and concise description of the problem you're looking to solve.
-->Cannot change or see device name on windows client. (maybe also on mac and linux client).

**Describe the solution you'd like**
-->Please add an option in windows client to change device name, like in android client.

**Additional context**
I am using windows 10 64bit
7.16.5(x64) boinc version.

**Comment by adamradocz** [comment]
On PC BOINC uses the PC name.

**Comment by talregev** [comment]
Why? 
Can you change that? It annoying.

**Comment by talregev** [comment]
> On PC BOINC uses the PC name.

By default it will take computer name, as it doing for years.
But also let user switch the name like you let it in android client. 
Thank you for your help.

**Comment by adamradocz** [comment]
Why do you want a different name than your PC's name? It identifies clearly. If it doesn't, probably you should change the PC name.

**Comment by Ageless93** [comment]
Go to Settings > System > About and select the Rename this PC button.

**Comment by talregev** [comment]
> Why do you want a different name than your PC's name? It identifies clearly. If it doesn't, probably you should change the PC name.

Why you argue with the user? I am using this client on my computer, valuntery give computing time. I see great feature you implemented in android client. I understand all the system already can handle this feature, and it simple task to ask. 
It really annoying me that I cannot give cool name to my pc name. 
No I won't change computer name. It for other things, and also require restart. So?
Do you really want to keep argue about and sting me about this? (Yes I know how to change computer name).
I hope other users will see my issue and vote up for this.

**Comment by RichardHaselgrove** [comment]
If you know your own computer name, that should be enough for identification on a project's website.

Would you really find it significantly cooler if you (and you alone) could see a special BOINC computer name on the website? Computer names are not displayed to other users.

**Comment by talregev** [comment]
> Computer names are not displayed to other users.

It for me only. That what I want. like android device.

**Comment by talregev** [comment]
I am a programer myself. I can help in coding. really. just don't sting me. And help me to help you to do better, cooler and nicer computing distribute client.

**Comment by Ageless93** [comment]
BOINC is open source. If you know how to add the code, you can download the source code, change the code to your liking, compile it and run it that way.

**Comment by Ageless93** [comment]
And before you ask where to get the source code: https://boinc.berkeley.edu/trac/wiki/SourceCodeGit
And how to compile it: https://boinc.berkeley.edu/trac/wiki/CompileClient

**Comment by talregev** [comment]
> And before you ask where to get the source code:

The source code is here. I am not blind.
Can you point me where I can add this functionality?

**Comment by talregev** [comment]
First I want to understand how the android application send the name for the client, to implement the same functionality. 
I see the preference fragment is here. 
https://github.com/BOINC/boinc/blob/master/android/BOINC/app/src/main/java/edu/berkeley/boinc/PrefsFragment.java

Could you point me out where he get the string from the user and send it to the client?

**Comment by Ageless93** [comment]
I am not a programmer. Adam, the person you yelled at, is one of the handful of volunteer programmers we have. I doubt he'll be coming back to this thread seeing how you treated him in the first place. As for adding what code where, why not take the weekend to familiarize yourself with the BOINC code?

**Comment by AenBleidd** [comment]
@talregev, at first, please calm down. We're here trying to help you. If you think (or it really is) that someone is rude to you, this doesn't mean that you need to be rude to anyone.
Second, you are aggring at the person who implemented this feature for Android because it was necessary there. Android client is different from other platforms. Generally you don't need to rename your computer in BOINc because it's really more easy to identify it when it has the same name as in the PC settings.
And the last one, from the top of my head, I don't remember how to change the name. You should look at the commit to Android client made by Adam.
So just take a long breath and then try to search through git log for necessary information. It you'll fall to do this - write me in discord in several hours, I can try to help you.
And just please don't forget, that this could be the feature that nobody except you wants. We, as developers, can't satisfy everyone but as big majority as possible.
And Jord pointed you the the place where to find sources with the reason: BOINC has a lot of dependencies and it is not clear from the first view where to get everything. E.g. you can't build Windows client for now because the repo with dependencies is under maintenance now.
In any case, feel free to contact me directly in discord for further conversation

**Comment by talregev** [comment]
> o just take a long breath and then try to search through git log for necessary information. It you'll fall to do this - write me in discord in several hours, I can try to help you.

Thank you @AenBleidd for your help and discussion. 
Even it more easy to identify you computer along other android client, it really annoying that it take your computer name and you cannot change it. I can give really thousand you shouldn't just rename your computer name, specially it connected to your network configuration, other software and more. 
But it really isn't the point. It really annoying me that i am willing to take the effort and implement this feature. 
I will look it more closely in the next days and also try to compile the boinc in my android studio.
I hope Adam will willingly want to help me too.
If I get in trouble I will publish here for help, also I will contact you. You seems really want to help me.

> E.g. you can't build Windows client for now because the repo with dependencies is under maintenance now.
There isn't stable tag or branch for windows that I can compile and debug?

**Comment by talregev** [comment]
@Ageless93 Sorry I yell at you. I though you trying to mock me. Because I understand that the boinc client is get the device name from computer name, and for now you need to change your computer name for that boinc device name will change.
But I ask for new functionality. That why I do the feature request template and also add Feature request tag in the title. I guess it wasn't clear for you.

Sorry, and I hope you forgive me and we can work together.

**Comment by truboxl** [comment]
See #2908

**Comment by cristipurdel** [comment]
I tend to agree with @talregev . He opened an issue requesting something. If you do not agree close the issue with arguments.
If you have only one PC it is fine to maange. Question is, what happens when you have a lot of PCs?
Or in my case how can I manage all of my 20+ android devices?

> 

MCM1_ 0162103_ 7985_ 0-- | android_bc5652df | In Progress | 4/15/20 09:26:23 | 4/22/20 09:26:23 | 0.00 / 0.00 | 0.0 / 0.0
-- | -- | -- | -- | -- | -- | --
MCM1_ 0162105_ 8744_ 0-- | android_46133121 | In Progress | 4/15/20 09:02:23 | 4/22/20 09:02:23 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162107_ 3366_ 1-- | android_e43bf4e5 | In Progress | 4/15/20 09:00:34 | 4/22/20 09:00:34 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162028_ 9113_ 1-- | android_67f127e6 | In Progress | 4/15/20 08:57:56 | 4/22/20 08:57:56 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162024_ 2695_ 1-- | android_46133121 | In Progress | 4/15/20 08:39:38 | 4/22/20 08:39:38 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162028_ 5539_ 0-- | android_3c6bf479 | In Progress | 4/15/20 08:29:40 | 4/22/20 08:29:40 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162028_ 8800_ 0-- | android_6c10f6cc | In Progress | 4/15/20 08:10:43 | 4/22/20 08:10:43 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162065_ 0823_ 1-- | android_0dcea119 | In Progress | 4/15/20 08:10:07 | 4/22/20 08:10:07 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162016_ 0646_ 1-- | android_5973fbaa | In Progress | 4/15/20 08:02:42 | 4/22/20 08:02:42 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162111_ 7299_ 0-- | android_d00e2497 | In Progress | 4/15/20 08:00:21 | 4/22/20 08:00:21 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162104_ 0253_ 0-- | android_f87cddee | In Progress | 4/15/20 07:45:21 | 4/22/20 07:45:21 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162023_ 0908_ 0-- | android_5d7cf9ef | In Progress | 4/15/20 07:43:18 | 4/22/20 07:43:18 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162023_ 9575_ 1-- | android_d00e2497 | In Progress | 4/15/20 07:32:28 | 4/22/20 07:32:28 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162026_ 9549_ 0-- | android_bc5652df | In Progress | 4/15/20 07:32:16 | 4/22/20 07:32:16 | 0.00 / 0.00 | 0.0 / 0.0
MCM1_ 0162027_ 6606_ 0-- | android_5d703751 | In Progress | 4/15/20 07:24:28 | 4/22/20 07:24:28 | 0.00 / 0.00 | 0.0 / 0.0

But to answer @talregev  directly, as a bypass, you could use boincstats site and rename individual the PCs or use boinc alternative boinctasks, which puts all your PCs in one window for remote access

**Comment by talregev** [comment]
> See #2908

Thanks! that really help. That what I looking for.

**Comment by talregev** [comment]
@AenBleidd 
> E.g. you can't build Windows client for now because the repo with dependencies is under maintenance now.

I download the source code in tag: 7.16.5
https://github.com/BOINC/boinc/tree/client_release/7.16/7.16.5
I notice it still in visutal studio 2013.
In the new tag or version is already 2019?

I will try to compile 2013 sln with 2019 vs.
Thanks for your help.

**Comment by talregev** [comment]
@cristipurdel 
> But to answer @talregev directly, as a bypass, you could use boincstats site and rename individual the PCs or use boinc alternative boinctasks, which puts all your PCs in one window for remote access

I already know that. I already change it in the state. but in the project the names don't change. It annoying me. And I already working to change that.

**Comment by AenBleidd** [comment]
VS2019 is in master. If you want to create a PR with new feature I recommend to do this basingbon master branch

**Comment by truboxl** [comment]
I really think we should just allow people to override hostname using `cc_config.xml` like what was suggested in https://github.com/BOINC/boinc/issues/3337 so all platforms can do this...

**Comment by talregev** [comment]
@AenBleidd 
> VS2019 is in master. If you want to create a PR with new feature I recommend to do this basingbon master branch

> E.g. you can't build Windows client for now because the repo with dependencies is under maintenance now.

Can I compile / build windows client on master?

**Comment by talregev** [comment]
> I really think we should just allow people to override hostname using `cc_config.xml` like what was suggested in #3337 so all platforms can do this...

I will implement this feature as easy I can, then other people will improve it.

**Comment by AenBleidd** [comment]
@talregev, yes, you can.

**Comment by talregev** [comment]
> @talregev, yes, you can.

Super easy to compile!

**Comment by talregev** [comment]
@AenBleidd 
I already implement the gui part for device name.
I need some help with asyncRPC. It not clear from first glance how you put new parameters there. 
Question:

1. Should I create a new branch from master?
2. To Which branch I should do pr when I finish?
3. I want to push my code and you can look on it. It not complete. Can you look and suggest where in the asyncRPC or other place I should add device name?

**Comment by talregev** [comment]
In advance view:
![advDeviceName](https://user-images.githubusercontent.com/7043539/79700345-a355b180-829d-11ea-94df-3d013a68eb5f.PNG)

**Comment by davidpanderson** [comment]
I agree with @truboxl.  The device name should be set in cc_config.xml if desired.

**Comment by AenBleidd** [comment]
@talregev,
1 - Yes
2 - master
3 - Yes

I agree with David, this should be done via cc_config.xml file. This windows is not a correct place for this feature.

**Comment by talregev** [comment]
I do it symmetric to Android config. Also I like it there.
After I will do my change you can add it to the xml.

**Comment by AenBleidd** [comment]
Android is different. Logically this setting doesn't fit any tab in this window

**Comment by talregev** [comment]
@AenBleidd 
Please open the issue.
The fix is not implement my request. 
My request is change device name via GUI.

**Comment by AenBleidd** [comment]
@talregev, please read these comments:
- https://github.com/BOINC/boinc/issues/3587#issuecomment-616232871
- https://github.com/BOINC/boinc/issues/3587#issuecomment-616237873
- https://github.com/BOINC/boinc/issues/3587#issuecomment-616243508

**Comment by talregev** [comment]
@AenBleidd 
I will open another one.
