### ISSUE TITLE
AppKit Mac app

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3645]
Is there any interest in moving BOINC Manager for macOS to a native [AppKit](https://developer.apple.com/documentation/appkit) app? It would not only be faster and [more familiar](https://developer.apple.com/design/human-interface-guidelines/macos/overview/themes/) to Mac users, but I think Mac developers would be more likely to contribute if that was the stack used.

**Comment by CharlieFenton** [comment]
> Is there any interest in moving BOINC Manager for macOS to a native AppKit app? 

Currently, all platform (OS) implementations of BOINC Manager (except Android) use a shared code base. Using as much cross-platform code as possible reduces the maintenance effort significantly, and helps keep the various OS implementations in sync. To that end, it uses the wxWidgets cross-platform library.

BOINC Manager already is a native AppKit app, as it uses the Cocoa version of wxWidgets. Where necessary to be Mac-specific, there is also custom Cocoa code. The cross-platform part is written in Unix code. Since MacOS and Cocoa are built on top of BSD Unix, that code is perhaps even more efficient than Appkit / Cocoa.

I agree that a version written from the ground up in Cocoa would likely be more efficient than using wxWidgets, but then the substantial contributions from the many non-Mac BOINC developers would no longer apply to the Mac version. That is the trade-off.

**Comment by davidpanderson** [comment]
For the reasons Charlie cites, we'd want any new GUI to be cross-platform.  One possibility is frameworks based on Web technologies, such as Electron.

**Comment by AustinConlon** [comment]
As a user I'd prefer that it not use Electron because of how disconnected the experience would be from the HIG linked, keeping as much code sharing between platforms is pragmatic. Thank you for the reasoning Charlie, and for your contributions to the Mac app! I just realized that Retina display support is here, it makes a huge difference.
