### ISSUE TITLE
[Win] Auto-update

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3809]
**Describe the problem**
I run the Boinc on a few computers and it's a little bit tedious to update the Boinc on them one-by-one. An auto-update feature would be awesome, not just the notification.

**Additional context**
The security was the concern in the past, but it can be solved like that:
- Check if a new version is available.
- Download the installer's hash code via HTTPS connection.
- Download the installer via HTTP connection, so it can be cached if needed.
- Validate the downloaded installer with the hash code.
- If OK, install the new version.

**Comment by AenBleidd** [comment]
Auto-Update ist not good in case when you run longrunning tasks that have no checkpoints. Also it affects in not a good way VM tasks when force-stop could make a incorrect checkpoint state and VM will not run again after BOINC relaunch

**Comment by RoboticMind** [comment]
Maybe something like how browsers do it where it will download the update automatically buy only update when you restart?

**Comment by Ageless93** [comment]
I don't want auto-update because the bleeding edge isn't always better than what I have installed. I decide when updates come in, be it for Windows or for software, so I can wait it out if there are problems with the updates before I add them. Case in fact, I allowed Firefox to install its newest update, since that time the Live video stream at the Roosterteeth.com is broken, its loading will crash FF completely.

**Comment by RoboticMind** [comment]
Maybe something like how ChromeOS updates with an A/B system? Run only on copy A or copy B and when you want to update, update the opposite copy and launch from there. If something goes wrong, you can launch back from the old copy.

**Comment by AenBleidd** [comment]
> Maybe something like how ChromeOS updates with an A/B system? Run only on copy A or copy B and when you want to update, update the opposite copy and launch from there. If something goes wrong, you can launch back from the old copy.

It's an additional and not needed complexity

**Comment by adamradocz** [comment]
> I don't want auto-update because the bleeding edge isn't always better than what I have installed. I decide when updates come in, be it for Windows or for software, so I can wait it out if there are problems with the updates before I add them. Case in fact, I allowed Firefox to install its newest update, since that time the Live video stream at the Roosterteeth.com is broken, its loading will crash FF completely.

It can be optional and not forced.

**Comment by Ageless93** [comment]
It is now optional and not forced. I now decide if I want to download and install the update. 
The moment you allow the software to download automatically, at one point it will need to be installed. Else there will be a nagging message - with annoying pop-up - about not having updated the software yet. Or the update happens at a next BOINC exit & restart because someone deemed that a good solution. 

I understand the want for auto-update, especially in light of problems with communications certificates and such. But I also think that things like that need to be kept up to date, that we need a couple of people who keep an eye on these things and update them before they can cause mass problems for everyone. An auto-update of BOINC isn't the fix here. 

Plus that will only affect those that chose to install the first version of the software with the auto-update function built in. Because you can't force people to install it. 
And I foresee the problem that if there is a version with a problem within the auto-update range, that the people who find they have a problem with it and they return to a previous version find that it will auto-update again overnight. It's a can of worms we may not want to open.

**Comment by HassanAbouelela** [comment]
> The moment you allow the software to download automatically, at one point it will need to be installed.

I think that's where the optional part comes in. Provide a toggle to auto download updates and apply changes on exit/launch/no active tasks as one option, and the current system as the other option. This gives you the best of both worlds as an end-user. If you want peace of mind, let the software do its thing, and if you want complete control, you can get it.

**Comment by AenBleidd** [comment]
This option will give more negative experience to the new and existing users rather than helping them.
BOINC has not so much updates during the year, so I don't see any positive valuable output of it.
Closing this as 'wontfix'

**Comment by adamradocz** [comment]
How come keeping the software up to date is a negative experience?

**Comment by AenBleidd** [comment]
Making Auto-Update and breaking running tasks is a negative experience.
When new version is released, notice in Manager is shown.

**Comment by adamradocz** [comment]
Why would brake it? The normal update doesn't brake them either.

**Comment by AenBleidd** [comment]
Currently update is done manually, so when the users do an update, they do this when it's the most convenient for them. Sometimes long running tasks should not be interrupted, and users wait until it's finished before doing update. Also, as I already wrote above, BOINC is releases just couple of times a year, so this is fine to not have Auto-Update.

**Comment by adamradocz** [comment]
Convenience doesn't change based on the repetition. If something can be done better, then it's better doesn't matter how many times do you want to do it per year.

New version comes out -> Auto download -> Promop the user: "Do you want to install now or on the next restart?"

I don't see, how ever this process is inconvenient or a negative experience.

**Comment by AenBleidd** [comment]
Ok, imagine next. Client is on the Linux, Manager is on the other machine on Windows. New version is released. Users see this on windows. How you suggest to execute remotely 'sudo apt-get install' to update remote client?

**Comment by adamradocz** [comment]
Differnt platform, different behaviour.

**Comment by AenBleidd** [comment]
That is why it doesn't worth to spend time on it now and keep this ticket open. Later we can get back to it and try to make a proper design that will provide a clear and understandable process for our users.
