### ISSUE TITLE
BUG: Boinc icon in the dock is replaced by an placeholder in an Ubuntu 20.04 wayland session

### ISSUE THREAD

**Issue by jakobjakobson13** [BOINC/boinc#3810]
**Describe the bug**
The boinc icon in the dock is replaced by an placeholder on an Ubuntu 20.04 wayland session.
![Bildschirmfoto vom 2020-06-07 13-55-05](https://user-images.githubusercontent.com/43045863/83968197-b4976380-a8c7-11ea-8e3a-c01b9dd6631f.png)
In the Ubuntu 20.04 x11 session the icon looks like it should.

**Steps To Reproduce**
1. Install boincmgr
2. Check icon of boincmgr in the dock by starting boincmgr in a wayland and in a x11 session

**System Information**
 - OS: Ubuntu 20.04 wayland session
 - BOINC Version: 7.16.6

**Comment by talregev** [comment]
We should unify the icons for all platforms.

**Comment by musicinmybrain** [comment]
This also happens in Fedora 32 under GNOME/Wayland. It is probably related to [gnome-shell #1779](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1779), in which gnome-shell has trouble matching the running application with the desktop file. Qt applications ([Lyx](https://www.lyx.org/trac/changeset/dc5eda84/lyxgit), [Spyder](https://github.com/spyder-ide/spyder/pull/13787/files)) can be fixed by calling QGuiApplication.setDesktopFileName; I am not sure what the right solution is for a GTK application.

**Comment by musicinmybrain** [comment]
[Here](https://gitlab.com/inkscape/inkscape/-/issues/539) is the discussion from the same issue on Inkscape.

On Fedora 32, the launcher is called `boinc-manager.desktop` but the executable is called `boincmgr`. Since upstream does not supply a `.desktop` file, this should probably be considered a downstream packaging bug. It seems downstreams should either use the name `boincmgr.desktop`, or patch in a call to `g_set_prgname()`.

**Comment by musicinmybrain** [comment]
I opened Fedora downstream issue [RHBZ #1880553](https://bugzilla.redhat.com/show_bug.cgi?id=1880553).
