### ISSUE TITLE
Support semantic versioning for applications

### ISSUE THREAD

**Issue by ChipWolf** [BOINC/boinc#3854]
**Describe the problem**
Currently, application versions are validated as MINOR.PATCH

**Describe the solution you'd like**
Allow use of [Semantic Versioning](https://semver.org/) for applications

**Additional context**
Semantic Versioning is increasingly common in the development community and is the direct result of sets of standards working together.
As an example, our projects enforce the use of [Conventional Commits](https://www.conventionalcommits.org/). In turn, this is used by [semantic-release](https://semantic-release.gitbook.io/semantic-release/) which automates the whole package release workflow including determining the next version number, generating the release notes and publishing the package.

We currently have to make accommodations for BOINC application versions by concatenating MINOR and PATCH, and stripping any additional metadata as defined in the SemVer spec (examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.). Removing these features of our versioning reduces readability and adds a potential error overhead to this process.

**Comment by AenBleidd** [comment]
BOINC has an application versioning system that is stable for more than two decades.
While semantic versioning looks interesting, however its implementation might break a lot of stuff, and since this is not a blocker (any non-BOINC-compliant version could be changed with a little script to something more BOINC-friendly, we're not going implement and support this functionality.
