### ISSUE TITLE
macOS Big Sur icon

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3875]
It would be nice for macOS Big Sur to have an app icon more consistent with the system's app icon design style: https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/.

**Comment by CharlieFenton** [comment]
Thank you for the suggestion, but I feel differently. This is similar to #2468, with which I also disagreed. As I wrote there, I strongly dislike the "modern" flat icon style Apple currently uses. I strongly prefer the "shiny" 3-dimensional look of our current Mac icons, which were donated to us by an excellent professional graphic designer, though I realize that it is largely a matter of personal taste. I also don't feel the need or desire to blend in with the system app icons; I like the idea of being distinctive.

To tell the the truth, I get rather annoyed by Apple's (and other software companies') making superficial changes in appearance. I feel that in many cases, these modifications are driven by marketing so that consumers can demonstrate that they own the latest version as a status symbol.

**Comment by CharlieFenton** [comment]
Thanks for the helpful information.
> Also, many of their Big Sur icons have elements that go back to photorealistic design away from being "flat."

I didn't realize that Apple had changed icon designs yet again for OS 11. That is interesting. The Apple article you referenced starts out:
> macOS 11 introduces
And I misinterpreted that as OS 10.11, so I thought it was an older document. I had not realized that Apple has finally given up on the OS 10.xx numbering scheme along with changing the name _OS X_ to _MacOS_. "

> I think the modification is driven more by Apple trying to make the design familiar to users context switching from one of their other OSes to macOS.

For what it's worth, that concern is somewhat moot for BOINC. It seems unlikely we will ever have a BOINC port to iOS because the way BOINC works violates too many of the iOS App Store guidelines (downloading project executables and running them silently in the background, to name just one issue.)

> A balance can be struck if a graphic designer is interested in trying

Unfortunately, we have lost touch with the icon designer who donated our current icons in 2007.

**Comment by AenBleidd** [comment]
Looking at the icons on the article above, I'd say icon from #2468 would fit just perfectly

**Comment by CharlieFenton** [comment]
@AustinConlon On a different but related topic, are you in a position to test the current release of BOINC under Big Sur MacOS 11 beta? I would  be especially interested to know if the BOINC screensaver works properly, as we've had to implement a number of rather convoluted techniques to make it work under MacOS 10.15 Catalina. If you want more information about these techniques, see PRs #2149, #2294, #2726, #3369, #3631, #3369 and #3667.

Also, your issue #3867 brought up the same matter as my issue #3827. If you have installed the Xcode 12 beta and would be interested in taking on the updating of BOINC's Xcode project to support _x86_64 / Apple Silicon_ Universal Binaries, that would be a great help to the project. Perhaps the biggest challenge will be in revising the build scripts for the dependent libraries to build Universal Binaries. I offer some suggestions in the comments, including referring to older versions of these build scripts when they built _x86_64 /  i386_ Universal Binaries.

Another concern is that some parts of the Mac-specific BOINC code still use long deprecated APIs. This is especially true of the accessibility code in `clientgui/mac/MacAccessibility.mm`, which is based on [this](https://developer.apple.com/library/archive/samplecode/ImageMap/Introduction/Intro.html) and it's [slightly newer](https://developer.apple.com/library/archive/samplecode/ImageMapExample/Introduction/Intro.html) version.

I am retired from software development and have been stepping down from involvement with BOINC, so I would rather not download and install Apple's beta software. But I am more than happy to help you or any other Mac developer take over BOINC support by answering questions and by pointing to relevant parts of the code.

**Comment by AustinConlon** [comment]
@CharlieFenton Yes, so far I've just been running BOINC on Big Sur and it works, but I haven't tested screensavers and I'll report back if there are issues. I also have yet to respond to your reply about a Spotlight issue. I don't have an ARM Mac development kit, but I'll see where I can contribute on x86. Thanks for offering guidance about the codebase, I'll send any questions your way.

**Comment by CharlieFenton** [comment]
> Looking at the icons on the article above, I'd say icon from #2468 would fit just perfectly

Yes, that is the flat icon style I was referring to in my earlier comment, which I dislike. I much prefer the current one, which you can see [here](https://en.wikipedia.org/wiki/File:BOINCManager.png), along with some very early BOINC icons.

**Comment by CharlieFenton** [comment]
@AustinConlon Thank you, that is good to know. I've started a new issue #3876 for this. Let's continue the discussion there.

**Comment by CharlieFenton** [comment]
@AenBleidd I don't think the icon in #2468 fits Apple's new app design guidelines (and neither does the current BOINC Manager icon on Mac, Windows or Linux -- I don't know what the Android icon looks like.) I believe the key sentence in the referenced document is:
> App icons combine a rounded-rectangle shape, a front-facing perspective, and a consistent drop shadow to provide a unified visual experience.

BOINC's icons do have neither the rounded-rectangle shape nor the drop shadow.

**Comment by talregev** [comment]
You mean Big and flat like this? 
![BOINC_1](https://user-images.githubusercontent.com/7043539/86496170-c6fca400-bd84-11ea-9830-150c6f80aa79.png)

**Comment by talregev** [comment]
> Looking at the icons on the article above, I'd say icon from #2468 would fit just perfectly

I vote up for this icon as well. to make all our client with this icon.

**Comment by CharlieFenton** [comment]
> You mean Big and flat like this?

 I am vehemently opposed to replacing the beautiful current Mac icon to that ugly flat one. 

> I vote up for this icon as well. to make all our clients with this icon.

I support changing all our clients to use the [current Mac icon ](https://en.wikipedia.org/wiki/File:BOINCManager.png).

**Comment by davidpanderson** [comment]
I support whatever Charlie supports - although the center of the icon
does look disturbingly like an egg yolk.
