### ISSUE TITLE
[Manager] Don't show dialog 'Shut down connected client' option not applied if pressed when no client connected

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#3933]
**Describe the bug**
Option changes its state when no client connected

**Steps To Reproduce**
1. Shutdown connected using corresponding menu option
2. Check there a checkbox 'Don't show this dialog again'
3. Press cancel when asked to connect to client
4. Try to 'Shutdown connected client' again
5. Repeat 3-4 couple of times

**Expected behavior**
Dialog is never shown again

**System Information**
 - OS: Windows x64
 - BOINC Version: 7.16.7

**Comment by CharlieFenton** [comment]
This has nothing to do with whether or not the client is connected. By design, the checkbox settings are saved only when you click _OK_. Clicking _Cancel_ ignores anything you have changed in the dialog. The same is true for any dialog, such as the _Other options_ dialog.

**Comment by AenBleidd** [comment]
Yes, but this is a misleading behavior. This dialogue should not be shown. And Ither options are related to Manager behavior, not client

**Comment by CharlieFenton** [comment]
I agree that the behavior can be confusing, but changing settings when the user clicks on _Cancel_ is definitely wrong. The better solution might be to add an _Apply_ button. 

You don't need to actually exit the Manager to disable the exit dialog; you can accomplish that by unchecking the "Enable manager exit dialog?" checkbox in the _Other options_ dialog. I understand that doesn't satisfy your concern, though.

**Comment by RichardHaselgrove** [comment]
Please refer to my #3187 - there are times when you need to use the options dialog with no client connected. Some outcomes are saved as local machine configuration changes, not in the client files.

I agree that in general, clicking a 'cancel' button should leave the machine state unchanged. There are difficulties where multi-tab dialogs are concerned - 'property pages', in the Windows jargon. Changing a value on one page, switching to another tab to check another value, seeing that the second value is correct, clicking 'cancel' - leaves you where, exactly?

This is where 'Apply' buttons can be helpful, and so can confirmation alerts "You have unsaved changes - discard them?"

**Comment by AenBleidd** [comment]
@CharlieFenton,
No, it's a differrent window:
![image](https://user-images.githubusercontent.com/3234209/87936631-762ec000-ca93-11ea-942e-a8104e46cfa8.png)

**Comment by dbareis** [comment]
> This has nothing to do with whether or not the client is connected. By design, the checkbox settings are saved only when you click _OK_. Clicking _Cancel_ ignores anything you have changed in the dialog. The same is true for any dialog, such as the _Other options_ dialog.

This is not what is happening, its the FOLLOWING dialog which is cancelled, not the one with the checkbox.  

Other than that I can see both sides of the argument, personally I believe that if I have ticked it I don't want to see it whether or not I cancel that dialog.  Microsoft and many others seem to disagree with me.

**Comment by CharlieFenton** [comment]
@AenBleidd I know it's a different window. I was just pointing out that there is a different way to disable the exit dialog without shutting down the client.

**Comment by delta1513** [comment]
Posting my debugging findings here so I can work on it later.

[AdvancedFrame.cpp L1352](https://github.com/BOINC/boinc/blob/master/clientgui/AdvancedFrame.cpp#L1352) has some undocumented logic that makes use of a short circuit evaluation.

1. When `showDialog=1`, the dialog is set up and styled and such, and then because the first operand to the or statement on L1352 is now `!showDialog=0` ...  `dlg.ShowModal()` is called and the modal runs as intended, the checkbox is set by the user if they want and the value is saved.

2. When `showDialog=0`, no modal styling is performed and the short circuit evaluation skips the call to `dlg.ShowModal()` ... unfortunately, the checkbox value is saved here whenever this if-statement is called and it is setting either an unknown value or 1 which then reverses the original check of the box.

**Comment by delta1513** [comment]
I should note that my change simply fixes the "I told it to not show again and it did" issue. I have not made it so that you can reverse the checking of the box and have left that to further discussion or commits here.

**Comment by CharlieFenton** [comment]
> unfortunately, the checkbox value is saved here whenever this if-statement is called and it is setting either an unknown value or 1 which then reverses the original check of the box.

This is not correct. 

The value of the checkbox is initialized to _false_ in line 113 of `DlgGenericMessage.cpp`, because the _CDlgGenericMessage_ constructor is called from `AdvancedFrame.cpp` line 1315. If _showDialog_ is true, then line 1353 saves the value from the dialog. If _showDialog_ is _false_ then the value _false_ is saved. Since _showDialog_ was _false_ only when the saved checkbox value was _false_, that preserves the correct value.

**Comment by CharlieFenton** [comment]
I just realized this PR refers to a different shutdown dialog than I thought. I had thought the topic was the exit dialog when you shut down the Manager, which has a checkbox asking whether to also shut down the client, and a "don't show this dialog again" checkbox. Sorry for my confusion.
