### ISSUE TITLE
Web API should migrate away from MD5

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3993]
https://boinc.berkeley.edu/trac/wiki/WebRpc#lookup_account

MD5 is cryptographically broken.

**Comment by tomasbrod** [comment]
The field in client state is 256 bytes long. Subtracting the userid prefix (for weak auth) and null terminator, leaves enough space for sha512. I think this could be done entirely server-side, so I suggest to remove client tags.

**Comment by efmer** [comment]
I'm working on Boinc for Android and implemented AES/GCM/NoPadding on Boinc for Android and BoincTasks for Windows.
In this case it was actually better (and easer) to move the calls to Android app and handle it in Kotlin.

**Comment by tomasbrod** [comment]
@efmer , we do not need a cipher, a has function is needed here. Or maybe MAC function, not sure (they are almost the same).

**Comment by efmer** [comment]
A MAC function isn't feasible, most OS make it impossible for an app/program to read the MAC address.
If it's still possible they will probably remove it later-on.
But even if you could, a MAC can be faked.

**Comment by tristanolive** [comment]
The MAC in question is a message authentication code, which is very different than a MAC address. This is similar to a hash, such as MD5 or SHA256, but makes use of a private key in order to provide authentication--explicitly so that it cannot be faked or used by a third-party in the way that a hash could be. (See https://security.stackexchange.com/a/30585 for further explanation).

Whether a hash or MAC function is more appropriate for web API fields depends on the application. If it's a field that is being used for authentication to the API, MAC could make more sense (in theory, at least).

**Comment by AenBleidd** [comment]
This change will make incompatible old clients and old servers.
It is too risky to do that, especially without RPC protocol versioning.

**Comment by AenBleidd** [comment]
And this could be done if/when we decide to upgrade our RPC protocol.
Currently there are no such plans, and md5 is definitely not the strongest argument to start this process.
That is why there is no reason to keep this ticket open

**Comment by davidpanderson** [comment]
The vulnerability is that you can find collisions, not that you can invert it.
All we care about is non-invertible.
