### ISSUE TITLE
Add "rocm" app plan

### ISSUE THREAD

**Issue by clemej** [BOINC/boinc#4049]
**Describe the problem**
I'd like to roll out ROCm support for MLC@Home's client as well as CUDA.  Since it uses PyTorch, it actually need ROCm, (HIP variety) and not just the OpenCL support.  I don't think this is covered under any existing AppPlans listed on the wiki
https://boinc.berkeley.edu/trac/wiki/AppPlan .  So if I do roll it out, I'll have to make a project specific app plan and have users hand-configure their client. 

**Describe the solution you'd like**
I'd like  there to be a standard "rocm" app plan, alongside "cuda' or "wsl" or "opencl" or "amd"

**Additional context**
There are valid arguments here: First, ROCm is currently Linux only, and only some AMD cards (MI line, VEGA, some POLARIS).  But AMD has committed to "CDNA" compute-focused architectures in the future, so hopefully they'll continue to grow. Still, there's a risk the numbers aren't high enough to support an official app plan. Fortunately, ROCm doesn't require any special drivers.. anyone with one of these cards and a modern linux kernel (4.18+?) will "just work" with an app that ships with the ROCm libraries (or they're installed on the system).  Finally. there are a not-insignificant number of high performance systems coming with AMD GPUs. 

There's also *so many* ati/amd app plans already, adding another probably isn't desirable. Still, they all seem to be different.  CAL is not ROCm is not OpenCL. 

Just wanted to make the suggestion here and open the discussion.

**Comment by Rytiss** [comment]
If it does not require any special drivers, you can create a custom plan class listing supported cards, using `host_summary_regex`, something similar to this:

```
        <host_summary_regex>CUDA\|GeForce (GT 640|GTX 550 Ti|GTX 560|GTX 570|GTX 580|GTX 650|GTX 660|GTX 760|GTX 770|GTX 780)</host_summary_regex>
```

Use https://boinc.berkeley.edu/trac/wiki/AppPlanSpec the XML file to specify the plan class.

**Comment by Germano0** [comment]
Test made on a new machine using lastest [4071 patch](https://src.fedoraproject.org/rpms/boinc-client/blob/f33/f/4071.patch)
Build [boinc-client-7.16.11-3.fc33](https://bodhi.fedoraproject.org/updates/FEDORA-2020-df51b3e029)

```
# ls -lah /etc/boinc-client
totale 4,0K
drwxr-xr-x. 1 root root   34 12 nov 09.54 .
drwxr-xr-x. 1 root root 4,7K 12 nov 11.57 ..
-rw-r--r--. 1 root root   25 11 nov 21.53 config.properties
```

```
# ls -lah /var/lib/boinc
totale 96K
drwxr-xr-x. 1 boinc boinc  460 12 nov 15.11 .
drwxr-xr-x. 1 root  root   748 12 nov 09.55 ..
-rw-r--r--. 1 boinc boinc  51K 12 nov 09.55 all_projects_list.xml
-rw-r--r--. 1 boinc boinc 3,4K 12 nov 15.11 client_state_prev.xml
-rw-r--r--. 1 boinc boinc 3,4K 12 nov 15.11 client_state.xml
-rw-r--r--. 1 boinc boinc  300 12 nov 11.50 coproc_info.xml
-rw-r--r--. 1 boinc boinc  119 12 nov 15.11 daily_xfer_history.xml
-rw-r--r--. 1 boinc boinc 8,9K 12 nov 11.51 get_current_version.xml
-rw-r--r--. 1 boinc boinc 1,4K 12 nov 11.51 global_prefs.xml
-rw-r-----. 1 boinc boinc   32 12 nov 09.55 gui_rpc_auth.cfg
-rw-r--r--. 1 boinc boinc    0 12 nov 11.50 lockfile
drwxrwx--x. 1 boinc boinc   18 12 nov 15.10 notices
drwxrwx--x. 1 boinc boinc    0 12 nov 15.11 projects
drwxrwx--x. 1 boinc boinc    2 12 nov 11.51 slots
-rw-r--r--. 1 boinc boinc    0 12 nov 09.55 stderrgpudetect.txt
-rw-r--r--. 1 boinc boinc  204 12 nov 11.50 stdoutgpudetect.txt
-rw-r--r--. 1 boinc boinc  958 12 nov 13.24 time_stats_log
```

```
# cat /etc/boinc-client/config.properties 
data_dir=/var/lib/boinc
```

```
# cat /var/lib/boinc/gui_rpc_auth.cfg 
7189be8ab3965ba4ea5a1000328107ed
```

# user A, in boinc group
## boinccmd
```
$ boinccmd --passwd 7189be8ab3965ba4ea5a1000328107ed --project_attach https://lhcathome.cern.ch/lhcathome key_censored
```

project attached even if client password was not provided

## boinc-manager
after opening it, it connects to the client without and user action required. No password has been provided

# user B, not in boinc group

## boinccmd

### test 1
```
$ boinccmd --passwd 7189be8ab3965ba4ea5a1000328107ed --project_attach https://lhcathome.cern.ch/lhcathome key_censored
Can't get RPC password: /var/lib/boinc/gui_rpc_auth.cfg exists but can't be read.  Check the file permissions.
Only operations not requiring authorization will be allowed.
```

despite the error, the project has been be attached anyways.

### test 2
Removed the project, and tried with no passoword

```
$ boinccmd --project_attach https://lhcathome.cern.ch/lhcathome key_censored
Can't get RPC password: /var/lib/boinc/gui_rpc_auth.cfg exists but can't be read.  Check the file permissions.
Only operations not requiring authorization will be allowed.
Operation failed: authentication error
```

No project attached as expected

### test 3

Tried with a wrong client password
```
$ boinccmd --passwd s7189be8ab3965ba4ea5a1000328107ed --project_attach https://lhcathome.cern.ch/lhcathome key_censored
Can't get RPC password: /var/lib/boinc/gui_rpc_auth.cfg exists but can't be read.  Check the file permissions.
Only operations not requiring authorization will be allowed.
Authorization failure: -155
```

No project attached as expected


## boinc-manager
After opening it, you will get error
```
/var/lib/boinc/gui_rpc_auth.cfg exists but can't be read.  Check the file permissions.
```

then you can select a computer from File->Select computer, enter localhost and the password and manage the client without problems

# My personal conclusions
Since:
- if an user is in boinc group, he can manage the client without providing any password;
- if an user is not in boinc group, he must provide the password contained in `/var/lib/boinc/gui_rpc_auth.cfg` in order to manage the client password;

the admin could simply add the user to boinc group instead of having to use the password contained in `/var/lib/boinc/gui_rpc_auth.cfg`

**Comment by clemej** [comment]
I think I've got it mostly working, so I'm going to close this issue, although I may need some help offline with regex's, and there's another bug I'm about to open due to the kernel OS number not parsing the string correctly, so "min_os_version" doesn't work on Linux.
