### ISSUE TITLE
Mac: New universal BOINC client breaks CPU feature detection

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#4137]
**Describe the bug**
From Einstein server log posted on [BOINC message board](https://boinc.berkeley.edu/forum_thread.php?id=14047&postid=102391#102391)
```
2021-01-03 19:48:16.5251 [PID=7492 ] [version] Checking plan class 'FGRPSSE'
2021-01-03 19:48:16.5252 [PID=7492 ] [version] CPU [' '] lacks feature ' sse '
```

**Steps To Reproduce**

User reports:
> I've been running einstein@home on my 12Z Mac mini. Using the BOINC universal build, I never get any new wu's. Using a non-universal BOINC does get me FGRPSEE wu's, which in general validate fine. Am I not getting new wu's from the BOINC universal build because I have a 12Z, and not a M1?

**Additional context**
This may require @CharlieFenton and @bema-aei to liaise and tweak the 'universality' of the new Apple silicon handling.

**Comment by CharlieFenton** [comment]
As far as I know, SSE is available only on Intel Chips. [This web page](https://simd-everywhere.github.io/blog/2020/06/22/transitioning-to-arm-with-simde.html) says:
> Arm CPUs do have support for SIMD, but instead of Intel technologies like SSE and AVX, Arm has NEON. NEON is an improvement over the x86 APIs in a lot of ways, and a regression in others, but it is undeniably different and you can’t just recompile your application on Arm and expect it to work.

Since arm64 processors do not support SSE, BOINC's feature detection is correct when it does not detect SSE. However, BOINC's code _does_ need to be updated to detect which arm64 features (such as NEON) are available on Apple Silicon processors. While BOINC already has code to detect arm64 CPU features for Linux and Android computers, the corresponding code needed for Macs will be completely different from those operating systems. Doing that is totally outside my area of knowledge, which is why it is not yet implemented.

MacOS 11 include Rosetta 2, which translates Inel instructions into arm64 code. I don't know if Rosetta 2 can handle Intel code containing SSE instructions. This question is asked but not answered [here](https://developer.apple.com/forums/thread/652140).

But [this website](https://eclecticlight.co/2020/09/12/what-could-go-wrong-with-apps-on-big-sur-and-apple-silicon/) says:
> The built-in Rosetta 2 instruction translation feature on Apple Silicon Macs doesn’t work for specialist vector features including Intel SSE, AVX, AVX2, or AVX512 units. If you use high-end software which could use those, check with the vendor before committing to using an Apple Silicon Mac. At worst, your expensive software may not run at all on its ARM processors.

**Comment by CharlieFenton** [comment]
I suggest creating a new issue "Add feature detection for Apple Silicon processors." As I wrote above, that is not something I know how to implement.

**Comment by RichardHaselgrove** [comment]
Thanks, Charlie. That Rosetta 2 comment certainly puts a spanner in the works, especially for projects.

But I've been pointed to this apple.stackexchange thread ([question](https://apple.stackexchange.com/questions/359644/what-replaces-x86-intrinsics-for-c-when-apple-ditches-intel-cpus-for-their-own-c) and [answer](https://apple.stackexchange.com/questions/359644/what-replaces-x86-intrinsics-for-c-when-apple-ditches-intel-cpus-for-their-own-c/407282#407282)), which suggests that a relatively simple mapping from SIMD to Neon may be available.

I think an experienced project like Einstein might be best placed to evaluate that idea. They already have Apple [applications](https://einsteinathome.org/apps.php) for intel and (still!) PPC, and they also have applications for Android on ARM, including for Neon. I'll try to reach out to Bernd and @brevilo, who is (I think) their Apple specialist.

But I think that's about as far as I can go. As usual, I'm merely a messenger, drawing developer attention to user feedback where it seems to be important. I haven't (personally) worked in a Mac environment since System 7 days, so I would just be in the way.

**Comment by brevilo** [comment]
Quick note: we going to look into all-things-m1 as soon as we receive the required hardware (already ordered) and find the time 👍 

Cheers

**Comment by RichardHaselgrove** [comment]
Ta - that saves me a couple of PMs.

**Comment by CharlieFenton** [comment]
> But I've been pointed to this apple.stackexchange thread (question and answer), which suggests that a relatively simple mapping from SIMD to Neon may be available.

It is worth noting that this approach requires modifying and recompiling the project source code. Rosetta 2 still cannot translate Intel executables which use SSE  to run on Apple Silicon, and so this is not a solution for the original concern of wanting to be able to run existing Intel projects on Apple Silicon machines..

**Comment by bema-aei** [comment]
Hi!

I would suspect that the "universal BOINC client" is actually a "fat"
binary, which has binaries native for both ARM and Intel (x86)
architecture. When run on an Intel Mac as in the post Richard reported,
the x86 code should be ran, it should detect and report the SSE
capability of the CPU. That it doesn't do this is now is a bug in the
BOINC Client (x86 code) that to me looks independent of all ARM SIMD
features, ARM code or Rosetta x86 emulation.

The new Apple ARM Chips probably can't run x86 project apps that require
even a minimum of SIMD (SSEx, AVX, probably not even MMX). I'd bet that
a lot of project apps silently require at least SSE (I think on modern
gccs that's even the default floating-point unit to use), i.e. they are
just assuming at least a Pentium3, without even checking for that CPU
capability via a plan class. Thus we should think carefully whether we
would want to publish the "x86(_64)-apple-darwin" platform as an
alternative BOINC platform  on these machines. Due to the very limited
capabilities of Rosetta 2 for computation I would be inclined against this.

To make use of these new Apple computers projects would need to
re-compile the apps for the new platform, and as long as they're not
using vector intrinsics or auto-vectorization in their source code,
probably need to go through manual optimization again.

Bernd

**Comment by CharlieFenton** [comment]
> I would suspect that the "universal BOINC client" is actually a "fat" binary, which has binaries native for both ARM and Intel (x86) architecture. 

Correct

 > When run on an Intel Mac as in the post Richard reported, the x86 code should be ran, it should detect and report the SSE capability of the CPU. 

It does indeed detect SSE on an Intel Mac. The original concern was raised about BOINC not detecting SSE on an arm64 Mac, which is the correct behavior. From my Intel Mac running the BOINC 7.6.14 "fat" binary:
> Mon Jan  4 16:46:56 2021 |  | Processor: 4 GenuineIntel Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz [x86 Family 6 Model 158 Stepping 9]
Mon Jan  4 16:46:56 2021 |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfsh ds acpi mmx fxsr sse sse2 ss htt tm pbe pni pclmulqdq dtes64 mon dscpl vmx est tm2 ssse3 fma cx16 tpr pdcm sse4_1 sse4_2 x2apic movbe popcnt aes pcid xsave osxsave seglim64 tsctmr avx rdrand f16c

> I'd bet that a lot of project apps silently require at least SSE (I think on modern gccs that's even the default floating-point unit to use), i.e. they are just assuming at least a Pentium3, without even checking for that CPU capability via a plan class. Thus we should think carefully whether we would want to publish the "x86(_64)-apple-darwin" platform as an alternative BOINC platform  on these machines. Due to the very limited capabilities of Rosetta 2 for computation I would be inclined against this.

It seems to me that if the project executable requires SSE and does not state that in the plan class, that is an error on the part of the project. So this raises the question of whether BOINC should support Intel executables that do not use Intel-only extensions on Apple Silicon, or if it is better to exclude those that could run (and have properly created their plan classes) to protect projects with incorrect plan classes.

That decision is beyond my pay grade. ;=) As I have written many times, I am trying to retire from supporting BOINC. If the decision is to release a new version of BOINC without the "x86(_64)-apple-darwin" platform as an alternative BOINC platform  on Apple Silicon machines, someone other than me should do it. Note that building Universal 2 binaries requires at least Xcode 12.2. which will run only on Mac OS 10.15 or later.

**Comment by CharlieFenton** [comment]
> Thus we should think carefully whether we would want to publish the "x86(_64)-apple-darwin" platform as an alternative BOINC platform on these machines.

Before making any decision, it would be useful to try running an executable containing SSE code on an Apple Silicon Mac to see what Rosetta 2 actually does. None of the information we have identified in this discussion about SSE support or lack thereof in Rosetta 2 comes from Apple.

Also, does it make sense to notify all projects (perhaps via the boinc_projects email list) about the concerns raised here and tell them of the importance of including in the plan class any requirements for Intel-specific extensions?

**Comment by RichardHaselgrove** [comment]
It's interesting to refer back to the original report, in the light of this discussion.

> Using the BOINC universal build, I never get any new wu's. Using a non-universal BOINC does get me FGRPSEE wu's, which in general validate fine.

Something in the hardware of that machine does seem to have been handling the SSE code. It's https://einsteinathome.org/host/12848621, but it doesn't seem to have returned any further results since this debate started.

**Comment by bema-aei** [comment]
05.01.21 02:18 CharlieFenton wrote:
>
>     I would suspect that the "universal BOINC client" is actually a
>     "fat" binary, which has binaries native for both ARM and Intel
>     (x86) architecture.
>
> Correct
>
>     When run on an Intel Mac as in the post Richard reported, the x86
>     code should be ran, it should detect and report the SSE capability
>     of the CPU.
>
> It does indeed detect SSE on an Intel Mac. The original concern was 
> raised about BOINC not detecting SSE on an arm64 Mac, which is the 
> correct behavior.
>
Sorry, I was completely on the worng track. I thought that the reported 
hardware was Intel, and the universal binary diedn't detect the CPU 
features correctly.

I finally got hands on a M1 machine and could experiment with it. 
boinc_7.16.11_macOSX_x86_64 reports:

Sat Jan 16 14:30:21 2021 |  | Processor features: fpu vme de pse tsc msr 
pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfsh ds acpi mmx fxsr 
sse sse2 ss htt tm pbe pni pclmulqdq dtse64 mon dscpl vmx est tm2 ssse3 
cx16 tpr pdcm sse4_1 sse4_2 aes seglim64

I presume the code it is using to detect the CPU features is still 
hostinfo_unix.cpp from line 777 on 
(https://github.com/BOINC/boinc/blob/03b2e00990b54caab9a2d725104f1f69b469b505/client/hostinfo_unix.cpp#L777)? 
Then it's not just assuming the features of an Intel x86_64 CPU, but 
actually asking the OS for each feature. If running on an M1 Mac with 
Rosetta (2) the OS returns these features, I would judge that Rosetta 2 
actually supports these (note that e.g. avx is missing). I have no idea 
of the performance, though. But I can confirm that an App using SSE 
(Einstein@Home FGRP) runs reliably on an M1 Mac with Rosetta.

So I would indeed rely on the CPU features reported by the OS, the 
question just being how to get these features of the Rosetta 2 emulated 
CPU from the code running natively on Apple Silicon. An external helper 
program possibly?

Bernd

**Comment by bema-aei** [comment]
On 16.01.21 14:51, Bernd Machenschalk wrote:
> I have no idea
> of the performance, though. But I can confirm that an App using SSE
> (Einstein@Home FGRP) runs reliably on an M1 Mac with Rosetta.

The performance isn't up to the recent top-notch Intel (or AMD) CPUs, 
but a FGRP tasked that was designed to run ~8h on average on machines 
available 4y ago will take almost precisely 10h on a core of that M1 
MacBook. Perfromance certainly could be better with native code, but I 
think even when using unchanged x86_64 code, projects could benefit from 
that computing power.

As long as there is no solution for the CPU feature detection of the 
Rosetta emulated x86_64 and no project has native apps for Apple 
Silicon, I would advise users to rather use the x86_64 client.

Bernd

**Comment by CharlieFenton** [comment]
@bema-aei @brevilo There is a place to add the CPU detection code for Apple Silicon at line 833 in _client/hostinfo_unix.cpp_. I suspect the code will be quite similar to that for Intel Macs in `get_cpu_info_mac()`, using `sysctlbyname()` calls.

Since you now have an Apple Silicon Mac, you could do a great service to BOINC by adding the Apple Silicon code there. I suggest starting by entering `sysctl -a` in the Terminal program, which will show you all available information. See `man sysctl` in Terminal for more information. Note especially the value of `sysctl machdep.cpu.features`.

I suspect that much of the existing code can also be used on Apple Silicon Macs (`machdep.cpu.vendor`, `machdep.cpu.brand_string`, `machdep.cpu.model`, etc.) testing for `#if defined(__arm64__ ` as necessary.

**Comment by bema-aei** [comment]
On 17.01.21 01:49, CharlieFenton wrote:
> Since you now have an Apple Silicon Mac, you could do a great service 
> to BOINC by adding the Apple Silicon code there. I suggest starting by 
> entering |sysctl -a| in the Terminal program, which will show you all 
> available information.

This is interesting:

% sysctl -a|grep hw.optional.sse

% sysctl -a|grep hw.optional.neon
hw.optional.neon: 1
hw.optional.neon_hpfp: 1
hw.optional.neon_fp16: 1

% sysctl -in sysctl.proc_translated
0

but:

% arch -x86_64 sysctl -a|grep hw.optional.sse
hw.optional.sse: 1
hw.optional.sse2: 1
hw.optional.sse3: 1
hw.optional.sse4_1: 1
hw.optional.sse4_2: 1

  % arch -x86_64 sysctl -a|grep hw.optional.neon
hw.optional.neon: 1
hw.optional.neon_hpfp: 1
hw.optional.neon_fp16: 1

% arch -x86_64 sysctl -in sysctl.proc_translated
1

I.e. you can detect the ARM CPU and its features _and_ the features of 
the emulated CPU from x86_64 code running under Rosetta, but you can't 
see the emulated CPU and its features from native ARM code.

I wonder whether it would make more sense to run an x86_64 client on 
Apple Silicon than a native one.

Bernd

**Comment by CharlieFenton** [comment]
Since an Apple Silicon Mac can run both arm64 code natively and Intel code using Rosetta2 translation, BOINC should report to projects the supported features for both native arm64 code and translated Intel code. One way to determine Rosetta's supported Intel features would be to have the arm64 BOINC client launch a small helper app written in x86_64 code.

The x86_64 helper app would call `HOST_INFO::get_cpu_info()` in _client/hostinfo_unix.cpp_ and write the results to a temporary file, which would be read by the main BOINC client. This is similar to the way that the client launches a helper process for GPU detection. See the comments at the start of _client/gpu_detect.cpp_ and the method `COPROCS::launch_child_process_to_detect_gpus()` in that same source file. Of course, unlike the GPU detection helper app, the x86_64 feature detection helper app must be a separate executable file because it must be built for a different CPU architecture than the main BOINC client.

According to [this documentation](https://developer.apple.com/documentation/avfoundation/averror/3684571-rosettanotinstalled), Rosetta is not installed by default on Apple Silicon Macs, so BOINC should not report _x86_64-apple-darwin_ as an alternate platform unless it has confirmed that Rosetta2 is actually installed. Because I only learned this today, the current version 7.16.14 of BOINC always reports _x86_64-apple-darwin_ as an alternate platform on Apple Silicon Macs, whether or not Rosetta2 is available. 

I expect that for the immediate future most Apple Silicon Mac owners will install Rosetta2 because they still need to run Intel applications. As early adopters, they are likely to be technically astute users who will probably install Rosetta. So fixing this can probably wait until we have an update of BOINC that reports both the arm64 and intel86 supported feature sets, assuming this happens within a few months.

Apple has also made it clear that it is providing Rosetta2 only to facilitate the transition to Apple Silicon, and will be discontinued after a few years. 

If Rosetta is not installed, the attempt to launch x86_64 helper app will fail with some specific error code. (The actual error code will need to be determined by testing on an Apple Silicon Mac without Rosetta2 installed; some possibilities might be _EBADARCH_, _EBADEXEC_ or _ENOEXEC_). That can be used to decide whether or not to report _x86_64-apple-darwin_ as an alternate platform to project servers.

**Comment by bema-aei** [comment]
Oh, this looks a lot easier than I first thought. The feature string returned by `sysctlbyname("machdep.cpu.features")` on an M1 machine with Rosetta2 installed actually already contains the features of both the native (arm64) and emulated (x86_64) CPUs:
```
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTSE64 MON DSCPL VMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 AES SEGLIM64
```
This means that 1. we don't need to separately find out the features of both CPUs and combine these later, and 2. we can easily find out whether Rosetta2 is installed by scanning the features string for features unique to the x86_64 CPU (like MMX or SSE).

**Comment by bema-aei** [comment]
Actually, machdep.cpu.features _only_ contains the x86_64 'features'. This means that we can still use this to detect an emulated x86_64 CPU (if this doesn't exits this string should be empty), but we need another way to detect the features of the ARM64 CPU and add these manually.

**Comment by bema-aei** [comment]
deleted comments: Oh damn - compiled the test program for the wrong architecture. Never mind.
