### ISSUE TITLE
Building Projects Locally

### ISSUE THREAD

**Issue by NetherStar64** [BOINC/boinc#4143]
For many Projects like for Most of the World community Grid Projects, there is no support for non-standard Architectures like ARM. (Fir Example Raspberry Pi)

Add a Function for the Developers to include their source code on the Platform and Boinc either builds it automatically

Or you download the source code from the website and specify the path to the executable manually.

**Comment by AenBleidd** [comment]
@NetherStar64, not sure you understand the way BOINC works: BOINC does nothing with Project code but just run whatever Project provides. Just building the code in automate way without any verification (and we as BOINC can't verify it because many reasons) is not a good way. Also not so many projects have open sources. So if you want some Project to be available for ARM - it's better to ask on their forums whether it's possible.

**Comment by NetherStar64** [comment]
So the idea was that the scientist provide their code and you can use that

**Comment by AenBleidd** [comment]
It will be too hard to support because if you build it and distribute - you should support it. Better way for Projects is to do this by themselves: if they require any help with it - they could always ask the community to help.
It's not a task of BOINC to build and support any Project
