### ISSUE TITLE
Star Globe not working on all tasks

### ISSUE THREAD

**Issue by DrBobby** [BOINC/boinc#4156]
**Describe the bug**

**Steps To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**

**System Information**
 - OS: 
 - BOINC Version: 

**Additional context**

**Comment by DrBobby** [comment]
The phenomonen with the star globe not showing up in the screen saver is still going on (>3 months now).  I look today and 2 of the 5 tasks have the "show graphics" icon available.  When the "show graphics" icon is grayed out, I only get the BOINC graphics which are the statistics of the tasks in process.  The two tasks that have the "show graphics" active are both LATeah scans.  The remainder have the icon grayed out.  I only work on 3 tasks at a time.
I am running Windows 10 and have worked with Einstein@home people for over three months now attempting to solve this issue.

**Comment by bema-aei** [comment]
Einstein@Home has a couple of different applications, not all of which feature graphics. Applications that use the graphics card (GPU) for computing usually don't feature graphics, in order to save valuable GPU memory. New (CPU) applications that we issue every few months (sometimes even weeks) may not have graphics at first while testing.

**Comment by bema-aei** [comment]
IOW this is not a bug, and not a general BOINC issue, but project specific.
