### ISSUE TITLE
Bintray shuts down on May 1st, 2021

### ISSUE THREAD

**Issue by truboxl** [BOINC/boinc#4170]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
https://twitter.com/bintray/status/1357024074942144516

Now
Bintray, JCenter, GoCenter, and ChartCenter service continues.
Bintray/JCenter users should start migrating to a new hosting solution

February 28th
No more submissions will be accepted to JCenter, GoCenter, and ChartCenter
The GoCenter and ChartCenter websites will be disabled (client requests will still work)

April 12th, 26th
We will have some short maintenance windows to prepare for the shutdown

May 1st
Bintray, JCenter, GoCenter, and ChartCenter services will no longer be available (ConanCenter is not affected)

**Comment by ChristianBeer** [comment]
Since we are using Github Actions and can store artifacts there this doesn't affect us much. For PRs created from a personal repository we couldn't even upload to bintray but can upload to github actions. So my preffered action on this end of service notice would be to remove all bintray related code in the CI pipeline and scripts.
