### ISSUE TITLE
Error filter.

### ISSUE THREAD

**Issue by Sandman192** [BOINC/boinc#4258]
**Describe the problem**
A clear and concise description of the problem you're looking to solve.

**Describe the solution you'd like**
Add a filter in the event log to show only errors and to have BOINC warn you instantly that an error has occurred.

**Additional context**

**Comment by Vulpine05** [comment]
I have started looking at developing this feature.  I created a new button to filter errors.  The button has no functionality yet, but it got me to think further of what this should do.

![image](https://github.com/BOINC/boinc/assets/58096400/7f382677-81c7-4a76-aaa9-03565a05cfde)

Presently, there is a button to filter event log items based on the project.  If the event log is already filtered, the button changes text and will provide the option to view all events.  I think the functionality of the error filter button could be useful by just toggling error messages.  That is, if there is no project filter enabled, the error filter will list only errors when the button is pressed.  If the event log is filtered by a project, then clicking on the error filter button will show only errors for the project that is filtered (sortof, see footnote below).  Therefore, there are four different states of filters for the event log:  All event log items, all event log items for a project, error log items only for all projects, and error log items only for one project (again, sortof, see same footnote).

The text for the error button will have to change depending on state of filtration, and there will probably be some changes to the text for the project filter button as well.  I'm wondering if the text in two buttons changing at each change of state is going to make it confusing for the user.  Maybe two check boxes would be better instead of buttons?  I'm not sure,  maybe not.  If anyone can provide any feedback for UI I would appreciate it

Footnote:  When the "show only this project" button is clicked, I noticed that event logs for a project are enabled, but also any non-project specific events still display.  Looking through the code this seems to be the intent.  Therefore, to be consistent I think if a project filter is enabled with the error filter, then errors for the project plus general (non-project specific) errors should be shown.

**Comment by davidpanderson** [comment]
It's probably better to call them "alerts" rather than "errors".  They're used in situation where a user action is needed. "Error" implies that the user (or maybe BOINC) did something wrong, which is not always the case.

You find them by searching for MSG_USER_ALERT in client/*.cpp

**Comment by Vulpine05** [comment]
@davidpanderson, now that I look at this closer, I want to be sure that I completely understand some definitions.

I can revise the button to refer to these as alerts instead of errors.  That will be forward facing for the user.  However, in the code there are several locations where they are referred to as errors.

In DlgEventLog, the attribute "m_pMessageErrorAttr" is what is used to turn the event log item red.  It is this attribute that I believe needs to be filtered and displayed when the new button is clicked.  If we are calling this attribute an alert in the Manager, should we revise this to say "m_pMessageAlertAttr"?  This variable is also used in ViewMessages.

Also for consideration, it appears these alerts are generated as defined in error_numbers.h.  I don't think we should change the name of the header file nor the defined errors; I am only bringing to your attention that the word "error" is used here as well.

All that I am trying to accomplish is to make sure the we are using the correct vocabulary and any comments I add are clear for developers.

**Comment by davidpanderson** [comment]
"Alerts" are intended for situations where
1) something is limiting computation
2) there's something the user can (possibly) do about it;
we try to give the user instructions accordingly.

In terms of what the user sees, we avoid the word "error" because it implies that
the user did something wrong, which causes anxiety and is not necessarily the case.

Variable and file names don't matter here.
