### ISSUE TITLE
Possibly revise Git Development Workflow and Client Release Procedure for BOINC

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#4412]
This is a continuation of a discussion begun under PR #4267, starting [about here](https://github.com/BOINC/boinc/issues/4267#issuecomment-864531030). We agreed that BOINC's current [GIT development workflow](https://github.com/BOINC/boinc-policy/blob/master/Development_Documents/Development_Workflow.md) and [Client Release Process](https://github.com/BOINC/boinc-policy/blob/master/Development_Documents/Client_Release_Process.md) need review and possibly revision.

In particular, @AenBleidd wrote:
> I think, this development process should be revisited, and I would like to initiate this process. Personally I like the idea of stable and releasable master: it's way more easier and important to test every feature implementation and bug fix than handle hundreds of cherry-picks.

**This is the current development workflow:**

Development is done in Git Master. Developers typically create a new feature branch off master and write their new code in that feature branch. The new code is then tested by the author and possibly by a few others, and then merged into master.

Each release has three numbers: like 7.16.35. In this example, 7 is the _major release number_ and 16 is the _minor release number_. 35 is the _revision number_ (also called the _bug fix number_.) A new release changes the _minor release number_ and occasionally the _major number_. For those, you create a new release branch off master.

A new _revision_ includes only bug fixes to that _major_ and _minor_ release version. For a new _revision_, you cherry-pick only bug fixes from master into the release branch from master. Specifically, the bug fix process is: the developer creates a new bug fix branch, writes and tests the code in that bug fix branch, then merges it into master. Finally, the developer cherry-picks that merge into master.

After the release branch is considered sufficiently stable for wider testing, a test build is made available to our volunteer alpha testers as a  _development version_. If they report bugs, the developers work to fix the bugs, increase the _revision number_ / _bug fix number_, and release it to the alpha testers as a new _development version_. This process repeats until the alpha testers report no new bugs, at which time the _development version_ is released to the general public as the _recommended version_.

If additional bugs are reported by end users, the bug fix process is repeated, with or without further alpha testing, and a new _recommended version_ is released to the public.

**Development workflow proposed by @AenBleidd :** 

In [this comment](https://github.com/BOINC/boinc/issues/4267#issuecomment-864659844), @AenBleidd suggested the following work flow:
> This is an explanation of what I suggest but with two changes:
> 
> their master -> our release
> their develop -> our master

![](https://user-images.githubusercontent.com/3234209/122695424-984f3600-d240-11eb-84b7-eb9fb22db9b6.png)
which I believe was based on [this article](https://yakiloo.com/getting-started-git-flow/).

**Comment by CharlieFenton** [comment]
I performed a cursory web search for Git Workflow and found that there are a number of variations proposed by different people, but I have not investigated them. Here are my initial thoughts on the proposal from @AenBleidd.

For clarity, I will use the terms in the original diagram rather than his substitutions:
> their master -> our release
> their develop -> our master

(I assume that you are eliminating their "release" branch as not needed for our workflow, since our version numbering system doesn't have pre-release version numbers like 0.1, 0.2, etc. culminating in a release version of 1.0.)

This workflow seems rather complex. @AenBleidd expressed concern about the complexity of performing the cherry-picks in the current workflow. In this proposed workflow, I would be even more concerned about someone accidentally merging one branch into another prematurely or incorrectly. I would encourage seeking a simpler workflow with fewer places for errors, though that may not be possible.

Neither the "Features for Next releases" branch nor the "Features for future releases "branch can be merged into another branch until all bug fixing is complete for a minor release. This won't work well when we have many people working on different feature branches simultaneously, unless we add yet another "temporary features branch" to accumulate all the separate feature branches. Otherwise feature branches developed during the testing and bug fixes for one release will sit in limbo for a long time, and may easily be overlooked when it comes time to begin the process for the following minor release.

These are my immediate thoughts. I may add more later.

**Comment by RichardHaselgrove** [comment]
As a member of the working group that drew up the current release document, I remember being warned to be very careful in my use of language and terminology in this area.

In particular, it was explained that there is a significant difference between "Git workflow" and "GitHub workflow". Our final proposal was more closely aligned with Git**Hub** workflow.

**Comment by CharlieFenton** [comment]
I notice that the workflow diagram which @AenBleidd included in his proposal was not included in the email sent to subscribers for this issue. It can be found [here](https://jacovanstaden.files.wordpress.com/2011/03/git-flow-overview.jpg).

**Comment by AenBleidd** [comment]
My concern mainly was from misunderstanding of that fact that release branch is a feature-freezed and used for bugfixing only (maybe because this was done in the past). So if we stick to this rule and for every release with feature implementation will increment MINOR number - then almost everything should be fine.
Main issue I see now with the current process (and have no good idea how to solve it in the best way without splitting repository - and I really don't want to do this) is Android application because every new release will contain not only bugfixing but feature implementation too. It's technically too difficult (and slow) to fix issues in release (and merge them to master) while simultaneously implementing new features on master only. So I want to have every Android release with MINOR version incremented.
And here comes linux that has releases immediately after new tag is created.
E.g.: if I create 7.18.0 Android release, and then it will be decided to do a hotfix for linux/Windows/OSX, linux will never get this hotfix but instead will use greater version that was used for Android (personally I think, if someone builds and releases linux package without notification from BOINC that desktop release is planned for actual release, they must live with this by themselves). But this is not a good approach in general, so it need to be solved somehow.

Technically, I can do Android releases not based on client_release/* branch, but use android_release/* branch instead, but then we should be careful with versioning.

So maybe we should not change the git (of github) flow itself but try to fix another issue.

Your thoughts, folks?

**Comment by CharlieFenton** [comment]
@AenBleidd, @RichardHaselgrove: should we close this issue then and perhaps start a new issue for how to deal with the version numbering concerns between Android and linux/Windows/OSX?

How much code does Android have in common with the other platforms? I believe the build systems are significantly different. I agree that it would be good if we don't need to split the repository, but if there is little common code then should we consider that?

**Comment by AenBleidd** [comment]
> How much code does Android have in common with the other platforms?

We use the same client as Desktop does.
We had similar discussion before to move server to another repository and decided not to do this to avoid versioning hell.
The case with Android is exactly the same.

So for me now main concern is linux and their uncontrollable releases. This is what should be fixed first.

> @AenBleidd, @RichardHaselgrove: should we close this issue then and perhaps start a new issue for how to deal with the version numbering concerns between Android and linux/Windows/OSX?

I vote to close this issue.

**Comment by RichardHaselgrove** [comment]
I think it's fine to keep this thread open (for a short time, at least) as a common point for discussing issues and clarifying our mutual understanding.

> here comes linux that has releases immediately after new tag is created

I think that's slightly misleading. Linux has one source for constantly updated builds: @LocutusOfBorg's PPA. That's more like a CI programme for testing and evaluating new features: I wouldn't call it a full release. The main Linux distributions all have their own repositories for final release versions, and in general I'd suggest that they are updated more slowly than the Windows and Mac variants - partly because the distro maintainers aren't themselves part of the BOINC programming community, and rely on formal announcements from the Release Manager that 'version x.xx is ready for public use'. I don't think we've had one of those for a while.

I agree that the Android case is special. I think there are two reasons for that:
1) The BOINC Android build was allowed to languish for a long time after first release, and had a lot of catching up to do.
2) Android itself is a young operating system, and itself subject to rapid change.

@AenBleidd - what does your crystal ball say about the future pathway for BOINC on Android? Once the current work is brought up to date and released, do you anticipate that those two drivers of rapid change will continue at the current pace, or do you anticipate that as the platform matures, the rate of change will reduce to something more like the desktop environments? Bearing in mind that OS X has undergone major changes in the past year, and that Microsoft has just announced a new version of Windows. Perhaps the major problem is handling the asynchronous nature of those external drivers of change.

**Comment by AenBleidd** [comment]
> rely on formal announcements from the Release Manager that 'version x.xx is ready for public use'

They don't. I see that the next day the tag was created, linux has their PPA updated with a new version. There was no announcement about 7.16.16 release for Desktop, but linux had this release. There was no any announcement about release of 7.16.17 but linux have this release, and this release was published even before @CharlieFenton announced that OSX is ready for testing.

My crystal ball is quite cloudy these days, but it shows me that every new release of Android brings us just another pain is the place we used to use to sit on chair. Desktop as a platform is more mature and have stronger backward compatibility (can't say anything about OSX because I don't use it). I suspect that after BOINC for Android will be stabilized (I hope this will be done during this year, and we will be able to bring it back to Play Store), there will be less feature implementation. 

After I make BOINC for Android stable, I might switch back to Desktop development (maybe 50/50), so we might have more releases for Desktop too (because for now it's like 50 PRs merged for Android, 1 PR merged for other platforms). 

But the inability to control linux releases worries me a lot.  Because at the end, linux users suffers because of this situation.

So we should definitely do smth with this.

And, maybe if's a question for @LocutusOfBorg: why do you release BOINC for linux without official announcement that it's ready for testing or using?

**Comment by RichardHaselgrove** [comment]
Again, that description of Linux is wrong. Google tells me "There are over 600 Linux distros and about 500 in active development". Those are the ones that wait for the formal announcements. There is just one CI rapid-response service, which caters for a certain type of geek (like myself). There is sometimes some crossover, when an end-user signs up to the fast-track service. but that isn't its main purpose. Think of the difference between the Play Store and apk releases.

**Comment by AenBleidd** [comment]
That's true, but most of popular distros are based on Ubuntu and uses their PPAs

**Comment by RichardHaselgrove** [comment]
I stand (at least partially) corrected. My Linux Mint 20.1 has a 'Software Manager' - their equivalent of the Play store - and that's offering me v7.16.17

We ought to invite one of the distro maintainers - like @Germano0 - to join us and give us their take on the situation.

**Comment by RichardHaselgrove** [comment]
Also @lfield - BOINC's release manager for Linux.

**Comment by RichardHaselgrove** [comment]
This page may throw some light on the Linux (specifically, Debian) status, but it's too densely technical for me to take in in full.

https://tracker.debian.org/pkg/boinc

**Comment by LocutusOfBorg** [comment]
@AenBleidd 
>And, maybe if's a question for @LocutusOfBorg: why do you release BOINC for linux without official announcement that it's ready >for testing or using?

back in the days, Linux clients were behind lots of releases, nobody was ever releasing them as stable, and people were bothering us to have them updated.
So I started following git tags to keep it up-to-date and master branch for people who wanted the latest git commits (they know it is unstable).
The approach worked in the past 10 years, probably because the changes were not that many, and not many breaks were introduced since my join of the boinc Debian/Ubuntu team.

I suggest, if you want "tags" to not be taken as "stable", to use "tags" for your purpose and "releases" (on github) when you think we have to grab a new release.

This way, I can update my watch file to only look for new releases and stop updating it on each tag.

Does this work for you?

**Comment by AenBleidd** [comment]
> I suggest, if you want "tags" to not be taken as "stable", to use "tags" for your purpose and "releases" (on github) when you think we have to grab a new release.

> This way, I can update my watch file to only look for new releases and stop updating it on each tag.

> Does this work for you?

Not really: you still can't figure out for what platform release was done. When every update for every platform is done, this document is updated: https://boinc.berkeley.edu/download_all.php?dev=1&xml=1
So I'd use it instead. Yes, it looks outdated, but in reality it shows correct versions of **announced** releases for every platform

**Comment by LocutusOfBorg** [comment]
7.4.22 is really old... I'm pretty sure Debian and Ubuntu folks will complain a lot for this :/

**Comment by AenBleidd** [comment]
@LocutusOfBorg, but it's definitely better than build every new tag, including the created by mistake or for a completely different release.
You can use 7.18.0 to build linux, it should solve your downgrade issues. And then we should do smth with linux releases.
P.S. You can use **announced** Windows release versions too as it not so different from linux

**Comment by LocutusOfBorg** [comment]
ok thanks!

**Comment by AenBleidd** [comment]
Assuming that the reason of this ticket is mostly my mistake, I don't think there should be done anything here.
Closing this ticket for now.
