### ISSUE TITLE
[Android]BOINC 7.18.1 is recommended but says it's a development version

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4502]
First reported in [the forums](https://boinc.berkeley.edu/forum_thread.php?id=14356&postid=104995), by Crystal Pellet. 

BOINC 7.18.1 is the recommended version, but it shows as a development version in the messages:
1 10 Aug 09:27:32 Starting BOINC client version 7.18.1 for aarch64-android-linux-gnu
2 10 Aug 09:27:32 This a development version of BOINC and may not function properly

I installed it on my phone and see the same under Android 11.

**Comment by AenBleidd** [comment]
@Ageless93, thanks for the report. I missed this while building a release. This is just a text message leftover. I'll fix that before next release.

**Comment by smoe** [comment]
Is anything speaking against uploading 7.18.1 to Debian?

**Comment by RichardHaselgrove** [comment]
The fact that it hasn't been released by BOINC yet, for any platform other than Android.

The Android apk release (the one with the correctly formatted name) was on 2021-08-08 - nearly four months ago. The other platforms should have followed soon after, but didn't.

The total silence on development plans since then doesn't inspire confidence in the BOINC leadership team.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, "the samurai has no goal, only the path" 😉

**Comment by smoe** [comment]
And that 7.16.x releases happened after that 7.18.1 one. Just, the automated local updates are performed to the latest release wrt the release numbering, not the release dates. Since my problems to authenticate myself are fixed with 7.18.1 for whatever reason I would very much like to see the patches that went into 7.16.20 move forward to a 7.18.2 and upload it to Debian unstable and testing.
