### ISSUE TITLE
Temporary release problems following certificate expiry

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#4544]
I tried downloading and building under VS2019 for the first time today. The client built - with warnings, but it's currently running.

But the Manager failed to build. I can provide error messages tomorrow, but that's not important.

There's a suggestion that we could release a composite installer, with an updated client and ca-certificate bundle, but an older Manager. Could that keep the science on track, and buy time to sort out what's wrong with the Manager build?

**Comment by AenBleidd** [comment]
> If you can build the Manager OK, why isn't there a new release in testing already? What's the hold-up? The silence is deafening.

'I can build Manager' doesn't mean it's ready for release ;) And there is a blocker I'm working on currently: https://github.com/BOINC/boinc/issues/4073

Since it will be done - I believe we could think about new major release for alpha testing.

**Comment by RichardHaselgrove** [comment]
I don't think I'd call that a blocker, compared with all Windows clients being unable to return completed science to multiple projects.

**Comment by RichardHaselgrove** [comment]
The whole principle of the GitHub workflow is that the master branch is maintained in constant readiness, just in case of an eventuality like this. Blockers should be isolated in WIP branches until solved and merged.

I made a temporary working certificate bundle available to active participants on 30 September. Set-and-forget participants need something stronger.

Closing comms for tonight.

**Comment by CharlieFenton** [comment]
> The whole principle of the GitHub workflow is that the master branch is maintained in constant readiness, just in case of an eventuality like this. Blockers should be isolated in WIP branches until solved and merged.

Hopefully the master branch is always ready for building a release **candidate** ready to go through extensive alpha testing before becoming a public release. This is different from being ready for immediate public release, even in an emergency. The latter would require every PR to go through full alpha testing before merging into master.

I agree with @AenBleidd that the correct way to do this is to add the minimal necessary changes  to the exiting release. However, due to the terrible pollution of the current release branch _client_release/7/7.16_ due to people mistakenly merging master into it repeatedly, that will be difficult.

I created a less polluted release branch for Mac releases: _client_release/7.16/7.16.12_branch_ by branching off the  _client_release/7/7.16_ branch at a point before much of the damage was done. You might want to create a new branch from my _client_release/7.16/7.16.12_branch_ as a starting point. **Please do not merge anything into my _client_release/7.16/7.16.12_branch_**!

**Comment by AenBleidd** [comment]
I already made a branch directly from 7.16.11 release tag that was the last Windows release

**Comment by CharlieFenton** [comment]
> I already made a branch directly from 7.16.11 release tag that was the last Windows release

That works too ;=). But you may want to look at the cherry picks I merged into my _client_release/7.16/7.16.12_branch_ from master as I believe some of them are bug fixes that apply to MS Windows and Linux as well.

**Comment by AenBleidd** [comment]
@CharlieFenton, we want this hotfix release as small as possible to avoid full cycle of testing.
We can test other fixes with major release (hopefully soon)

**Comment by CharlieFenton** [comment]
I want to expand on my earlier comment about the use of the release branch rather than master. BOINC versions numbers are of the form _major.minor.bugfix_, and all releases with the same major and minor version numbers are normally built from the same release branch. The [BOINC Client Release Process](https://github.com/BOINC/boinc-policy/blob/master/Development_Documents/Client_Release_Process.md) says:
> only important bug fixes should be merged into the release branch.

This implies that all releases from a release branch must be built with the same versions of all the dependent libraries, unless using a different library version is the only way to fix a serious bug. This is especially true of an emergency fix like this one. In this case, it is sufficient to include an updated ca-bundle.crt, since this is a short-term fix and there should be a new major release very soon which can contain an updated OpenSSl library.

One reason I want to mention the importance of using the same dependent library versions throughout all releases from the same release branch (i.e., with the same BOINC major and minor version numbers) is my concern about the use of _vcpkg_. Additional care may be required to ensure that newer builds from the same release branch do not inadvertently use newer library versions.

I tried to express this concern in my comments in PR #4385 but unfortunately I said it poorly so it was not understood.

**Comment by AenBleidd** [comment]
> One reason I want to mention the importance of using the same dependent library versions throughout all releases from the same release branch (i.e., with the same BOINC major and minor version numbers) is my concern about the use of vcpkg. Additional care may be required to ensure that newer builds from the same release branch do not inadvertently use newer library versions.

This will be true for the next release.
**vcpkg** now supports *manifest mode* https://vcpkg.readthedocs.io/en/latest/users/manifests/ and it provides you a way to use some particular vesion of any dependency.
I plan to implement this for the next major release.

**Comment by AenBleidd** [comment]
@CharlieFenton, is ca-bundle.crt used on OSX?

**Comment by RichardHaselgrove** [comment]
Oops. I did build v7.16.20 from a zip download on Monday morning, using my usual VS2013 under Windows 7. The machine I deployed it on is still running fine, so I'd be happy with that.

I might try a VS2019 build from master later, purely for fun - it's not germane to this issue.

**Comment by CharlieFenton** [comment]
> is ca-bundle.crt used on OSX?

Yes, but the Mac build has not had this problem because it has used newer versions of OpenSSL for both the build of curl and for the client for several years. It has used openssl-1.1.0l (the last character is lower case L) since BOINC 7.16.17. 

Please note that curl is not the only place that BOINC uses OpenSSL; the BOINC client code itself also uses OpenSSL extensively. So I suspect that your PR #4545 may not fully eliminate the need for OpenSSL on MS Windows.

**Comment by AenBleidd** [comment]
@CharlieFenton,

> Yes, but the Mac build has not had this problem because it has used newer versions of OpenSSL for both the build of curl and for the client for several years.

Is there a way to get rid of it and use OSX system certificate store (whatever it's called?).
What advantages our own 'ca-bundle.crt' gives us?

**Comment by CharlieFenton** [comment]
> What advantages our own 'ca-bundle.crt' gives us?

This answer applies to MSWindows as well as OS X, and perhaps to Linux. As I have mentioned elsewhere, it is common for people to repurpose their old obsolete computers to run BOINC when they upgrade. Some of those computers are running a version of the OS that is no longer supported, such as Windows 7 or MacOS 10.13, which BOINC still supports, even with our new releases.
In fact, it is not unusual for some BOINC volunteers to run these past-support operating systems on their current computers.

I suspect that the OS developers (e.g., Microsoft or Apple) no longer update the system-provided certificate for operating systems they no longer support, so using the system-provided certificate may create a worse situation than we have now using OpenSSL with a BOINC-provided certificate. Manually upgrading a system-provided certificate is likely beyond the understanding of most users.

A better solution might be to do the following three things:
[1] Implement an automatic or semi-automatic process that periodically updates _curl/ca-bundle.crt_ in GIT master so each new release of BOINC has the most current available certificate set.

[2] BOINC should alert the user in clear language when the certificate is expired or near expiration, with a link to instructions how to fix the problem. Ideally, this alert should be more noticeable than an entry in the _Event Log_ or even a _Notice_ in the Manager since most users probably just set and forget BOINC; at minimum it should be an actual alert dialog that is visible even when BOINC Manager is hidden.

[3] Create a tiny installer for each platform (MS Windows, MacOS and Linux) that fetches the latest ca-bundle.crt either from GIT master or directly from Mozilla and updates it in the BOINC user's BOINC Data directory. An even better alternative would be to add code to the BOINC client itself to automatically download a new certificate before the current one expires; this would eliminate the need for item [2].

This third item assumes that curl is configured to look for the certificate in the BOINC Data directory at run time. I believe that is already done by client/http_curl.cpp lines 489 - 539.

**Comment by AenBleidd** [comment]
1 - This is easy to achieve
2 - This means we should implement som parsing mechanism to retrieve this information from the ca-bundle.crt file. Also, if some of the certificates is expired, that doesn't mean that it will affect any Project since we don't know which certificates are used by any Project.
3 - BOINC client might have no permissions to write to installation directory, so automatic update usually not possible.

**Comment by AenBleidd** [comment]
> I think you meant that for me
@CharlieFenton, yes, sorry, I tagged a wrong person.
Yes, this could be a solution. I need to think a little bit about it.
Thanks for the ideas!
