### ISSUE TITLE
I want a button to display black screen on android boinc

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4578]
**Describe the problem**
I want a button to prevent screen burn-in

**Describe the solution you'd like**

**Additional context**

**Comment by locuturus** [comment]
In the meanwhile you can:
1. Go to F-Droid
2. Get Coffee app to keep screen awake
3. Get FakeStandby app to create a black screen
4. Profit?!

I find FakeStandby to be buggy so I use an older release which works for me. I also need Coffee or another way to keep the screen on because FakeStandby never figured out how to do that itself.

**Comment by AenBleidd** [comment]
This is closed in favor of #5597
