### ISSUE TITLE
OSX CI build failed but shown as 'passed'

### ISSUE THREAD

**Issue by AenBleidd** [BOINC/boinc#4612]
CI build Is failed with the next error:

```
Linking boinc
ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:

	Ld /Users/runner/work/boinc/boinc/mac_build/build/boinc.build/Deployment/BOINC_Client.build/Objects-normal/x86_64/Binary/boinc normal x86_64

(1 failure)
```

https://github.com/BOINC/boinc/runs/4912711265?check_suite_focus=true

But build script ignores this.

@CharlieFenton, could you please take a look and fix both script and build?

Thanks in advance.

**Comment by CharlieFenton** [comment]
This issue mentions two separate but related problems. Both of these appear to be problems in the implementation of Github Workflow CI, not anything in my code or that I can fix. I recommend asking @ChristianBeer for assistance, since he created the CI workflows and has been their primary maintainer.

[1] The Mac build errors were fixed each time I forced a rebuild of the dependency cache. But the link errors returned the next time I caused the Github Actions CI to run without rebuilding the cache again (so it used the cached dependent libraries.) This leads me to believe that there is a problem with the dependency cache logic, which was created and has been maintained primarily by @ChristianBeer.

I thought that perhaps another Github Action might be corrupting the macOS dependency cache, but the same problem occurred when I removed all *.yml files from _.github/workflows/_ other than _osx.yml_.

One way to force a rebuild of the dependency cache is to add the following before line 148 in _3rdParty/buildMacDependencies.sh_:
`doclean="yes"`
as I did in my commit 298d5e9e2d. I don't know whether the rebuild affects only the one branch. Note that it is important to then remove that line after the cache has been rebuilt.

[2] Regarding why CI showed the failed MacOS build as 'passed':

If you look at lines 113-115 of the shell script _mac_build/buildMacBOINC-CI.sh_, you can see that it should return 1 if the build of the Manager failed:
`    if [ $retval -ne 0 ]; then cd ..; exit 1; fi
`
and similarly if the build fails for any of the other components. This script is used only for the CI builds, and was created and maintained primarily by @ChristianBeer. I have not been directly involved with work on the CI builds since coordinating with Christian when he first developed the Travis CI support in 2017, and am not familiar with the syntax or other details.

One oddity of this script is that there is a mix of `return` and `exit` statements in this script, but this has been true since Christian Beer created it in 2017 and this script has been unchanged since 26 August 2018.

**Comment by AenBleidd** [comment]
@CharlieFenton, ok, I'll play with cache then to eliminate this problem.
Regarding the build not failed when error appears - I thought it might be a side effect of 'eval' function that might not return error code correctly. Since this is not a critical issue, I'll handle it later.
Thank you for investigation!

**Comment by AenBleidd** [comment]
I've found the way to fix the issue with cache. At least for now. Will provide a PR for that.
Second issue with failed build shown as 'passed' still requires further investigation.
