### ISSUE TITLE
[CI] Switch to vcpkg manifest mode for all vcpkg builds

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#4707]
* [x]  Android ...#4702 
* [x]  Linux .........#4705 
* [x]  MinGW ....#4706 
* [x]  Windows .#4708 
* ~~MacOS~~

This is important to be able to lock dependencies versions on release branch between minor releases.

Reference: https://vcpkg.readthedocs.io/en/latest/examples/manifest-mode-cmake/

**Comment by AenBleidd** [comment]
> This is important to be able to lock dependencies versions on release branch between minor releases.

For now this is not mandatory. We don't use version pinning for Android (the only platform for now that was released with vcpkg).
Later we might decide to do that for Windows since it will be the second platform with vcpkg. If yes - I'll do that in automated way during release process, so this is definitely not a part of this ticket.
Linux doesn't need any version pinning because we don't release any linux binaries by ourselves, so this is up to distro maintainers (who are now use general autotools scripts) to handle dependencies.
OSX releases will still use current build scripts without vcpkg.

**Comment by talregev** [comment]
We solve this issue.
