### ISSUE TITLE
Android BOINC 7.18.1 pauses when run on DC power with battery setting turned off

### ISSUE THREAD

**Issue by Jord-NL** [BOINC/boinc#4873]
As per https://boinc.berkeley.edu/forum_thread.php?id=14310&postid=109523
User prefers to be answered via the forums, if that's possible, due to dyslexia and these boards being confusing to them. 

> I have been running BOINC projects on PC for awhile and wanted to make use of all the ARMv7/8 stuff I have (several SBCs, mobiles and a tablet). Those are using Android 4.4.2 to 11, all with BOINC 7.18.1. Most of them are running fine, but a couple are some pain. All of the devices are 100% dedicated to BOINC, with unnecessary stuff disabled/removed (mobiles+tablet). BOINC is excluded from optimization in all mobiles, but not in the tablet (not available) and SBCs (no need). All devices are air cooled.
>
> Case #1
> - Xiaomi Redmi Note 9 Pro (Android 11)
> * Works fine when display is active, but slows down when display is inactive. May be an Android issue. Optimization settings does not seems to matter. All the other mobiles I have, do not have this issue. (None of the SBCs either.)
> 
> Case #2
> - Huawei MediaPad M3 Lite 10 (Android 7)
> * The same as Redmi Note 9 Pro.
> * When reactivating the display on the MediaPad, the app occasionally crash. At next startup, all the running tasks have restarted from the beginning.
> 
> Case #3
> - MBX MXQ (Android 4.4.2)
> * BOINC installs fine and receives WUs, but refuses to do anything. Claims that battery needs to be charged above 10% (minimum setting). The MXQ have no battery and is DC supplied only. When disabling battery use in the settings, BOINC demands DC power to be connected first. At this point, BOINC is hogging the system, regardless of settings and has to be removed/uninstalled completely, before regaining the normal performance. Have also tried BOINC 7.16.5, but the same. It has been working with an earlier version, but can not recall which. Have tried BOINC 7.4.41/43 and 7.4.51/53, but all of them have other issues, like not connecting to projects. Not even with URLs. Have not checked 7.0.x, 7.1.x and 7.2.x versions.

**Comment by Ageless93** [comment]
(And yes, I made a new account because I forgot I changed my email address... no worries, is all me. 😀)

**Comment by TechMasse** [comment]
Huawei P9 (_Android 7_) - same as Case #1 too.

(_Headline incorrect, it pauses only - Case #3. Yes, I'm the one who reported these issues._)

**Comment by AenBleidd** [comment]
Modern Android version limit a lot applications background activity. There is not much we can do about this. Important to note, such limitations are different for different device manufacturers (I may assume this hardly depends on the hardware, but I'm not sure), and sometime even manually adding application to the exceptions in the Battery Optimizations list doesn't help a lot since OS kernel might kill the application when it's not used by the user (screen is off, no any user interactions with the device).
I observe this behavior on both of my Xiaomi devices and have no such issues on my Samsung Galaxy device.
Battery Optimization Mode will be handled in #4420.
Case no. 4 will be handled in #5305.
