### ISSUE TITLE
[Manager] [Website] New version notification not working for M1 Mac

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#4879]
**Describe the bug**
User report: has a M1 mac mini and an i5 Intel iMac. The i5 was notified of v7.20.2: the M1 wasn't.

On advice, he downloaded manually from the 'download all' page and reports successful upgrade from previous v7.16.21

https://boinc.berkeley.edu/forum_thread.php?id=14749

**System Information**
 - OS: OS X 'Monterey' 12.5
 - BOINC Version: 7.16.21 to 7.20.2 upgrade
 - Project: Einstein@home

**Comment by AenBleidd** [comment]
Manager sends notification about new version once in 28 days (IIRC), so I believe this is just a bad timing.

**Comment by RichardHaselgrove** [comment]
Read the linked thread, especially the opening post. User explicitly states:

> Clicking on "Check for new BOINC version" the BOINC on the M1 mac mini reports "There is no new version of BOINC Manager available".

after seeing and acting on the i5 notice.

**Comment by CharlieFenton** [comment]
I think I've fixed this. It was an omission from the _versions.inc_ file, which has this comment:
>// Mac Universal builds contain code for both Intel 64 and 
// Apple Silicon (ARM64) Macs, but the two architectures 
// report different primary platforms so we need to include
// these builds in both the $mac and $mac_arm arrays for
// the client's New Version Check code to handle them properly.
// See GitHub Issue #4551 for more details.
 
However, when 7.20.0 was released as a Development version for alpha testing, I added it only to the $mac array, and did the same for 7.20.1 and 7.20.2 when they replaced the earlier Development versions. Since _New Version Check_ ignores Development versions, this did not cause any problems until 7.20.2 was promoted to a public release (Recommended Version.) 

In the future, we should remember to add the Mac Development version releases to both the $mac and $mac_arm arrays to avoid this oversight when promoting to a public release / Recommended version.

@RichardHaselgrove Thank you for bringing this to my attention.

**Comment by CharlieFenton** [comment]
My M1 Mac is being replaced by Apple due to a problem so I can't test that I've actually fixed this until the new unit arrives, which may be 2 weeks or longer.

**Comment by RichardHaselgrove** [comment]
I see you've already commented in the message board thread. Sometimes the message boards are worth reading!

**Comment by AenBleidd** [comment]
@CharlieFenton, is this still an issue?

**Comment by CharlieFenton** [comment]
> @CharlieFenton, is this still an issue?

No. As I wrote in [this commentt](https://github.com/BOINC/boinc/issues/4879#issuecomment-1211821045), it just requires me (and @davidpanderson) remembering that, in the _versions.inc_ file, we must:
> add the Mac Development version releases to both the $mac and $mac_arm arrays to avoid this oversight when promoting to a public release / Recommended version.
