### ISSUE TITLE
VirtualBox can't be blamed this time

### ISSUE THREAD

**Issue by team109** [BOINC/boinc#4900]
**The bug**
I'm running on VirtualBox 6.1.32 and I have 4 virtual machines of my own.They are able to run normally when Hyper-V is open ,though Hyper-V cannot run when VirtualBox is even only installed.However lhc@home shows CPU virtualization support is off.So do GPUGrid.Only after I disabled Hyper-V through bcdedit and then restart can I run lhc@home again.It seems that,it's boinc who fights with Hyper-V,not VBox.

**Reproduce**
I haven't tried to.

**System Info**
Win11
BOINC 7.20.2
VirtualBox 6.1.32

**Comment by team109** [comment]
Please forgive me that English is a second language.

**Comment by team109** [comment]
Yes it can be reproducted simply by 
> bcdedit /set hypervisorlaunchtype auto 
> then restart

**Comment by Ageless93** [comment]
By default Hyper-V will disable VirtualBox when it detects that the other hypervisor is installed, this is because they can't both be using the virtualization (VT-x) on the CPU at the same time. There are ways around that (https://www.how2shout.com/how-to/use-virtualbox-and-hyper-v-together-on-windows-10.html) but you'll have to test whether that works that way on Windows 11 as well. 

The above will allow VirtualBox to use Hyper-V as the hypervisor of choice. 
BOINC can only work with VirtualBox not with any other hypervisor. A quick search shows that in #1974 the developers thought of adding Hyper-V support, but decided against it as it isn't supported in Windows 10 Home Edition.

**Comment by team109** [comment]
Yes I was using as that link says, the paravirtualization interface was set to Hyper-V, and my own vm was working all right, that's the problem.
Besides, Windows 10 Home *is* able to run Hyper-V service. It's easily searched that you only need to run this bat:
```
pushd "%~dp0"
dir /b %SystemRoot%\servicing\Packages\*Hyper-V*.mum >hv.txt
for /f %%i in ('findstr /i . hv.txt 2^>nul') do dism /online /norestart /add-package:"%SystemRoot%\servicing\Packages\%%i"
del hv.txt
Dism /online /enable-feature /featurename:Microsoft-Hyper-V -All /LimitAccess /ALL
Pause
```

**Comment by Ageless93** [comment]
BOINC devs, see https://www.how2shout.com/how-to/download-and-install-hyper-v-on-windows-10-home.html for how to do this. I'm not sure we'd want to add something to the user's computer without their express acknowledgment.

**Comment by team109** [comment]
Well, you can teach them to do it themselves.

**Comment by team109** [comment]
Anyway the problem is that VirtualBox is working all right but BOINC shows no virtualization support.

**Comment by AenBleidd** [comment]
https://github.com/BOINC/boinc/issues/3184#issuecomment-2112458414
