### ISSUE TITLE
BOINC causes my battery capacity to drop

### ISSUE THREAD

**Issue by LezheGao** [BOINC/boinc#5012]
I had use BOINC for 3 mounths,but when I used "powercfg/batteryreport" today, I found that:
![battery-report](https://user-images.githubusercontent.com/76685272/201458024-fca392b5-ff25-466c-b18f-a46e10aae286.png)
Because of file suffix restrictions, please change the suffix name to "html" before reading

**Comment by LezheGao** [comment]
before i download boinc,the capacity was 68,000 mWh

**Comment by LezheGao** [comment]
@AenBleidd

**Comment by LezheGao** [comment]
@davidpanderson

**Comment by AenBleidd** [comment]
If you keep your PC/laptop always connected to the charger, it reduces the life or your battery because it's always kept fully charged. If you want you battery to live long, you need to drain it to ~10% and then recharge. And do this regularly (ideally once a day).
And it is expected behavior of the battery if you use your laptop 24/7.
This is not the fault of the BOINC.

**Comment by LezheGao** [comment]
> If you keep your PC/laptop always connected to the charger, it reduces the life or your battery because it's always kept fully charged. If you want you battery to live long, you need to drain it to ~10% and then recharge. And do this regularly (ideally once a day). And it is expected behavior of the battery if you use your laptop 24/7. This is not the fault of the BOINC.

OK，thanks

**Comment by kotenok2000** [comment]
Couldn't you upload it as html.txt instead of png?
It works.
[201458024-fca392b5-ff25-466c-b18f-a46e10aae286.html.txt](https://github.com/BOINC/boinc/files/10201365/201458024-fca392b5-ff25-466c-b18f-a46e10aae286.html.txt)
