### ISSUE TITLE
Move all configurations in linux under /home directory.

### ISSUE THREAD

**Issue by im7mortal** [BOINC/boinc#5058]
**Describe the problem**

On [QubesOS security model have template and app VMs](https://www.qubes-os.org/doc/templates/). Template VM has installed Boinc client and manager. From this client I create app VM which can override files only under `/home` directory. I can login my projects and I can do works but when I restart my app VM I will lost all my login info. Then I need to login again. 

**Describe the solution you'd like**

Keep all session data under `/home` directory. Then all data will be preserved

**Comment by AenBleidd** [comment]
@im7mortal, this folder is configurable.
If you're running boinc via systemctl, you can check the file `/etc/init.d/boinc-client` and fix the line
`BOINC_DIR=/var/lib/boinc-client`
setting the path you want BOINC client to write files to.
Also don't forget to change this file as well: `/etc/boinc-client/config.properties`
to set the same directory instead of the default one:
`data_dir=/var/lib/boinc-client`

**Comment by im7mortal** [comment]
@AenBleidd I changed both and tried couple of times. 
As I use QubesOS I could create fresh installation easily but it never used path which I set in these configs

Any suggestions?

**Comment by AenBleidd** [comment]
BOINC client is not a regular application but a service aka daemon. And this kind of applications should have only one instance running at the same time. That means that the configuration should be in a system location.
There is currently nothing that should be changed on the client side.
