### ISSUE TITLE
7.22.0 CPU usage FULL THROTTLE on macOS Ventura.2

### ISSUE THREAD

**Issue by Chamiu** [BOINC/boinc#5072]
**Describe the bug**
The CPU usage rate set by the web server cannot be reflected, and the CPU usage rate becomes full throttle.

**Steps To Reproduce**
1. upgrade to 7.22.0 from 7.20.4
2. launch

**Expected behavior**
It works according to the CPU usage rate set on the web server.

**System Information**
- OS: macOS Ventura.2
- BOINC Version: 7.22.0

**Comment by CharlieFenton** [comment]
@davidpanderson @AenBleidd I can confirm this and see several major problems:
* Whether using web preferences or local preferences, the client does no throttling. Even with local prefs set to use 10% of CPU time both when computer is in use and when it is not in use, all the tasks use one second of CPU time every second. I see this on Einstein, WCG and Rosetta, so it is not specific to any one project.
* Since none of these projects have added the new version of web preferences which distinguishes between in-use and not-in-use values, it is logical to assume that the values should apply to both situations. Especially, if the user has selected "suspend when compute is in use" in web prefs, then the values should apply when the computer is not in use. But when using web prefs, if you open the Manager's Computing Preferences dialog, you see the default values: 75% of CPUS and 100% of CPU time for when the computer is not in use. If you then turn off the "suspend while in use" checkbox, you see that the web preference values have been applied to "when the computer is in use." This is backwards.
* For projects that don't distinguish between in-use and not-in-use, the correct implementation of web prefs should be to use those same values for both in-use and not-in-use.
* Thee is a situation where the client forgets your local settings: When setting local prefs, set values for both in-use and not-in-use (with "suspend when in use" off) and then turn "suspend when in use" on and click save. Open the dialog again and set "suspend when in use" off again. Your earlier when in-use settings are lost and replaced by the defaults of 75% of CPUS and 100% of CPU time. It should instead remember your previous settings.

I am quite certain that these problems (including the one in the title of this issue) will occur on all platforms, and are not specific to MacOS.

**Comment by CharlieFenton** [comment]
I have removed BOINC 7.22.0 from the download pages (versions.inc) and from the alpha test matrix (test.inc) because it could allow overheating in users' computers if they were depending on the throttling to keep the hardware cool. This is definitely a show-stopper.

**Comment by RichardHaselgrove** [comment]
In Windows at least (and I think Linux as well), both the BOINC Manager and boinccmd can control a second client without reference to the data directory, because the control messages are passed by GUI RPC over TCP/IP.

But there are other hurdles to jump to keep the two instances separate. I have these two command lines which enable a second instance to run under Windows - a prerequisite is that <allow_multiple_clients> is enabled in the cc_config.xml file of the primary client.

Start second client:
`D:\BOINC_v7-20-0\boinc --allow_multiple_clients --allow_remote_gui_rpc --redirectio --detach_console --gui_rpc_port 31418 --dir D:\BOINCdata2\`

Start second Manager:
`start D:\BOINC_v7-20-0\boincmgr.exe /m /n 127.0.0.1 /g 31418 /p password`

Adapt as needed.

**Comment by CharlieFenton** [comment]
@davidpanderson I just noticed another oversight: The preferences dialog in Simple View shows only the original preferences, not the new niu prefs. There is no indication in Simple View that the "Use at most xx% of CPU time" setting may be different when in use vs not in use.

**Comment by Chamiu** [comment]
Thanks for fix.

Describe the bug *fix*

The CPU usage rate set by the web server can be reflected.
![BOINC 7 22 1](https://github.com/BOINC/boinc/assets/2077600/fa61dfb6-8586-4dc1-9d81-471343a98176)

Steps To Reproduce

1. upgrade to 7.20.7 from 7.22.1
2. 21:25 (JST) at launch

Expected behavior

It works according to the CPU usage rate set on the web server.

System Information

OS: macOS Ventura.3.1
BOINC Version: 7.22.1

**Comment by Chamiu** [comment]
Add Compute Processing Preference.
![Preference 7 22 1](https://github.com/BOINC/boinc/assets/2077600/ae82a52d-5d3b-4c44-a9ce-7a3243267aaa)
