### ISSUE TITLE
BOINC Install from PPA does not work in Mint 21.1

### ISSUE THREAD

**Issue by makeasnek** [BOINC/boinc#5124]
**Describe the bug**
Just tried installing BOINC on a fresh Linux mint install. BOINC manager doesn't launch at all from app menu. When running boincmgr from command line, BOINC manager launches but says it can't connect to client.

**Steps To Reproduce**
`sudo add-apt-repository ppa:costamagnagianfranco/boinc`

`sudo apt update`

`sudo apt install boinc`

**Expected behavior**
BOINC manager opens

**Comment by AenBleidd** [comment]
@LocutusOfBorg, could you please take a look at this issue? Thank you in advance

**Comment by jamescowens** [comment]
This is essentially what I was dealing with earlier today with a user on Ubuntu 22.04. Had to adjust a number of permissions to get it to work.

**Comment by LocutusOfBorg** [comment]
Hello, yes there are few configuration changes to do in order to make it work, sadly are security permission issues.
I don't want to do the chown/chmod in apt configuration scripts, because they will introduce possible security holes (e.g. if the password file is world readable)

**Comment by AenBleidd** [comment]
So how then user should find out how to make application work?
For me having unusable application is bigger issue that possible security issue.
Do you have any idea how this could be fixed?

**Comment by RichardHaselgrove** [comment]
I hit the PPA security key issue when I upgraded a machine from Linux Mint 20.3 to 21. This affects the installation process only.

My workrounds were:
1) Client and boinccmd: I copied the binary files from a working PPA v7.20.5 installation on Mint 20.3
2) Manager: the PPA file won't run, because it was compiled against a different version of WxWidgets. I'm using a CI artifact from here.

Hope that helps to identify the issues which need addressing.

**Comment by jamescowens** [comment]
I agree with Vitalii and I think the issues around security here are largely misguided. 

1. The gui rpc password file does not need world (666 or 777 perms) to solve the problem. It does need 660 perms, and the current user should be part of the boinc group.
2. BOINC by its very nature is an "untrusted" component, so the biggest security issue is BOINC executables attacking the rest of the machine, via the injection of a bad project exe via a man in the middle attack or a bad project, not the other way around. The man in the middle attack would be very difficult, because BOINC uses TLS certificate validation in the communication process. Permissions around the current user having access to BOINC resources (such as being a member of the boinc group points in the opposite direction to the real security concern, which should be ok. Let's not get confused here on what we are trying to protect. We are not protecting boinc from the user, we are protecting the user and the machine from boinc.
3. On modern distributions, users personal files are in their group with the same name as the user, or the "users" group, which the boinc account should NOT be part of. This ensures that the exes running under the boinc account can't access user's personal files.

A general principle of a software package is that it should not leave the package installed in an unusable state after installation. That is currently what is happening and does not meet the usability standard that we should be striving for.

**Comment by jamescowens** [comment]
@LocutusOfBorg we need to resolve this, and the answer cannot be "make no changes." The package should not be in a condition where it does not work out of the box. The "official" packages are also broken.

**Comment by makeasnek** [comment]
I have sourced some instructions for how to install BOINC on Ubuntu/Debian in the meantime, perhaps these should be added to https://boinc.berkeley.edu/wiki/Installing_on_Linux until the deb packaging is sorted out. Tested on the latest ubuntu version to work.

1. If you installed any previous versions of BOINC, such as from the PPA, remove them with `sudo apt purge boinc*`. Then remove the PPA with `sudo add-apt-repository --remove ppa:costamagnagianfranco/boinc`
2. Enable universe repo if it isn't already enabled with `add-apt-repository universe`
3. `sudo apt update`
4. `sudo apt install boinc`
5. If you need GPU support do a `sudo apt install boinc-client-nvidia-cuda` (NVIDIA) or `sudo apt install boinc-client-opencl` (AMD)
6. ` sudo usermod -aG boinc your_username_here`
7. Restart the machine
8. `sudo systemctl enable --now boinc-client`

**Comment by davidpanderson** [comment]
We currently have:
https://boinc.berkeley.edu/wiki/Installing_BOINC_on_Ubuntu
https://boinc.berkeley.edu/wiki/Installing_BOINC_on_Debian

Are separate pages needed?  Is there any difference?
Can the above instructions replace the "Basic Installation" section?

**Comment by makeasnek** [comment]
Seems like this could go into the basic installation section. Ubuntu and Debian install pages could probably be merged, pending however y'all decide to do the next deb release. In the meantime though, I think the instructions provided here should be added to the Ubuntu one. I haven't tested this in Debian, I would _assume_ it would work. In any case, I don't see how running these commands could cause users any problems, but I wouldn't want to have users running extra commands needlessly.

**Comment by davidpanderson** [comment]
I updated the page; please review:
https://boinc.berkeley.edu/wiki/Installing_BOINC_on_Debian_or_Ubuntu

**Comment by makeasnek** [comment]
Looks good!

**Comment by AenBleidd** [comment]
We're gonna host our own linux packages on the official BOINC web-site.
Once this is tested and ready for publix usage - it will be separately announced.
We're not gonna fix BOINC on all the distros because we're not maintaining them.
Please stay tuned.

**Comment by Aurum420** [comment]
Thanks! I was having problems with Linux Mint 22.2 Zara so I thought I'd use Timeshift to restore my LM 21.3 that worked fine. Then BOINC failed to run and I kept getting cryptic Linux messages. I think what happened was that when I decided to upgrade (downgrade in my opinion) to LM 22.2 I'd also switch from using the franco boinc to using the official boinc using the instructions at https://boinc.berkeley.edu/linux_install.php. After 5 hours trying to fix the wrong Linux errors I found this thread and used:
1. If you installed any previous versions of BOINC, such as from the PPA, remove them with sudo apt purge boinc*. Then remove the PPA with sudo add-apt-repository --remove ppa:costamagnagianfranco/boinc
2, Enable universe repo if it isn't already enabled with add-apt-repository universe
3. sudo apt update
4. LM 21 instructions at instructions at https://boinc.berkeley.edu/linux_install.php
And BOINC works again!!!
