### ISSUE TITLE
Allow out of date certificates

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#5134]
At the moment it's Asteroids, but almost every project has had the same age old problem at some point, the certificate expires.  Now on a web browser you can just click continue and ignore the over the top safety - I mean 1 hour out of date and it's miraculously dangerous?!  There needs to be an option for this on Boinc.

**Comment by AenBleidd** [comment]
There is no excuse in 2023 have issues with SSL certificates.

**Comment by hucker75** [comment]
Sorry, but almost every project has had this problem in the last year, it's beyond a joke.  I can bypass it in my browser, why not Boinc?  I can't see how being a day out of date is somehow dangerous.  My computer, my risk.

**Comment by AenBleidd** [comment]
Browser does every connection on request. BOINC is a tool that does every connection automatically without user interaction.

Expired/incorrect certificate - is a dangerous situation, and because we don't want to make BOINC a bother, we must make it safe by default.

**Comment by hucker75** [comment]
I'm not asking you to make it "dangerous" by default.  Just have an option, hidden away in the config file.  We all know the scientists are very busy and forget to renew.  Almost every project has had it happen.  But it's not online banking, an outdated certificate isn't going to harm me.  Give the user the option.

**Comment by AenBleidd** [comment]
This anyway opens a security hole: user will forget that they set this option, and they will be immediately vulnerable.
Making complicated mechanism to track this is not valuable as well.
Project admins must always be sure that their project is working, and it's safe for their users.
If project admin doesn't care about this - how you could be sure that they value your work you do for them?

Also, from my experience, almost all projects keeps their certificates up to date, and I see no reason to make product vulnerable just for one exception.

**Comment by hucker75** [comment]
It's Boinc, not online banking, I see no need for security anyway.  Might someone intercept my points?  Not really the end of the world.

Only a user who knows what they're doing will look up such an option and use it.

A project admin is busy doing science and shouldn't be lumbered with over the top security, which I gather now has to be renewed once a year.  I forget to MOT my car (safety test) every year, so it is entirely possible people can forget "important" things.

And as I said, it's happened to most projects, otherwise it wouldn't be annoying me.  Are you saying they're all untrustworthy?  Rosetta, Asteroids, and Universe just recently, all worthwhile projects.

**Comment by AenBleidd** [comment]
Project Admin should be busy doing server administration.
Certificate update can be done automatically using free services.
Most of project admins keep their servers up-to-date, and even if they have issues - they are resolved quite fast.
Again, in 2023 there is no excuse to keep your users unsafe and vulnerable to malware.

**Comment by hucker75** [comment]
Well they don't, because it's happened to half the projects I use.
I disagree they're vulnerable, what data is going to be intercepted?  It's not like it's my bank details.
Before we had https, everything worked just fine.  I remember Rosetta only got it because a big company volunteering to help them insisted on it.
I also don't believe a 2 day expired certificate is any different than one with 2 days left.  It doesn't suddenly become hackable.
And most importantly, it should be each user's decision.

**Comment by AenBleidd** [comment]
If they don't - you should push projects to admin their projects better.
I won't argue with you further: we are making our software secure for our users and safe to use.
If project doesn't care about their users - you should reconsider whether you want to contribute to their project at all.

**Comment by hucker75** [comment]
Every project has had the problem, so I guess I shouldn't contribute to any of them.
Safety is only needed for internet banking.  I tried to use logic, I don't know why I bothered.

**Comment by AenBleidd** [comment]
Following your logic, if on the sea shore you see the sign 'No swimming! Sharks!', you'll go into the water saying 'I see no sharks there'.
And whom you blame after you being heated? Of course not yourself, but those who put the sign, saying they were unconvincing.

Our goal to make software safe. The same should be done by projects. No excuses.

**Comment by hucker75** [comment]
More like me not avoiding walking on the beach due to sharks in the water.  There's no need for security unless you're typing in credit card numbers.  What dangers are you trying to protect users from?  Stealing of points?  Worked fine for decades without it....

As for the choice, I can choose to ignore the sharks sign, but you don't even let us do that.

**Comment by AenBleidd** [comment]
Invalid certificate could mean a man-in-the-middle attack, a phishing server, etc.
After this your BOINC client could download executable file that is not safe anymore, that could be any kind of malware (e.g. keylogger) and execute it. After that when you visit your online banking - all your data could be stolen.

That is a major security breach.
That is why we must protect our users, especially from doing dangerous and stupid acts.
That is why software should be secure be default.

**Comment by davidpanderson** [comment]
I agree with Vitalii.

**Comment by hucker75** [comment]
I have AV software.  Nothing like that ever happened before https was even invented.  People only ever got viruses by opening stupid email attachments or visiting dodgy porn sites, AND not having up to date AV.  I've been in IT support since 1997, and not once has anyone got a virus unless they did all of the above.

There is such a thing as going too far with safety.  But if you want to do that, that's fine, just don't FORCE it on us.

**Comment by AenBleidd** [comment]
One more time: we create software that should be safe for our users.
Project owners should keep their users safe as well. If anyone doesn't do that - that's not the problem of the tool creators.
Also, we must keep our users from doing stupid and dangerous acts, because not everyone is experienced enough to understand the risk (e.g. when you download some crack for the game and it's written that you need to disable AV - in 99.9% of cases these software contain some hidden miners, keyloggers and other malicious software that disables further AV launch and installation).
Making a hidden way in the software is not a good option as well, because every hidden option became known, and creates a new attack vector, that could harm Projects and users, making them vulnerable.
Also, as soon as you work in IT support, you should understand, that antivirus protects from **known** malware only, and not very effective in all other cases. If any AV is advertised as 'protect from all known and unknown malware' - that's a marketing trick and nothing more.
This is our final decision.
If you don't agree - you can fork BOINC and add this option for yourself only.
This question is closed for good, and I'll not spent any time further arguing with you.

**Comment by hucker75** [comment]
Well as I said, you're going to have to help projects work out how to keep their certificates up to date, because they're not managing.  And I don't know why you took it upon yourself to be extremely rude to 50% of projects, suggesting I shouldn't participate just because they forgot.  You may be perfect in every way and never forget to update something, but welcome to the real world....

**Comment by AenBleidd** [comment]
You are wrong about 50% of projects.
There are only two projects that have constant issues with certificates: Asteroid and Universe.
All other projects have no issues at all, or have them for a very short period of time (from couple of hours to 1 day max).
And again: if projects don't care about their servers availability - do you really think they care about their users and their work?
We, BOINC, provide a tool, that should be safe for our users.
We should not directly support any Project doing administration of their server. It's completely up to them.
They forget to update certificate - that's not our problem, especially now when you can use "Let's Encrypt" service, setup daemon on the server according to their documentation and forget about issues with certificate update forever, because everything will be done automatically.

**Comment by hucker75** [comment]
I remember Rosetta having a problem aswell, and a couple of others.  And I remember the whole of Boinc going wrong when Boinc itself was out of date - I think someone left an outdated certificate in a text file?  Anyway you can't say Universe and Asteroids aren't worthy, they're certainly more useful than finding prime numbers!

**Comment by AenBleidd** [comment]
BOINC had issues with certificates, but that was completely different issue, and we made some changes the prevent this in future.
Again, if some projects have some issues with certificates from time to time, and this issue is temporary (less than 1 day) - that's ok. But if projects are not reachable for weeks and event months - that's not good.
I treat all projects equally, but I'm talking about project admins' attitude to their users: if they don't check availability of their server for their users - do they really check results their users send to them? I so know that when project has issues with certificates - their users immediately report this on their forum. Unfortunately, some projects don't care checking forums either, and these messages are left unanswered forever.
I don't think this is a good behavior, and in this particular case I don't care what science do these projects. If they don't care about their users - why do we care about these projects?

**Comment by hucker75** [comment]
Rosetta (until recently, now there's one scientists there) had no admin presence on the forum, we couldn't contact them about anything.  But that didn't stop me supporting their worthwhile science.  A small project might not have the manpower to communicate with users.  As long as they're getting the results back they just leave things alone.

**Comment by hucker75** [comment]
Uh oh..... just got it on https://www.scienceunited.org/wiki/Android_issues
One of yours isn't it?

**Comment by AenBleidd** [comment]
Congratulations. You found an issue with incorrect server set-up. You can report it to David P. Anderson: https://boinc.berkeley.edu/anderson/

**Comment by davidpanderson** [comment]
Where did that URL come from?  Science United doesn't have a wiki, and its URL doesn't start with www

**Comment by hucker75** [comment]
I find out of date certs every day, the internet is full of them since the new 1 year rule.

Well if I ping www.scienceunited.org and scienceunited.org, they go to the same IP address of 208.68.240.115 so I guesds it's the same server?  Something outdated left on there?  https://scienceunited.org/wiki/Android_issues doesn't exist, so it's a different set of pages.
