### ISSUE TITLE
Remote desktop disables GPU, but it doesn't need to

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#5143]
**Describe the bug**
Boinc disables the GPU when Microsoft Remote Desktop Connection is in use.  But according to this webpage, it doesn't have to:
https://knowledge.civilgeo.com/knowledge-base/enabling-gpu-rendering-for-microsoft-remote-desktop/

It says you can enable GPU computing for a remote desktop, and I've checked, it works ok with Folding@Home, and if a Boinc GPU task is already running it keeps running ok for a minute until Boinc disables it.

This is nothing to do with the other report I made [#5132](https://github.com/BOINC/boinc/issues/5132), this one is not to do with multiple Boinc instances.

**Steps To Reproduce**
1. Follow instructions on https://knowledge.civilgeo.com/knowledge-base/enabling-gpu-rendering-for-microsoft-remote-desktop/ for a host running GPU tasks in Boinc.
2. Connect a remote desktop session to the host.

**Expected behavior**
Boinc should continue processing GPU tasks, but instead Boinc gives the error "Remote desktop in use; disabling GPU tasks".

**System Information**
 - OS: Windows 11
 - BOINC Version: 7.20.2

**Comment by AenBleidd** [comment]
@davidpanderson, what do you think about this request?
Personally I think that we still should disable GPU tasks by default when RDP is in use, because this could affect machines with slow GPUs (e.g. servers that usually have just integrated Intel GPU).
From the other hand, it would be nice to let users decide whether they want to stop processing GPU tasks with RDP running, but in this case there should be a new 'cc_config.xml' option (can't say it will make code more complicated but still).

**Comment by davidpanderson** [comment]
This affects only users who have done the 17-stop process described in that web page.
We can add an option in cc_config.xml that turns off the RDP check.
I'll do this.

**Comment by AenBleidd** [comment]
Thank you, @davidpanderson

**Comment by hucker75** [comment]
Actually, it appears you don't have to follow all those steps.  I just Remote Desktop connected to another machine where I hadn't followed the steps, and Folding@Home continued to function.  They also use OpenCL, so I guess Boinc would keep working too.
