### ISSUE TITLE
generate .deb installer for Debian-based Linux

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#5151]
.deb format:
   https://en.wikipedia.org/wiki/Deb_(file_format)

installing a .deb file:
   https://itsfoss.com/install-deb-files-ubuntu/

creating a .deb file:
   https://www.makeuseof.com/create-deb-packages-debian-ubuntu/
   https://www.iodigital.com/en/history/intracto/creating-debianubuntu-deb-packages

(related) installing VBox on Linux:
   https://itsfoss.com/install-virtualbox-ubuntu/

**Comment by AenBleidd** [comment]
Some additional requirements that would be nice to have:

- [ ] Two installers are required: x64 and ARM64
- [ ] Should contain BOINC Client, BOINC CLI (boinccmd) and BOINC Manager.
- [ ] All binaries should be built with libc statically linked
- [ ] Should extract all necessary files to the default location or to the location set by user (via command line or simple cli ui)
- [ ] Should set all necessary permissions, create group and add user to this group if needed
- [ ] Should be able to set autorun on system startup (systemctl)
- [ ] Should work on at least on Debian/Ubuntu
- [ ] These installers should be automatically created on CI

These are the minimal requirements, additional features could be added later

**Comment by makeasnek** [comment]
I would also add that this package should include what's currently covered by boinc-client-opencl and boinc-client-nvidia-cuda. My understanding is that these packages being installed, if not needed (due to no GPU or other brand of GPU), do not cause any harm. I usually install them both whenever I install BOINC and haven't encountered any issues doing so. There should be no reason a user needs to install a separate package to use a core feature of BOINC which is GPU support.

**Comment by Toby-Broom** [comment]
I never installed the opencl or the cuda packages and it worked fine when I did some WUs for Milkyway on nvidia, so its not clear why I would need these?

**Comment by AenBleidd** [comment]
DEB and RPM creation was done. All additional features and bugfixes will be tracked separately
