### ISSUE TITLE
BOINC Manager exits completely  when closing minimised window.

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#5164]
**Describe the bug**

**Steps To Reproduce**
1. Open boinc manager window.
2. Minimize it.
3. Hover over it.
4. Close window with middle mouse button.

**Expected behavior**
Boinc window closes without  killing boincmgr.exe
**Screenshots**
![image](https://user-images.githubusercontent.com/8822292/227054771-6dd5814f-962a-4b69-a095-cca1214c745c.png)
![image](https://user-images.githubusercontent.com/8822292/227054792-61b72ca2-ae2e-4795-a31d-d2a0360573ac.png)
**System Information**
 - OS: Microsoft Windows [Version 10.0.22621.1413]
 - BOINC Version: 7.22.0

**Additional context**
This issue was seen even on 6.10.48
https://boinc.berkeley.edu/forum_thread.php?id=11667&postid=79148

**Comment by BrianNixon** [comment]
This behaviour has been deliberately implemented (for Windows in 2b5630c9b7c2598192fe1c38a85cd24ebb02e00b): if the top-level window is closed when minimised, [`CBOINCBaseFrame::OnClose()`](https://github.com/BOINC/boinc/blob/master/clientgui/BOINCBaseFrame.cpp#L330 "clientgui/BOINCBaseFrame.cpp") destroys it, which will exit the application.

Anyone know the history/​rationale?

**Comment by RichardHaselgrove** [comment]
Under Windows, 'closing' the Manager window actually minimises it to the notification area (system tray). Right-clicking the icon - most Windows users don't have a middle button - brings up a context menu with an entry for 'Exit' - there's no point in closing it further, since it's already been closed. There's a conscious difference in the Windows implementation between "close" and "exit", but it doesn't necessarily translate easily to the other operating systems.

**Comment by BrianNixon** [comment]
We need to be careful with terminology here.

In BOINC Manager’s normal case, selecting ‘Close’ does not _close_ or _minimise_ the window; it _hides_ it (with the side-effect of also removing the taskbar button), but the application continues running.

_Minimised_ (a.k.a. _iconised_) top-level windows do have taskbar buttons.

The fact here is that the code makes a special case of a request to close a minimised window, and causes the application to exit. The discussion is whether or not that is the right thing to do (for any or all window systems).

[also _minimized_ and _iconized_, for the benefit of anybody searching for the en-⁠US spellings]

**Comment by RichardHaselgrove** [comment]
Indeed - we do have to be careful with terminology, and with interpreting the implications of user actions.

Let's concentrate on Windows, and use your word _hidden_ for the minimal-footprint case.

Under Windows XP, a BOINC Manager icon was **always** visible in the system tray when the main window was hidden.

With the change to a 'notification area' under Windows 7, the icon was always available, but was set by default to "Only show notifications" - it popped into view whenever a notice reminder was displayed, but was invisible otherwise. Windows 7 provides a clear and simple user interface for changing the default mode to "Show icon and notifications", which makes it permanently visible again.

Under Windows 10 and 11, it has become increasingly difficult to force the display mode into "Icon always visible" mode. And with some iterations of the development of the new interfaces, users have reported problems in  re-displaying the full manager window when it's hidden and icon-free. By default, BOINC only allows one copy of the Manager to be active at the same time: re-launching the application fails, because the hidden copy is still active - but Windows hasn't always restored and given focus to the running copy instead.

It's a version-control minefield, and should only be meddled-with after full consideration of all of the above. You did ask if anyone knew the history!

**Comment by BrianNixon** [comment]
All good stuff; thanks. But the issue here is nothing to do with the notification area icon.

Perhaps the question is better phrased as: “Under what circumstances should BOINC Manager _exit_?”

**Comment by BrianNixon** [comment]
Intricacies of the notification area aside, the Manager behaviour on Windows is clearly inconsistent. The ‘Close’ action should have the same effect, whichever method is used to make it happen.

PR #5174 fixes this for Windows while preserving the existing behaviour on Mac (exit if minimised, otherwise hide, per be2b680f1dea401125e28ca8b2481b6b7685066d) and GTK (always exit, never hide).

**Comment by davidpanderson** [comment]
We've always had the problem that the Manager and the client are separate programs,
and "Exit BOINC" is ambiguous - does it exit one or both?

**Comment by BrianNixon** [comment]
The “unwanted” exit under discussion here is a fast path out of the Manager only: the Exit Confirmation dialog is not shown, and the client remains running (regardless of stored preferences). The (only?) user-visible effect of the exit is that the notification area icon is removed.
