### ISSUE TITLE
7.22.0 Intel Arc 770 GPU detect failed

### ISSUE THREAD

**Issue by lugdunum1715** [BOINC/boinc#5192]
Describe the problem
Intel Arc 770 GPU can not be detect

Event log.
2023/4/11 12:43:00 |  | GPU detection failed: process exited with status 0xc0000409: (unknown error)
2023/4/11 12:43:00 |  | No usable GPUs found

**Screenshots**

**System Information**
 - OS: Win11 23430
 - BOINC Version: 7.22.0 x86_64

**Additional context**
NVIDIA GPU and INTEL intergrated GPU can be detect.
Intel driver version:  31.0.101.4257

**Comment by lugdunum1715** [comment]
stderrgpudetect.txt empty, zero byte, empty. 

stdoutgpudetect.txt
11-Apr-2023 12:26:44 [---] cc_config.xml not found - using defaults
11-Apr-2023 12:30:00 [---] cc_config.xml not found - using defaults
11-Apr-2023 12:39:51 [---] cc_config.xml not found - using defaults
11-Apr-2023 12:42:50 [---] cc_config.xml not found - using defaults

**Comment by AenBleidd** [comment]
@lugdunum1715, do you have correct GPU drivers installed?

**Comment by lugdunum1715** [comment]
yes, the newest one from Intel official site
31.0.101.4257

**Comment by AenBleidd** [comment]
Just in case, is that possible you installed BOINC as a service?
![image](https://user-images.githubusercontent.com/3234209/231190781-142f0d12-761d-4962-b7d1-6b4a3b45304c.png)
If it's installed as as service, GPU are not usable by BOINC

**Comment by lugdunum1715** [comment]
NVIDIA GPU and INTEL intergrated GPU can be detect.

And I did not make BOINC install as service.

**Comment by AenBleidd** [comment]
@lugdunum1715, could you please do some testing?

Please download this archive: https://github.com/BOINC/boinc/suites/12136353128/artifacts/639917994
You should stop both BOINC Manager and BOINC client, go to the BOINC installation location (be default it's C:\Program Files\ BOINC), make a backup copy of boinc.exe, and then overwrite it from the archive (please remember you should first extract the content of the archive in some folder, because otherwise Windows might prevent you from copying file to the Program Files directory directly from the downloaded archive.
Please don't forget also to backup your BOINC Data directory (by default located in the hidden folder C:\ProgramData\BOINC) to prevent any possible data loss after you decide to switch back to the original installation version.
After that you could start BOINC Manager again (that should automatically start the client) and check the Event log again.

**Comment by BrianNixon** [comment]
> stderrgpudetect.txt, zero byte, empty.

All right; thanks for checking.
It turns out `0xc0000409` is an uncatchable exception, which explains why there’s no debug output.
The development version of the client suggested by AenBleidd contains additional logging (to `stderrgpudetect.txt`) in the GPU detection code, so it might provide more information.

**Comment by lugdunum1715** [comment]
2023/4/13 14:30:25 |  | cc_config.xml not found - using defaults
2023/4/13 14:30:25 |  | Starting BOINC client version 7.23.0 for windows_x86_64
2023/4/13 14:30:25 |  | This a development version of BOINC and may not function properly
2023/4/13 14:30:25 |  | log flags: file_xfer, sched_ops, task
2023/4/13 14:30:25 |  | Libraries: libcurl/8.0.1-DEV Schannel zlib/1.2.13
2023/4/13 14:30:25 |  | Data directory: D:\ProgramData\BOINC
2023/4/13 14:30:25 |  | Running under account Apears
2023/4/13 14:30:26 |  | OpenCL: Intel GPU 0: Intel(R) Arc(TM) A770 Graphics (driver version 31.0.101.4257, device version OpenCL 3.0 NEO, 13005MB, 13005MB available, 9830 GFLOPS peak)


7.23 detected Intel GPU

**Comment by lugdunum1715** [comment]
stderrgpudetect.txt

NVIDIA drivers present but no GPUs found
No ATI library found.
NVIDIA drivers present but no GPUs found
No ATI library found.

**Comment by AenBleidd** [comment]
@lugdunum1715, do I understand correctly that on 7.23.0 you have Intel GPU detected, but other GPUs are not detected anymore?

**Comment by lugdunum1715** [comment]
> @lugdunum1715, do I understand correctly that on 7.23.0 you have Intel GPU detected, but other GPUs are not detected anymore?

At least Intel GPU detected, and I did not test for NVIDIA now,  NVIDIA should be work, I got A NVIDIA GPU install before, but at this time, only an Intel GPU exist.

**Comment by lugdunum1715** [comment]
7.23.0`s Intel GPU detection is unstable, some time back to

2023/4/13 17:57:05 |  | GPU detection failed: process exited with status 0xc0000409: (unknown error)

**Comment by lugdunum1715** [comment]
I restart several times, only one time, 7.23 detect A770 GPU.

**Comment by lugdunum1715** [comment]
Seems after Intel driver 4311, always detected.
