### ISSUE TITLE
Not installing Flatpak on Linux Mint 20.2 Uma

### ISSUE THREAD

**Issue by jpaulbiss** [BOINC/boinc#5295]
**Describe the bug**
I keep getting this warning: invalid Client RPC password. Try reinstalling Boinc

Using Linux Mint 20.2 Uma
**Steps To Reproduce**
1. reinstalled
2. reinstalled

**Expected behavior**

**Screenshots**

**System Information**
 - OS: 
 - BOINC Version: 

**Additional context**

**Comment by AenBleidd** [comment]
@jpaulbiss, thank you for the report.
FlatPAK installation doesn't maintained by the BOINC team.
Anyway, I'll check what went wrong and provide a fix if needed/possible.

**Comment by GuiltyDoggy** [comment]
This can come up if you try to use the Flathub flatpak's BOINC Manager to manage a client that's not the built-in one. Even though the flatpak's name on Flathub is "BOINC Manager", it actually comes with the BOINC client that it runs automatically as well. This confused me at first too because I assumed it was just the Manager and I am running my own local client in Docker. 

The flatpak has a pre-configured RPC password that it autofills for itself on launch. So trying to connect to another client will throw up this error.

First, disable the built-in client by going to Options > Other Options > Run the Client in the Manager. This will keep the flatpak's built-in client from running.

Second, if you want the "invalid Client RPC password" to not show up when launching, you have 2 options:
1. Change your own client's RPC password to match the pre-configured one that the flatpak uses (59e9117580b8e0622382992315b2f106). This is a bit of a security issue, as the flatpak uses this password for everyone.
2. Launch the flatpak from the command line, specifying the password for your client: `flatpak run edu.berkeley.BOINC --password=123`

**Comment by AenBleidd** [comment]
All the issues related to the FlatPak need to be reported here: https://github.com/flathub/edu.berkeley.BOINC
