### ISSUE TITLE
Automatic Abort of Stalled Tasks

### ISSUE THREAD

**Issue by ChrisProto** [BOINC/boinc#5347]
**Problem Statement**
There are some tasks that stall during computation.  These tasks seem to be stopped, or caught in an infinite loop, and will never complete.  The symptoms are:
1. The Progress stops
2. The Elapsed time continues to increase.
3. The Remaining (estimated) time continues to increase.

These tasks must be aborted manually.

**Desired Solution**
We need a global supervisory solution so that if a task does not progress within some time limit then it is automatically aborted.  For example, if Progress does not increase within 10 minutes, then abort.  The Progress is measured to 3 decimal places, so if it has not increased by even 1/1000 of a percent then it is safe to say it is stalled.  This should be configurable as a global parameter, and also on a per-project basis, if needed.

![image](https://github.com/BOINC/boinc/assets/537007/07254320-8e82-4412-8591-4170181e9cf2)

**Comment by davidpanderson** [comment]
A BOINC application reports its fraction done by calling an API function.
It could potentially run for a long time without calling this function -
for example, if it calls a long-running function from an external library.
So a job could be progressing even if its fraction done doesn't change for a while.

There's already a mechanism for aborting runaway jobs:
projects supply a max # of floating-point ops ( rsc_fpops_bound)
and jobs are aborted if they reach this.

I suggest contacting the Milkyway@home admins,
and ask them to make sure their app doesn't have an infinite loop,
and that their rsc_fpops_bound value is appropriate.

**Comment by MagicQuantumMechanic** [comment]
LHC VB tasks are known to run until you check and see they are not actually running a task and actually have Failed but they do not abort on their own ever and you have to do it yourself when you check one of your hosts wondering why the VB task is still running after 20+ hours of doing nothing and the floating-point  also does nothing to abort them.

Just had one a few days ago and have seen many of these since the beginning of VB tasks at T4T until today........Production site or at -dev

**Comment by MagicQuantumMechanic** [comment]
LHC VB tasks are known to run until you check and see they are not actually running a task and actually have Failed but they do not abort on their own ever and you have to do it yourself when you check one of your hosts wondering why the VB task is still running after 20+ hours of doing nothing and the floating-point also does nothing to abort them.

Just had one a few days ago and have seen many of these since the beginning of VB tasks at T4T until today........Production site or at -dev

https://lhcathomedev.cern.ch/lhcathome-dev/result.php?resultid=3234885
