### ISSUE TITLE
Settings for "When computer is not in use" are used exclusively when BOINC is run in a container

### ISSUE THREAD

**Issue by GuiltyDoggy** [BOINC/boinc#5423]
**Describe the bug**
If BOINC is run in a container, it seems that the logic to detect whether the "computer is in use" only detects when there is interactivity within the container (e.g. if you run `docker exec -it boinc /bin/bash`).

Since containers are usually left to run and not interacted with, it never appears to the boinc client that the computer is "in use", even if the user is interacting with the host machine. Therefore, only the settings for "When the computer is not in use" are respected. The settings for "When the computer is in use" is ignored under normal circumstances.

**Steps To Reproduce**
1. Run the boinc client using the docker image.
2. Set CPU usage to 75% when computer is in use.
3. Set CPU usage to 100% when computer is _not_ in use.
4. Observe that usage is 100%, even when using the computer.

**Expected behavior**
Ideally, the client should obey the usage of the host and follow the settings accordingly. Realistically, I don't know if this is solvable since the container would have to have knowledge of the host's activity. I suppose some warning/label to note this behavior for container-based clients would suffice.

**Screenshots**
![Screenshot_20231112_195211](https://github.com/BOINC/boinc/assets/52749251/a69dc687-8a5e-48d1-836b-4ff648f700a1)
As you can see, even though I am using the computer to take this screenshot, the system is obeying the computing preferences for "When the computer is not in use" - 100% CPU usage.

**System Information**
 - OS: Fedora 39
 - BOINC Version: 7.24.1

**Additional context**
None.

**Comment by AenBleidd** [comment]
Container is an isolated environment, and this is not a recommended way to use BOINC.
When user installs BOINC within the container, they should know that the behavior of the software will be different.
I don't think it's valuable to support such a use case and find a solution to detect activity on the host machine from the container.

**Comment by GuiltyDoggy** [comment]
> this is not a recommended way to use BOINC

Sorry, but even if it is not recommended it _is_ an official installation option - should it not receive the same attention as any other installation type's defect?

https://github.com/BOINC/boinc-client-docker
https://hub.docker.com/r/boinc/client/
https://boinc.berkeley.edu/wiki/Installing_on_Linux (Running BOINC using Docker)
https://boinc.berkeley.edu/trac/wiki/BoincDocker

**Comment by AenBleidd** [comment]
@GuiltyDoggy, you're right, however, as I wrote above (and you mentioned as well), when running in an isolated environment, it's very hard to get the information about the host system in a 'safe and legal' way.
We have a separate ticket to resolve the current issues with the idle detection on Linux: https://github.com/BOINC/boinc/issues/5226
Docker images of the BOINC client are not built and maintained by the BOINC maintainers. Yes, we mention this as an option to install it, but this doesn't mean that this is a recommended way of installing it.
If you have an idea how to make it better when running from the Docker container - please share it with us, and we can try to implement this.
Currently we're trying to support to most generic way of BOINC usage only, because we don't have enough manpower capacity to handle such a corner cases, unfortunately.

@davidpanderson, could you please fix the wiki to mention that idle detection doesn't work for the BOINC client when running from the Docker container?

**Comment by GuiltyDoggy** [comment]
I didn't realize that Linux idle detection was not completely working. I think there would be a way to make this work for containers using a flag written to the boinc data directory - though I am by no means a developer so I am probably missing something. But I think the following should work, and would inherit whatever mechanism is created/modified to fix `idle_time` calculation.

https://github.com/BOINC/boinc/blob/a26a9cb63b71f0f338d45951bafa14b4414cb075/client/client_state.cpp#L995-L998

At the end of that `else` block, if we wrote a flag file if the user is idle:

```
    if (!user_active)
        create /var/lib/boinc/idle_flag
    else   
        delete-if-exists /var/lib/boinc/idle_flag
    endif
```

Then change in cpu_sched.cpp, to check for the existence of idle_flag instead of `!user_active`:
https://github.com/BOINC/boinc/blob/a26a9cb63b71f0f338d45951bafa14b4414cb075/client/cpu_sched.cpp#L1668-L1669

Since /var/lib/boinc needs to be passed to the container to work anyway, creating the flag there should in effect pass the state to the container.

Of course the major downside here is the performance penalty of reading the flag from disk vs the current method. And like you said, this is a real corner case - probably not worth it.

**Comment by davidpanderson** [comment]
I updated the doc
