### ISSUE TITLE
vboxwrapper: share slot and project dirs

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#5444]
Currently vboxwrapper creates a directory 'shared' in the slot directory.
This directory is shared with the VM, which typically mounts it at /root/shared.
Vboxwrapper copies input files from the slot dir to the shared dir,
and when the job is done the client moves output files from the shared dir to the project dir.

This is needlessly complex, and also inefficient.  I propose that

- vboxwrapper share the slot directory with the VM
- vboxwrapper share the project directory with the VM

That way the app (running in the VM) can directly read input files in the project dir
(which may be shared with other jobs)
and it can directly write output files to the project dir.
In both cases it can follow the link files in the slot dir.

This could be done in a way that doesn't break existing VM apps.

**Comment by CharlieFenton** [comment]
Will this cause any problems because of file ownership / permissions, specifically on MacOS where the slot directories have user boinc_master and group boinc_project? Note that any user authorized to run and administer BOINC is a member of both groups boinc_master and boinc_project. The corresponding question may apply to other platforms.

**Comment by computezrmle** [comment]
If slots is shared from within the VM the processes inside the VM can get access to the VM definition and accidentally destroy the VM.
