### ISSUE TITLE
Mac Won't Compute GPU.

### ISSUE THREAD

**Issue by JEMcats** [BOINC/boinc#5501]
**Describe the bug**
I have a Mac with M3 and I can't GPU compute.
<img width="410" alt="Screenshot 2024-01-25 at 5 04 57 PM" src="https://github.com/BOINC/boinc/assets/67199328/856b151e-5a65-4ac7-b2fc-7ecf4f0e4a8d">

**Steps To Reproduce**
I don't know.
**Expected behavior**
To compute GPU processes 

**Screenshots**
<img width="410" alt="Screenshot 2024-01-25 at 5 04 57 PM" src="https://github.com/BOINC/boinc/assets/67199328/856b151e-5a65-4ac7-b2fc-7ecf4f0e4a8d">

**System Information**
 - OS: MacOS 14
 - BOINC Version: 7.24.2

**Additional context**
.

**Comment by AenBleidd** [comment]
Thank you for your question.
Could you please do the next:
1. Verify that you have Rosetta2 installed (https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/)
2. What are the projects you are connected to?

**Comment by JEMcats** [comment]
Yes I have Rosetta 2 installed, And I am just connected to science united.

**Comment by AenBleidd** [comment]
Science United is account manager. What are the Projects you currently have in your Projects tab of BOINC Manager?

**Comment by davidpanderson** [comment]
The only project that has an app for Apple GPU is Einstein@home, AFAIK.
But Science United doesn't currently know about Apple GPU, so it may not
attach your computer to it.
I'll look into fixing this.  Then the meantime you can attach to E@h manually.

**Comment by JEMcats** [comment]
Thank you, Can you get back to me here when this issue has been fixed?

**Comment by AenBleidd** [comment]
Basing on the comments above, this doesn't look like an issue on the BOINC client side.
Closing this ticket for now.

**Comment by CharlieFenton** [comment]
> The only project that has an app for Apple GPU is Einstein@home, AFAIK.

That is not correct. PrimeGrid has had tasks for Apple Silicon GPUs for a while. Please see [this issue](https://github.com/BOINC/boinc/issues/5456). BOINC does recognize Apple Silicon GPUs for use with OpenCl. On my M1 iMac running MacOS 14.3 Sonoma, the BOINC Event Log shows:
`OpenCL: Apple M1 0: Apple M1 (driver version 1.2 1.0, device version OpenCL 1.2, 10923MB, 10923MB available, 8 GFLOPS peak)`

However, as explained in the  above referenced issue, at last some of PrimeGrid's GPU tasks fail after a MacOS update, but this can be fixed by first running the _Uninstall BOINC_ application (distributed with BOINC Manager for the Mac), and the running the _BOINC Installer_ again.

I believe I have a better fix for this, which we will be testing soon. If testing confirms that the fix works, we'll release an update of BOINC for Mac.

**Comment by JEMcats** [comment]
Does BOINC update automatically or do I need to re download it?

**Comment by AenBleidd** [comment]
@JEMcats, BOINC doesn't have any automatic updates

**Comment by CharlieFenton** [comment]
I'll post here when the update is ready for you to download. Probably early next week.

**Comment by CharlieFenton** [comment]
I have built and  uploaded BOINC 7.24.3. This is a hot fix for issue #5456. The changes affect only the permissions checks when BOINC is started and the way the BOINC installer sets permissions. It makes no changes to the way BOINC computes or interacts with project servers.

**Comment by JEMcats** [comment]
So this should allow my computer to compute GPU?

**Comment by CharlieFenton** [comment]
> So this should allow my computer to compute GPU?

Only if you have the same problem as issue https://github.com/BOINC/boinc/issues/5456. You have never told us any details about what you mean by "I can't GPU compute."

You never answered thisquestion form @davidpanderson:
> What are the Projects you currently have in your Projects tab of BOINC Manager?

What error messages do you see that tell you there is a problem with GPU computation in BOINC?
