### ISSUE TITLE
Manager gets stuck on "Communicating with boinc client"

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#5518]
**Describe the bug**
Boinc manager got stuck on "Communicating with boinc client" if system lags during communication because of memory exhaustion.

Boinctasks can connect just fine.
**Steps To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**

**System Information**
 - OS: 10.0.22631.3007
 - BOINC Version: 7.24.1

**Additional context**
It seems as if response to a request gets lost, and boinc manager remains content to wait for a response infinitely, without timing out.

**Comment by davidpanderson** [comment]
The Manager makes periodic RPCs to the client (once/minute, more in some cases).
If the client is unresponsive (e.g. because of out-of-memory issues)
the Manager will show a 'Client not responding' error (modal dialog) for each one.

This behavior isn't as user-friendly as it could be,
but it's been this way forever and it's not clear what to do instead.
