### ISSUE TITLE
Mac - can't install using Command Line/MDM. macOS Sonoma 14.4.1

### ISSUE THREAD

**Issue by jameslbrown** [BOINC/boinc#5551]
**Describe the bug**
BOINC ownership/permissions not set when trying to deploy not using GUI.

**Steps To Reproduce**

Put the BOINC.pkg into /Applications folder.
Run:
```
sudo installer -pkg /Applications/BOINC.pkg -tgt /
installer: Package name is BOINC Manager
installer: Upgrading at base path /
installer: The upgrade was successful.
```

But get Error code -1005 when trying to run the BOINC Manager app.

I've tried running the Mac_SA_Secure.sh script, but get:

```
sudo sh /Users/jlbrown/Downloads/Mac_SA_Secure.sh/Mac_SA_Secure.sh 
Changing directory /Library/Application Support/BOINC Data file ownership to user and group boinc_master - OK? (y/n)
y
chown: ./BOINC_Finish_Install.app/Contents/_CodeSignature/CodeResources: Operation not permitted
chown: ./BOINC_Finish_Install.app/Contents/_CodeSignature: Operation not permitted
chown: ./BOINC_Finish_Install.app/Contents/MacOS/BOINC_Finish_Install: Operation not permitted
chown: ./BOINC_Finish_Install.app/Contents/MacOS: Operation not permitted
chown: ./BOINC_Finish_Install.app/Contents/Info.plist: Operation not permitted
chown: ./BOINC_Finish_Install.app/Contents/PkgInfo: Operation not permitted
chown: ./BOINC_Finish_Install.app/Contents: Operation not permitted
chown: ./BOINC_Finish_Install.app: Operation not permitted
chown: /Applications/BOINCManager.app/Contents/MacOS/BOINCManager: Operation not permitted
```

Following instructions at: [https://boinc.berkeley.edu/wiki/Tools_for_MacOS#Installing_BOINC_on_a_Mac_using_the_command_line](url)

**Expected behavior**
Would like to be able to deploy BOINC Manager (and update it) to Macs using MDM (Jamf Pro)

**Screenshots**
<img width="260" alt="Screenshot 2024-03-26 at 3 33 59 PM" src="https://github.com/BOINC/boinc/assets/5938562/a49d42b6-cfd5-44b8-bbf7-d9feaabfa956">

**System Information**
 - OS: macOS Sonoma 14.4.1
 - BOINC Version: 7.x and 8.0

**Comment by CharlieFenton** [comment]
I suspect you are the first person to use this option in years. I've updated the [instructions](https://boinc.berkeley.edu/wiki/Tools_for_MacOS#Installing_BOINC_on_a_Mac_using_the_command_line). Please try it using the updated instructions and let us know  if you still have a problem.

**Comment by jameslbrown** [comment]
Thanks @CharlieFenton - I added the /Applications to the end of the command, so it is now 

`installer -pkg /Applications/BOINC.pkg -tgt /Applications`

But when I try to run BOINC Manager I still get the -1005 error.

**Comment by CharlieFenton** [comment]
You need to have the entire Installer application intact, and run the install on the package while it is inside the installer application's bundle. Otherwise, the package can't find the other resources it needs. These resources include the PostInstall.app application, which is quite long and complex. The PostInstall app creates users and groups _boinc_master_ and _boinc_project_ as described [here](https://github.com/BOINC/boinc/wiki/SandboxUser) and [here](https://boinc.berkeley.edu/sandbox_design.php), and does many other things that are essential for BOINC to work properly.

Please note the other changes I made to the instructions:
_First SCP the "BOINC Installer.app" to the remote Mac's /tmp directory_. You must move the entire application, not just _BOINC.pkg_. That is why the command is now:
`sudo installer -pkg "/tmp/BOINC Installer.app/Contents/Resources/BOINC.pkg" -tgt /Applications`
It doesn't have to be in the /tmp directory, but _BOINC.pkg_ must remain inside the  _BOINC Installer.app_.

**Comment by jameslbrown** [comment]
Thanks Charlie. After transferring the whole 'BOINC Installer.app" to the target machines, it all worked!

Once again, thanks heaps for your help.

James.
