### ISSUE TITLE
Mac: After every OS update, 'ownership of permissions are not set properly'

### ISSUE THREAD

**Issue by jameslbrown** [BOINC/boinc#5588]
**Describe the bug**
Every time there is a macOS update, BOINC will not start because get this error:

BOINC ownership or permissions are not set properly; please reinstall BOINC.
(Error code -1301)

**Steps To Reproduce**
Run Software update on a Mac with BOINC (full) installed.

**Expected behavior**
It just opens and runs

**Screenshots**
<img width="260" alt="image" src="https://github.com/BOINC/boinc/assets/5938562/de828e3c-0b48-4de8-bc8c-fc030267859d">

**System Information**
 - OS: macOS Sonoma 14.4 (and earlier)
 - BOINC Version: 8.0, but also earlier versions.

**Comment by CharlieFenton** [comment]
Every MacOS update messes up BOINC’s permissions. This was causing GPU applications to fail without explanation. I added this message to warn the user that they must reinstall BOINC after a system update and prevent these GPU errors. See #5502 .

**Comment by jameslbrown** [comment]
Makes sense @CharlieFenton. And BOINC can't fix the permissions issue because it is not running as Admin (unlike installer).
Is there a script, or set of commands, that can be run (via MDM) to set the permissions?

**Comment by CharlieFenton** [comment]
If you download the [Unix command line version ](https://boinc.berkeley.edu/dl/boinc_8.0.0_universal-apple-darwin.dmg) it includes the Mac_SA_Secure.sh script which should fix the permissions

**Comment by jameslbrown** [comment]
I tried that but it made no difference.


% cd /Library/Application\ Support/BOINC\ Data

% sudo sh /Library/Application\ Support/BOINC\ Data/Mac_SA_Secure.sh

Password:

Changing directory /Library/Application Support/BOINC Data file ownership to user and group boinc_master - OK? (y/n)

y

%


James.

On 17 Apr 2024, at 5:32 PM, CharlieFenton ***@***.***> wrote:



If you download the Unix command line version <https://protect.checkpoint.com/v2/___https://boinc.berkeley.edu/dl/boinc_8.0.0_universal-apple-darwin.dmg___.Y3A0YTpib3Jkb2ludGVybmF0aW9uYWw6YzpvOjAwMDg2NWYyMTc4MjAzZWFhMGIwNDBlMzU5Y2I0YTUzOjY6YzE2NDo1NTFmMjRlZWJkMjZhZTFiZTBhZWNlNzc2MGQyOGU3ZmM4ZmU1Yjk1ZDI2YzM2MGNjMGUzM2VkMDY3OThiMjNkOmg6VA> it includes the Mac_SA_Secure.sh script which should fix the permissions

**Comment by Upperholme** [comment]
I don't understand why this issue has been closed. Does 'not planned' mean that the developers have no intention of fixing this? For end users it's a major PITA. I'm on the verge of giving up with BOINC altogether because of this.

**Comment by CharlieFenton** [comment]
> I don't understand why this issue has been closed. Does 'not planned' mean that the developers have no intention of fixing this? For end users it's a major PITA. I'm on the verge of giving up with BOINC altogether because of this.

@Upperholme: This is a completely different issue than your #5910 (which I have reopened.) This issue #5588 happens only when installing a new version of MacOS because Apple's MacOS installer destroys BOINC's permissions. There is nothing BOINC can do about it beyond warning the user that they must reinstall BOINC. Older versions BOINC failed to detect the permissions corruption which caused problems which were difficult to diagnose.

**Comment by Upperholme** [comment]
I appreciate that the two issues may be different. I've experienced both - they may be the same as clearly an OS update also requires a restart. What i don't understand is why BOINC is the only app that I've come across that gets broken in this way. And if there's nothing you can do about that, then perhaps there is a more user-friendly way to communicate this to users?

**Comment by CharlieFenton** [comment]
> What i don't understand is why BOINC is the only app that I've come across that gets broken in this way.

It is because of our unique security features:
https://github.com/BOINC/boinc/wiki/SandboxUser and http://boinc.berkeley.edu/sandbox_design.php

**Comment by Upperholme** [comment]
If the special features of the app mean that it must be reinstalled after every OS Update (at least), and that there are no plans to address this feature/bug, then it seems logical that this reinstall requirement is made clear up front to anyone considering installing the application on a Mac, so that users can be prepared for it and plan it in to their software updating workflow, rather than relying on an error message after the event, which serves primiarily to encourage users to uninstall and stop using what looks like a flaky app.

**Comment by eprillios** [comment]
While I understand that this is not a high-priority issue, not having to reinstall BOINC after each macOS system update would be a considerable quality-of-life improvement. Could it be possible to take this in consideration in the future, during work on BOINC's sandboxing implementation? Thanks!

**Comment by CharlieFenton** [comment]
If we had any way to fix this, we would have done so long ago. As I wrote [here](https://github.com/BOINC/boinc/issues/5588#issuecomment-2488357803):
> This issue https://github.com/BOINC/boinc/issues/5588 happens only when installing a new version of MacOS because Apple's MacOS installer destroys BOINC's permissions. There is nothing BOINC can do about it beyond warning the user that they must reinstall BOINC.

Specifically, each MacOS update installer changes the PrimaryGroupID of user _boinc_master_ from group _boinc_master_ to _staff_ (20). Fixing this requires superuser (root) privileges. The BOINC Installer has that, but the BOINC client and Manager do not (nor should they.)

**Comment by Upperholme** [comment]
Given that the developers see no alternative but to make the user re-install, I would suggest that the user experience is reviewed such that this requirement is clearly stated (for example, on this page), during the initial install process, and in the error message shown in the screenshot shared by the OP above.
In this way users can be better educated, developers won't get bored by continually having explain to users that the software isn't broken, it's actually designed that way, and we can all move on to more interesting things.

**Comment by eprillios** [comment]
> If we had any way to fix this, we would have done so long ago. As I wrote [here](https://github.com/BOINC/boinc/issues/5588#issuecomment-2488357803):
> 
> > This issue [#5588](https://github.com/BOINC/boinc/issues/5588) happens only when installing a new version of MacOS because Apple's MacOS installer destroys BOINC's permissions. There is nothing BOINC can do about it beyond warning the user that they must reinstall BOINC.
> 
> Specifically, each MacOS update installer changes the PrimaryGroupID of user _boinc_master_ from group _boinc_master_ to _staff_ (20). Fixing this requires superuser (root) privileges. The BOINC Installer has that, but the BOINC client and Manager do not (nor should they.)

I understand. My suggestion is, if broader work starts on the sandboxing implementation, then maybe the macOS situation can be addressed as well. I realize you might have other priorities at the moment, but I'm hopeful about possible future solutions. And if this is demonstrably a bug in macOS, then Apple could put in effort to fix that as well.

Has there been contact between the BOINC project and Apple? From what I understand, Apple's preferred implementation for sandboxing does not rely on user accounts and user groups. But I also imagine that app containers and permissions do not fit with BOINC's workings.

**Comment by nodevnul** [comment]
> Specifically, each MacOS update installer changes the PrimaryGroupID of user _boinc_master_ from group _boinc_master_ to _staff_ (20). Fixing this requires superuser (root) privileges. The BOINC Installer has that, but the BOINC client and Manager do not (nor should they.)

Hi. I came across this thread as I have encountered and encounter right now the BOINC permissions error message. If I do for group and user boinc_master in Terminal

```shell
/ dscacheutil -q group -a name boinc_master && dscacheutil -q user -a name boinc_master
name: boinc_master
password: *
gid: 505
users: SomeUsersHere

name: boinc_master
password: ********
uid: 505
gid: 20
dir: /var/empty
shell: /usr/bin/false
gecos: 
```

and for group and user boinc_project

```shell
/ dscacheutil -q group -a name boinc_project && dscacheutil -q user -a name boinc_project
name: boinc_project
password: *
gid: 506
users: SomeUsersHere

name: boinc_project
password: ********
uid: 506
gid: 20
dir: /var/empty
shell: /usr/bin/false
gecos:
```

the group ID 20 [staff] set for the users boinc_master and boinc_project can be seen.

So the question is if it would be sufficient to change the primary user group ID back to 505 and 506 respectively in terminal ? Or are there more dependencies to be accounted for ?

Perhaps the project could outline the script that the installer would run anyway to set group memberships correctly and/ or post the commands neccessary to do this. Maye this could be a script that could be initiated when launching BOINC and encountering wrong permissions, asking for needing to set the group memberships correctly and proceeding after admin credentials are given ?

**Comment by nodevnul** [comment]
> Yes, but this is now done automatically in BOINC version 8.2.1 available [here](https://boinc.berkeley.edu/dl/boinc_8.2.1_macOSX_universal.zip).

Ok thanks of pointing to the github project downloads as the BOINC main website still offers V 8.0.2.

**Comment by davidpanderson** [comment]
I updated the download page to offer 8.2.1

**Comment by jameslbrown** [comment]
Looks like permissions get broken after updating to macOS 15.6 from 15.5 :-(

Version 8.2.5

**Comment by CharlieFenton** [comment]
@jameslbrown what is the error number shown in the permissions error alert window?

**Comment by jameslbrown** [comment]
Actually it's different code, same text. Now it is: Error code -1072

**Comment by CharlieFenton** [comment]
@jameslbrown Thank you for that report. That error code indicates that the permissions of the podman subdirectory are not set s expected. Podman on the Mac is a work in progress and that directory will probably change in the next release.

This appears to be unrelated to the issue in this PR, or to the MacOS update. I suspect it happened to show up after the MacOS update because BOINC was relaunched after the system restarted, and would have shown up any time you quit and relaunched BOINC (such as after logging out and back in to your Mac.)

**Comment by jameslbrown** [comment]
OK. Thanks. So just deploy 8.2.1 to all computers for the moment?

**Comment by CharlieFenton** [comment]
@jameslbrown I have not seen this problem and have not received any other reports of it, so I suspect it might have been an anomaly. I suggest you quit and relaunch BOINC Manager v8.2.5, and if you don't see that happen again you should be fine deploying 8.2.5.

To clarify, I'm not aware of any permissions issues with the podman directory in 8.2.5. The reasons the directory will probably change in the next release are due to issues with running Podman tasks.

**Comment by jameslbrown** [comment]
Quitting BOINC Manager and re-opening it makes no change, still get -1072 error. Same with reboot.

**Comment by CharlieFenton** [comment]
@jameslbrown If you don't mind, please reinstall 8.25. Then quit BOINC Manager and relaunch it. Hopefully you won't see this error again, but please let me know if you do. Thanks for bearing with me.

**Comment by jameslbrown** [comment]
Thanks @CharlieFenton - re-deploying to fleet seems to be working.

**Comment by AustinConlon** [comment]
Just reproduced this on macOS 26.0 (25A354):

<img width="328" height="321" alt="Image" src="https://github.com/user-attachments/assets/6c63e665-251d-496b-8b04-d6eb220d1869" />

**Comment by AenBleidd** [comment]
@AustinConlon, what is the version of BOINC you have reproduced this on?

**Comment by Upperholme** [comment]
Curiously, just upgraded to macOS 26 and Boinc didn't give this alert for me, where it normally does whenever the OS is updated.

**Comment by CharlieFenton** [comment]
While we fixed the permissions -1301 error in BOINC 8.2.1, unfortunately a different problem was introduced in a later version. That newer issue results in permissions error -1072 , but **only the first time** that BOINC is quit and relaunched after installation. This will be fixed soon in the next release.

It shows up for some people upgrading MacOS but not for others because the MacOS upgrade process involves a system restart, causing BOINC to quit and be relaunched. But if the user had previously quit and relaunched that version of BOINC before the MacOS upgrade, then they won't get the error.

**Comment by dvsjr** [comment]
Installing boinc using Macintosh BOINCManager Version 8.2.9 as admin I get an error after install when I launch BOINCManager version 8.2.9 on Mac Tahoe 26.4 (25E246)

"BOINC ownership or permissions are not set properly; please reinstall BOINC.
(Error code -1005)" (screenshot below)

I get the frustration of this permissions issue constantly popping up, but it's not updates or the OS doing this. After installing boinc's most recent version and running it, launching boinc gives a permissions error. Not from a system update, but **immediately after installing**. This has been going on for literally years. Second reinstall after the error same results, same error. I have been using boinc with a cancer project since 2014.

Also: the readme included with the installer has multiple links that are broken: "For more options, please see the BOINC Macintosh administrator tools at:
https://boinc.berkeley.edu/wiki/Tools_for_MacOS " (link broken)

<img width="372" height="365" alt="Image" src="https://github.com/user-attachments/assets/a341c270-b53f-42a6-9eda-425297a77d63" />

**Comment by CharlieFenton** [comment]
@dvsjr:
> the readme included with the installer has multiple links that are broken

Thank  you for bringing this to my attention. I have fixed the broken links for the next version of BOINC. Meanwhile, here are the correct links fr the ones that were broken: https://github.com/BOINC/boinc/wiki/Tools-for-MacOS and https://github.com/BOINC/boinc/wiki/GPU-computing

> After installing boinc's most recent version and running it, launching boinc gives a permissions error. Not from a system update, but immediately after installing. This has been going on for literally years.

I can't reproduce this and haven't seen it. If you run the _Uninstall BOINC.app_ utility (provided with the BOINC installer in the _extras_ folder) before running _BOINC Installer.app_ does that solve the problem?

I assume you are installing BOINC by double-clicking on _BOINC Installer.app_. Is that correct? If not, how are you installing BOINC?

> Second reinstall after the error same results, same error

If you keep getting the same error, how have you fixed it so you can run BOINC?

**Comment by dvsjr** [comment]
Thank you for bringing this to my attention. I have fixed the broken links for the next version of BOINC. Meanwhile, here are the correct links fr the ones that were broken: https://github.com/BOINC/boinc/wiki/Tools-for-MacOS and https://github.com/BOINC/boinc/wiki/GPU-computing
happy to thank you for the hard work.
After installing boinc's most recent version and running it, launching boinc gives a permissions error. Not from a system update, but immediately after installing. This has been going on for literally years.
I can't reproduce this and haven't seen it. If you run the Uninstall BOINC.app utility (provided with the BOINC installer in the extras folder) before running BOINC Installer.app does that solve the problem?
I will test. I was installing in place over the previous version. 
I assume you are installing BOINC by double-clicking on BOINC Installer.app. Is that correct? If not, how are you installing BOINC?
yes double clicking as admin 
Second reinstall after the error same results, same error
If you keep getting the same error, how have you fixed it so you can run BOINC?
I posted this update last night. Will uninstall and reinstall and report. 

d

**Comment by dvsjr** [comment]
I used the uninstall app in extras folder, hesitated on uninstall but saw it posted an info window that said data wasn't removed. Uninstalled, reinstalled, it opened no error but data was gone. Had to find creds for the specific project and UNAP but was able to log in. Just wanted to mention how difficult it is to find sometimes unless you know what you are doing. Ive been using this software for a long time as I mentioned and it could have been gone but that's user error, but could possibly be avoided. 

<img width="1066" height="761" alt="Image" src="https://github.com/user-attachments/assets/2e893794-cd00-4560-9299-be430e46b354" />

<img width="544" height="733" alt="Image" src="https://github.com/user-attachments/assets/d3606023-0aba-4c5b-a0f8-ce558a66aa3e" />

**Comment by CharlieFenton** [comment]
@dvsjr:
> Uninstalled, reinstalled, it opened no error but data was gone. 

The uninstaller definitely does not remove the data. If it appeared to BOINC to be gone, then probably either it had already been badly corrupted or was somehow in the wrong place on your computer (in which case it might still be on the Mac somewhere.) Either of those could have caused the permissions error. 

If you look at your Event Log (in BOINC's _Tools_ menu) it might indicate whether it deleted any data due to corruption. The Event Log window shows only events since you last launched BOINC. If you have quit and relaunched BOINC again since reinstalling it, that information might not be in the Event Log window, but might still be available in the file _/Library/Application Support/BOINC Data.stdoutdae.txt_ or _/Library/Application Support/BOINC Data.stderrdae.txt_ which you can view by double-clicking them.

**Comment by jameslbrown** [comment]
It has now changed for me, after every OS update, it boots into Recovery Mode, with this error:

![Image](https://github.com/user-attachments/assets/16c36c35-3326-49ed-8a40-a22e393f0296)

Your computer started up in Recovery because a failure occurred during installation.
An error occurred migrating user data during an install.
Reinstall macOS to resolve the issue.

Installed Rosetta 2, and BOINC. versions 8.2.8 and 8.2.9. Maybe earlier too.

I have to go to Apple menu, then Restart. Happens on all machines, Tahoe, Sequoia, maybe earlier.

**Comment by jameslbrown** [comment]
It's definitely BOINC causing this. I removed its three items from /Library/Application Support/ and uninstalled it. Did an update and it worked perfectly - no booting into Recovery Mode.

**Comment by Upperholme** [comment]
I'm also seeing my desktop Mac (which has BOINC installed) boot into recovery mode after an OS update. This doesn't happen with my Macbook (which doesn't have BOINC installed).

**Comment by CharlieFenton** [comment]
> It's definitely BOINC causing this.

> I'm also seeing my desktop Mac (which has BOINC installed) boot into recovery mode after an OS update. This doesn't happen with my Macbook (which doesn't have BOINC installed).

OK, I'll look into this, but it probably won't be a quick fix. It would be extremely helpful to know the last version of BOINC which did _not_ trigger this (and the first version BOINC which _did_) to help pin down what changes might be responsible. Trying to pin it down by process of elimination will be very time consuming because MacOS updates happen only occasionally.
