### ISSUE TITLE
Installing BOINC on Linux Mint 21.3 -- boincmgr doesn't open

### ISSUE THREAD

**Issue by makeasnek** [BOINC/boinc#5614]
**Describe the bug**
After installing BOINC, clicking the BOINC Manager icon in the tray does nothing. Launching it from terminal gives the error ""BOINC Manager (Pre-release) is not able to start a BOINC client. Please run the client and try again""

This was tested on a clean install of Linux Mint 21.3, I chose Ubuntu 22.04 version from the [BOINC site](https://boinc.berkeley.edu/linux_install.php) since that's what this version of mint is based on. Restarting did not fix the issue.

After running: `systemctl enable boinc-client` and `systemctl start boinc-client` I was able to get boincmgr to run from terminal, but launching from menu still does not work for whatever reason.

Also, with the dark theme selected in system preferences, BOINC looks very bad.
![Screenshot from 2024-05-04 18-39-03](https://github.com/BOINC/boinc/assets/90811423/229e4946-2c67-4355-af9f-b678b0d49806)

I don't have time available to do further debugging on this, just wanted to pass along the info.

**Comment by AenBleidd** [comment]
> After installing BOINC, clicking the BOINC Manager icon in the tray does nothing. Launching it from terminal gives the error ""BOINC Manager (Pre-release) is not able to start a BOINC client. Please run the client and try again""

Sometimes you need to restart your system to get BOINC properly installed (this will be addressed in the instructions).

> After running: systemctl enable boinc-client and systemctl start boinc-client I was able to get boincmgr to run from terminal, but launching from menu still does not work for whatever reason.

Can't reproduce that.

> Also, with the dark theme selected in system preferences, BOINC looks very bad.

Can't reproduce that as well. In my case BOINC Manager looks pretty much fine:
![image](https://github.com/BOINC/boinc/assets/3234209/16b23160-4993-4fb3-b04b-950f4b8fe58c)

Closing this ticket for now.

**Comment by bWildered1** [comment]
Same thing just happened to me with a fresh install of Mint Cinnamon 21.3 on an older HP 17-p000na (AMD A6-6310).

Installed BOINC via the command line:
    ` sudo apt install boinc boinc-client-opencl boinc-client-nvidia-cuda libgl1-mesa-glx`

the latter because suggested by apt.

After install, a BOINC icon was present in the menu under Administration, but selecting (clicking) this achieved nothing.
Same after restart.

Checking process stats showed no boinc entry at all.

Manually started the client
   ` systemctl start boinc-client `

resulted in an entry in process stats, but BOINC Manager would still not start from the Desktop.

BOINC Manager could be started manually from a terminal however. 

This has 2 odd - to me - attributes:
i) The BOINC Manager window has a label 'BOINC Manager (Pre-release)', which is not on that of my other machines, and which I do not recall seeing before
i) The icon in the Panel for BOINC Manager differs from the icon for BOINC Manager in the Menu system.

I ran a systemctl command to get BOINC Client to autostart, just to get this out of the way

   ` sudo systemctl enable boinc-client`

And tested -> boinc starts up on system start

Then some little research brought back to mind that a similar thing happened when I installed BOINC on another PC some little time ago, this time on an HP G6 with an Intel i5-7200U CPU and a then fresh install of Mint 21.

The fix required adding the user to the boinc group.

Where the username is rumplestilskin and the boinc group is boinc:

    `sudo usermod -a -G boinc rumplestilskin`

BOINC Manager will now start from the Desktop (clicking the BOINC icon).


Notes: 
To check the user's current status, including what groups they belong to, enter the command 'id' at the terminal prompt,
e.g.:
```
     $id

   uid=1000(rumplestilskin), gid=1000(rumplestilskin), groups=1000(rumplestilskin), 4(adm), 24(cdrom), 27(sudo), 30(dip), 46(plugdev), 115(lpadmin), 136(sambashare) 
```

To check the boinc group exists:

```
    $grep boinc /etc/groups

    video:x:44:boinc
    render:x:110:boinc
    boinc:x:137
```

After adding the user rumplestilskin to the boinc group, an extra entry is added to the boinc group line above

   ` boinc:x:137:rumplestilskin`

The version of BOINC Manager running on the HP G6 is 7.24.1 (X86) with wxWidgets Version of 3.2.4, both newer than the versions just installed on the HP 17-p000na, which triggered this research and post (7.18.1 and 3.0.5 respectively).
I suspect that I may have built BOINC from sources for the earlier install on the HP G6 (but which still exhibited the same problem(s)).

Hope this is of help to some.

I attach a screenshot of the Panel from the HP 17-p000na, which is running Mint 21.3 Cinnamon and the older BOINC installed via the command line, showing the 2 different BOINC icons.

<img width="378" height="42" alt="Image" src="https://github.com/user-attachments/assets/616dd397-e3b6-4444-8b39-84a85d062df3" />

The icon that displays when this version of BOINC manager is started is shown on the right, with the icon associated with the menu entry shown sandwiched between the Terminal and Calculator icons.

Although the newer BOINC Manager seems to be much improved from those in the Mint repository, it still required manual configuration to allow it to autostart, and the manual addition of the user to the boinc group to allow BOINC Manager to run, at the time it was installed.

Best.

**Comment by AenBleidd** [comment]
@bWildered1, did you install BOINC using these instructions?
https://boinc.berkeley.edu/linux_install.php Installing BOINC on Linux

**Comment by bWildered1** [comment]
Probably; way back when.

I've installed BOINC many many times over the years, none of which worked out of the box.

The first time I would have done as much research as possible, staring with going to its home.

But at my age I don't remember things as I once did, and those instructions would not have helped here as far as I can see.

All the best.

**Comment by Bjohnson131** [comment]
Hello, I am seeing this issue currently on my linux mint system. the manager was installed via apt just today.  I installed boinc via snap, but snap does not appear to have the manager in its package.

**Comment by AenBleidd** [comment]
@Bjohnson131, try installing this vanilla package: https://boinc.berkeley.edu/linux_install.php?action=submit&os_num=4&version_num=2&build=stable

**Comment by Bjohnson131** [comment]
thank you, this worked!
