### ISSUE TITLE
Manager always already running

### ISSUE THREAD

**Issue by wyzwon** [BOINC/boinc#5655]
**Describe the bug**
Every time I run Boinc, I get an alert pop-up that states: "Another instance of Boinc Manager is already running."

**Steps To Reproduce**
1. Turn on computer
2. Run Boinc Manager

**Expected behavior**
No warning pop-up

**System Information**
 - OS: Windows 10 and Windows 11
 - BOINC Version: 8.0.2 (x64)

**Additional context**
Both of these computers were updated from existing installations. I do not get this alert if I manually end the Boinc Manager task in Task Manager, but it does appear even when run first thing after reboot.

**Comment by AenBleidd** [comment]
Hello @wyzwon, thank you for your report.
This happens because you have this option (highlighted by yellow) enabled:
![image](https://github.com/BOINC/boinc/assets/3234209/829b99a6-17a5-41e9-a031-1093aa1e85a2)
Usually you can find BOINC Manager hidden in the system tray menu (on the very right bottom):
![image](https://github.com/BOINC/boinc/assets/3234209/fd4023f3-a4f1-4885-9c69-f711ad240802)
I suggest you to search for BOINC Manager there first before trying to launch a new instance of it.

**Comment by wyzwon** [comment]
@AenBleidd Can you clarify for me what is specifically the known defect that won't be fixed as per the tags?

I was able to turn off that setting which saves me the first alert, but not from the following errors after closing the window with the X button.

I get what you are saying about the instance living on and being accessible in the system tray, but these steps never resulted in an alert before, and given the intended behavior is pretty intuitively "show me the window" with little care whether or not it existed in the background before that point, it's hard to believe an extra alert box to click through is the intended design, particularly since a pinned start or task bar shortcut is way quicker to click than right clicking a small icon in the small system tray menu.

I have also duplicated the issue on Linux (at least I think I have, it's hanging while waiting for a response from the client as often happens, so I can't actually interact with the manager anyways, but I do now get that pop-up there as well now).

**Comment by AenBleidd** [comment]
> but these steps never resulted in an alert before

In this way we have fixed the opposite scenario when the instance of BOINC Manager was already running, but for some reason never appeared on the foreground, and the users were confused, that they have started the BOINC Manager, but it won't start.

**Comment by RichardHaselgrove** [comment]
> the users were confused ...

... because at that point, the users are not aware that they have already opened the first instance. Because they haven't opened it themselves: it was started silently and invisibly by Windows, as part of the logon process. The 'autostart' copy is intended to appear minimised in the system tray: in newer versions, it often starts hidden in the notification area.

In older settings, launching the second copy was intended to locate the first running copy; transfer control to that first copy; and bring that first copy to visibility. The "another copy is already running" message was intended to cover failures in that sequence. It is no longer appropriate wording with these (repeated) tweaks by Microsoft. We need someone on the alpha test team, who monitors these changes in the Windows API, and keeps the BOINC Manager autostart process compatible.

**Comment by RichardHaselgrove** [comment]
Installed BOINC v8.0.3 on a Windows 11 machine. As I normally do, I verified that the BOINC Manager icon is visible in the notification area at all times. I also 'pinned' the manager to the task bar, so I have a single-click and a double-click access route available.

The double-click in the notification area worked as designed.

The single-click on the taskbar **both** opened the existing instance, **and** displayed the dialog saying that "Another instance is already running ...". These contradict each other. I had to use my saved click to dismiss the dialog.

Workround: I've replaced boincmgr.exe with a v7.24.1 copy from another machine. The UI now functions in the way that the original designers of both products intended.
