### ISSUE TITLE
Web: make 'auto subscribe' a user preference.

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#5746]
Issue #4614 and PR #5735 introduce an auto-subscribe feature for BOINC and project message board threads and posts.

In principle I agree with this, especially for 'Help desk' type boards aimed at new and inexperienced users of BOINC.

But for the rest of us, and the more 'social' areas of the message boards frequented by regular users, it's overkill.

**Describe the solution you'd like**
Add one (or possibly two) over-ride controls to the user's 'Community preferences' page. Either separate controls for 'create' and 'post' -which could default to 'on' and 'off' respectively - or a single control for both.
 
**Additional context**
See initial reaction from [BOINC message 114418](https://boinc.berkeley.edu/forum_thread.php?id=13668&postid=114418#114418) onwards.

**Comment by Ageless93** [comment]
I agree, please make the option a user preference as now each time I have been in threads to answer, I am required to pass by on the main index and unsubscribe from all the threads, as else I get bombarded by emails from others posting to those threads. Because that's another thing, each post you make to the thread sets a subscription, and each post thereafter sends an email. If the project wasn't a spammer yet, this change makes it a spammer.

**Comment by AenBleidd** [comment]
This was fixed in a little bit different way that should be more agile

**Comment by RichardHaselgrove** [comment]
Yes, we've seen the deployment on the BOINC message boards and discussed it. We agree that the implementation is adequate - nfa.
