### ISSUE TITLE
Do not include run number in packages name

### ISSUE THREAD

**Issue by Berbe** [BOINC/boinc#5789]
**Describe the problem**
Your current way of releasing packages [includes the internal GitHub run number into the package name](https://github.com/BOINC/boinc/blob/1cc0d3fd7fee819cbad37083199e36cbdd5a2b42/.github/workflows/linux-package.yml#L155C38-L155C64).

While this reference might be useful in the compilation context (to differentiate one run from another), it makes little to no sense in a package name, as this value has no meaning outside of the building context (here, GitHub workflows).

**Describe the solution you'd like**
Would it be possible that the compiled packages do not include that number, meaning a package is merely references by its name and version number?

**Additional context**
This would improve discoverability when a user wishes to pull a specific package version.
Today, the options are:
* [Package repository](https://boinc.berkeley.edu/dl/), merely offering the last version
* [GitHub releases](https://github.com/BOINC/boinc/releases), but that run number stands in the way

**Comment by AenBleidd** [comment]
Thank you for the request.
Unfortunately, this won't be changed for several reasons:
1. We don't plan to store more than 5 latest versions in every channel (stable/alpha/nightly).
2. We don't do releases very often (usually up to 2 releases per year if we are talking about stable channel)
3. And because of point 2 we encourage our users to install the latest version for which you don't need to specify the version and can just allow package manager to do its job).
