### ISSUE TITLE
Automatic adjustment for CPU affinity

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#830]
**Reported by Devaster on 21 Jul 39160755 11:33 UTC**
Can be implemented a mechanism to set automatic CPU affinity for every running project/task with selection plus when running multiple GPU clients on multiple GPUs  then they will occupy only one (the same) CPU  ?

Migrated-From: http://boinc.berkeley.edu/trac/ticket/853

**Comment by romw** [comment]
**Commented by Nicolas on 17 Aug 39161119 00:26 UTC**
CPU affinity was already suggested in #325.

I don't understand what you mean with GPU apps. If you run all GPU apps in the same CPU core, and they fight for CPU time, probably they won't be able to feed the GPU fast enough (the CPU will be the bottleneck).

**Comment by romw** [comment]
**Commented by Devaster on 18 Apr 39163258 06:40 UTC**
i think no. SETI GPU apps and GPUGrid apps are using around 1 % of CPU for gpu populating at my AMD Quad Phenom and i am running 3 instaces of SETI MB CUDA and 4 instances of AP. All 3 SETI CUDA are consuming around 5 % percent of one core.Only at start of every task it is using max cpu time but at this first seconds are done a simple benchs for function selections.
And it can be optional at last.

**Comment by romw** [comment]
**Commented by Nicolas on 5 Jul 39164738 20:26 UTC**
If you run 3 SETI CUDA apps using 5% each, and you pin them to the same core, you'd waste a lot of CPU power by using only 15% of the core.

**Comment by romw** [comment]
**Commented by Devaster on 1 Aug 39165741 14:13 UTC**
no,no,no not each 5%, all together eats 5% of CPU time...

**Comment by romw** [comment]
**Commented by Nicolas on 20 Aug 39167934 23:06 UTC**
Then you're making even less sense. Why would you want to pin those to a specific CPU?

**Comment by romw** [comment]
**Commented by Devaster on 2 Dec 39168785 21:20 UTC**
i think i would be good that they wil dont disturb other apps on other cores ...

**Comment by romw** [comment]
**Commented by tear on 21 Feb 40736792 11:06 UTC**
I did some work in the area of CPU and memory affinity; so far I have a POC patch
that sets CPU and memory affinity sequentially, starting with first CPU.

Very happy with performance improvements --
before:
http://darkswarm.org/eah-before.png

after:
http://darkswarm.org/eah-after.png

At this time it's Linux-only patch though Windows support shouldn't be a problem
once design issues are solved. About those -- I'm by no means BOINC expert
but I haven't found a nice way of user indicating which processors to use.

Global preference doesn't appear to be right approach as it applies to all
computers on user's account, so... all ideas will be much appreciated.

All that assuming there's upstream interest in adding such feature of course.

**Comment by ChristianBeer** [comment]
Short summary of the above: if tasks are pinned to a specific core they perform better because the kernel does not need to switch them between cores.

**Comment by davidpanderson** [comment]
I'm skeptical about this.  I'd like to see performance comparison on modern OSs with and without CPU pinning.

**Comment by AenBleidd** [comment]
Are there any updates on this or this ticket just can be closed?

**Comment by RichardHaselgrove** [comment]
I'd be with @davidpanderson on this one. There are sporadic outbreaks of affinity enthusiasm on the message boards, but they seem to be provoked by faith more than analysis. If there is real benefit to be had, let's have it written up with all the evidence. Otherwise, the increased complexity seems unwarranted.

**Comment by JuhaSointusalo** [comment]
I've been thinking about adding manual affinity control via app_config.xml
on app version level. Use case is Einstein' gamma ray GPU app. The app is
written in OpenCL and on Nvidia GPU it uses whole CPU core because Nvidia's
OpenCL implementation busy waits GPU. If you have multiple GPUs and want to
run multiple tasks per GPU to maximise GPU utilisation the app eats all
your CPU cores. I imagine it would be beneficial to park the app on just
one core leaving other cores for other apps. Of course I don't have any
actual data to back that one up.

I'm not interested in adding automatic affinity control. I think that gets
seriously complicated and fast. Hyperthreaded cores share some resources so
you'd need to think about how to best spread the tasks among available
cores. Even if the implementation is left simple there'd soon be complaints
about why it is not better. ("Can't you see that two tasks using app A
shouldn't share the same physical core but app B is ok.") Not to mention
these days we have multi-threaded apps and volunteers have NUMA machines.
Get affinities wrong and you'll end up with worse performance. Automatic
affinity control would pretty much end up replicating+extending OS
scheduler.

**Comment by RichardHaselgrove** [comment]
Would it be possible to prototype the NVidia OpenCL use case on one or more projects, by using an external affinity controller like Process Lasso? That would give us some idea of the available gain (if any), and hence the payback available from any development effort.

**Comment by JuhaSointusalo** [comment]
> Would it be possible to prototype the NVidia OpenCL use case on one or
> more projects, by using an external affinity controller like Process Lasso?
>
I believe Archae86 had tried Process Lasso but found out that the app
doesn't like to moved from one core to another. I don't really know how
Process Lasso works but apparently it controls processes after they have
been created started running. Which is why I thought well let's have the
client do it then.

**Comment by JuhaSointusalo** [comment]
Of course you could one client for GPU apps and another for CPU apps.
Restrict the client running GPU tasks to one core and all the GPU apps will
use that one core too.

**Comment by RichardHaselgrove** [comment]
First stage of prototyping complete. Einstein FGRPopencl1K-nvidia application, GTX 970 card, free core for each app instance,

  | 1-up | 2-up | 3-up
-- | -- | -- | --
  |   |   |  
Average | 894.412 | 807.963 | 800.297
std_dev | 4.014604 | 9.372873 | 22.92021
  |   |   |  
Sample | 64 | 114 | 72

Clear benefit from running multiple tasks per GPU, at cost of surrendering CPUs cores which could have been used for something else. Next to see if we can roll up all those wasted sleep cycles onto a single core with Process Lasso.

**Comment by truboxl** [comment]
Process Lasso now has Instance Balancer that does this. Surprise they specifically mentions BOINC...
https://bitsum.com/product-update/processlasso-v901/

To be fair, my individual testing has found it does shortens the gap between CPU time and Elapsed time from an hour to minutes for CPU tasks. Maybe long running tasks are better to be assigned manually?

**Comment by AenBleidd** [comment]
Modern OSs are quite smart, and have a very good scheduling mechanisms to use available cores in a most efficient way.
Yes, that's true, that if you lock any particular process to particular core, it **might** work faster, but that doesn't mean that this core won't be used by the OS for any other (BOINC and non-BOINC processes).
Also, you need to know the running application good enough to understand, whether core-pinning will give you on that particular CPU and advantage and speed-up.
BOINC is a type of the application that doesn't know anything about the applications it runs.
Having any automatic algorithm to do such a complicated scheduling doesn't really worth much, as it might bring more problems that the real speed-up.
Also, we need to take into the consideration, that BOINC supports Windows, Linux, MacOS and Android, that all these OSs have very different internal scheduling mechanisms that are also different on different versions of these OSs.
And finally, this feature is interesting only to the very tiny number of BOINC users.
That is why I decided to close this feature request without any further actions.
