### ISSUE TITLE
Wish: search function with RegEx and related to the current open forum level

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#90]
**Reported by AndyK on 19 Nov 37304113 00:53 UTC**
Would be very nice to have a keyword search function on each forum level with RegEx capability.

With level I mean: Main forum index, 1st level subforum like 'Number Crunching' or 'Problems and Help' etc. and displayed thread
- At the main index it should search all the forum db. ''already done''
- At the 1st subforum level it should search only that forum (including any subforums), etc.
- And when a thread is displayed the search function should be related only to that thread including all posts which are not displayed due to forum settings for that user.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/90

**Comment by lfield** [comment]
The advanced search already allows to search by forum but the search box stays as _search forums_. It should be possible to change the behavior of the search box so that it changes the scope depending on the view e.g forum_index.php,  forum_forum.php or forum_thread.php. This would be a nice enhancement for anyone who wish to start contributing.  Adding RegEx capability to the searches would be more complicated and is most probably not required.

**Comment by AenBleidd** [comment]
As it was already said, RegEx is very complicated stuff and it's not clear and usable for regular people (especially without tutorial nearby).
Closing this as 'wontfix'
